nf-core/tools

.travis.yml
nf_core/lint.py
tests/lint_examples/critical_example/LICENSE
tests/lint_examples/failing_example/LICENSE.md
tests/test_lint.py

Now having a list of filenames for an object means that the test passes if any of them are present. For example - CI testing with either Travis _or_ Circle CI.

Allow OR testing for filenames. Check MIT.

---

nf_core/lint.py

I kept getting confused about whether it should be Licence or License. Turns out that it can be both.
Also, if the `nextflow config` command files, everything falls over. Instead, capture the code and stderr and continue. This test is way off being finished yet.

Allow Brit/US spellings of Licence. Catch nextflow errors.

---

nf_core/lint.py
tests/lint_examples/license_incomplete_example/LICENSE
tests/lint_examples/wrong_license_example/LICENSE
tests/test_lint.py

Added some tests for corner cases, and check if `lint.py` is behaving as it should.

Increase code coverage for lint tests

---

tests/test_lint.py

The function `test_call_lint_pipeline()` was present twice and screwed up the unittest.
This PR fixes the issue.

Increase code coverage

---

nf_core/lint.py

Some changes I made to make linting work on my python 3.6 installation

A few bugfixes

---

.travis.yml

Addresses #20 
Enables CI testing for Python versions with Travis:
- 2.7
- 3.4
- 3.5
- 3.6

Enable testing for multiple Python versions

---

nf_core/lint.py

`params.container` variable is resolved by `nextflow config`, meaning that the tests fail with valid code.
Simplified code to just check that whatever is set is valid.

Refactor new docker slug tests to fix process.container

---

nf_core/lint.py
scripts/nf-core
tests/lint_examples/failing_example/nextflow.config
tests/lint_examples/minimal_working_example/environment.yml
tests/lint_examples/minimal_working_example/nextflow.config
tests/test_lint.py

A WIP pull-request! Most of the core code now written though, so feel free to provide comments..
* Specifically sublists, such as can be done with `pip` packages
A little refactoring:
* Progress bar now tells you the name of the function that is currently running
* New `-v` /  `--verbose` command line flag to print logging debug statements
* Passing test results now shown if debug messages shown
* Logging has been tidied up a bit
* Nicer log message formatting
* No more debug statements that mess up the progress bar
Some new linting tests:
* Additional config variables which weren't checked before
* Checks that dag is turned on by default and that the filename ends with `.svg`
* Checks that the manifest URL is set to nf-core GitHub, uses this URL to parse the workflow name
* New tests for …

Lots of new linting - mostly conda env

---

nf_core/lint.py

I have no idea why the tests pass with this 🤔 
But running on a pipeline with 3.6 throws a syntax error without this fix. Tests run fine...

Fix py3.6 syntax error

---

nf_core/lint.py
scripts/nf-core

As highlighted in https://github.com/nf-core/cookiecutter/pull/19, it's currently not very obvious when the tests are running with `--release` (which they do automatically on Travis under certain circumstances).
These changes move the log message down to the main lint results so that it can't be missed, as well as a bonus message when there are failures.

Made --release mode activity more obvious in the test results logs

---

Dockerfile

Added a `Dockerfile`. We can then use `nfcore/base` for all other nf-core containers, making it easier for us to add future fixes for Docker across all pipelines.

New base nfcore docker image

---

scripts/nf-core

At the moment, if you have a version `1.4dev` on the `master` branch of your fork then the tests fail. This change checks that it's `master` **and a `nf-core` repository** before automatically setting `--release` on the Travis tests.

Travis: only check with --release if a nf-core repo

---

.travis.yml
nf_core/lint.py
nf_core/release.py
scripts/nf-core
tests/lint_examples/minimal_working_example/nextflow.config
tests/test_lint.py
tests/test_release.py

New subcommand to bump version numbers everywhere within a pipeline.
* Starts by running linting - no point in searching for strings if there are major problems. Also parses useful things for us such as pipeline name and version
* Take regexes and switch version numbers in:
* `nextflow.config` - pipeline version and docker image tag
* If the new version contains non-numeric characters (apart from `.`), assume dev and use `latest` for the docker label
* `environment.yml` and `Dockerfile`
* Only if `environment.yml` file is present
Example output:
```
$ nf-core release . --version v1.5
INFO: Running nf-core lint tests
Running pipeline tests  [####################################]  100%  None
INFO: ===========
LINTING RESULTS
=================
54 tests passed   0 tests had warnings   0 tests …
```

New subcommand: release (bumps version numbers)

---

docs/lint_errors.md

Porting this file from the website over to this repository. This means that we can update both the lint tests and the documentation in a single commit / PR.
This repo will be cloned on the website back end and the web page documentation built from it dynamically. Updates will be pulled automatically.

Added markdown documentation of lint errors.

---

nf_core/download.py
nf_core/lint.py
nf_core/utils.py
scripts/nf-core

New subcommand to download a pipeline and its singularity containers.
* Validates pipeline input, fetches workflow details and release hash
* Download workflow files
* If `-s`is specified, downloads singularity images
* Automatically finds container names from workflow config
* Looks on the singularity hub API for a singularity image - downloads it if found
* Includes md5 check
* If not found, tries to pull singularity images using singularity
* ~If singularity is not installed, tries using docker (with [`docker2singularity`](https://github.com/singularityware/docker2singularity))~
* _removed due to configuration difficulties - may be possible to put back later with more investigation_
To do:
Example usage:
```
$ nf-core download methylseq -s
,--./,-.
___     __   __   __   ___ …
```

nf-core download <pipeline name>

---

nf_core/download.py
tests/test_download.py

- Increase the test coverage for nf-core tool's sub-command `download`.
- Refactor class code, in order to make unit-test code easier to implement

Provide unit-tests for 'download' subcommand

---

nf_core/lint.py

Crashes if access is not safe, and results in a not so user-friendly `KeyError` when linting a pipeline.
This PR fixes this.

KeyError safe dict key access

---

requirements.txt
setup.py

PyPi cannot work with the requirements.txt, as it is not
published with the nf-core tools distribution.
The better way is to define the required modules
in the respective section in the setuptools setup()
method.

Quick Patch 1.0.1: Refactor dependency management

---

tests/lint_examples/minimal_working_example/environment.yml

Update MultiQC version in miminal example to fix CI on nf-core tools

fix CI with new MultiQC version in minimal example

---

nf_core/lint.py
tests/lint_examples/failing_example/nextflow.config
tests/test_lint.py

`nextflow` had an update in syntax for process specific configuration. Idea is to encourage the new syntax (`withName: processName`) as it is more flexible. So point out the deprecated syntax (`$processName`) in *warning* while linting.
It is fairly easy now (thanks to how `nextflow` lists the current user defined configuration).  For instance
```
[u'process.$makeHISATindex.cpus', u'process.$workflow_summary_mqc.cache', u'process.$makeSTARindex.time', u'process.$star.time', u'process.$hisat2Align.time']
```
```
[u"process. 'withName:makeHISATindex'.cpus", u"process. 'withName:workflow_summary_mqc'.cache", u"process. 'withName:makeSTARindex'.time", u"process. 'withName:star'.time", u"process. 'withName:hisat2Align'.time"]
```

Add check to lint for deprecated syntax

---

nf_core/lint.py

Previous behaviour:
```python
Traceback (most recent call last):
File "/usr/local/bin/nf-core", line 117, in <module>
nf_core_cli()
File "/usr/local/lib/python3.7/site-packages/click/core.py", line 722, in __call__
return self.main(*args, **kwargs)
File "/usr/local/lib/python3.7/site-packages/click/core.py", line 697, in main
rv = self.invoke(ctx)
File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/usr/local/lib/python3.7/site-packages/click/core.py", line 895, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/usr/local/lib/python3.7/site-packages/click/core.py", line 535, in invoke
return callback(*args, **kwargs)
File "/usr/local/bin/nf-core", line 45, in lint
lint_obj = …
```

lint fails more gracefully in travis doesn't have before_install

---

nf_core/lint.py
tests/lint_examples/minimal_working_example/Dockerfile
tests/lint_examples/minimal_working_example/Singularity
tests/test_lint.py

Recreating PR #122 by @HadrienG which I reverted after accidentally merging into `master`.
This PR goes to `dev` as it should do.

reverse conda env handling (fix for #114)

---

nf_core/pipeline-template/{{cookiecutter.pipeline_slug}}/docs/configuration/adding_your_own.md
nf_core/pipeline-template/{{cookiecutter.pipeline_slug}}/docs/configuration/local.md

This should make some points mentioned in https://github.com/nf-core/tools/issues/97 more clear.
I was wrong with the redundancy I think: One document describes more in detail how you can add your own profile in here, whereas the other one describes how to use Docker/Singularity with the specific pipeline, which is something different. 
However, I took the time to update the docs a bit, adding in some more up2data ways how we normally run testcases now (adding a test.config profile for example) and removing the `./tests` directory.

Docs redundancy

---

nf_core/create.py
scripts/nf-core

Add option for the `nf-core create` command to specify the output directory. This works by running cookiecutter in a temporary directory, then moving the contents to the specified directory (needed because the cookiecutter template annoying needs to produce files in a subdirectory).
I also refactored to use object-orientated style instead, which should make life easier for testing and other stuff.

nf-core create: Refactor, add --outdir

---

nf_core/create.py

Apologies, this was the originally intended behaviour. Should now work properly with `--force`.

Make --force work for nf-core create

---

CHANGELOG.md
README.md
docs/lint_errors.md
nf_core/bump_version.py
nf_core/lint.py
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.travis.yml
scripts/nf-core
tests/lint_examples/minimal_working_example/.travis.yml
tests/test_bump_version.py
tests/test_download.py
tests/test_lint.py

* Renamed the somewhat confusing `nf-core release` to `nf-core bump-version`
* Updated the above to have a `--nextflow`/`-n` flag to bump the required nextflow version
* Added a lint test for the new Travis `before_install` branch name check

Renamed 'release' to 'bump-version' and other stuff

---

scripts/nf-core

I noticed that the lint tests in https://github.com/nf-core/rnaseq/pull/61 should be running with `--release` automatically, and failing. But they weren't.
That led me to notice this error in the logic for that block. Now fixed.

Fix logic bug in automatic --release for linting

---

README.md
nf_core/list.py

The releases are sorted in date order, so the command nf-core list only showed the first release. It now shows the latest release.
Pretty printing the date sometimes gave weird results on py2.7 as it wasn't an ordered dictionary. Addressed.
Plurals are now handled better when listing pipelines.

nf-core list: Fix release sorting and plurals

---

Dockerfile

Hi! 
this should resolve #159 . 
I've added a simple statement updating the base conda to 4.5.11 and keeping that until conda 4.6.0 is out. Then we can update for each nf-core/tools release accordingly as discussed in #159. 
If there is stuff missing/ideas/comments, let me know!

Add fixed conda version for nf-core tools

---

nf_core/pipeline-template/{{cookiecutter.name_noslash}}/nextflow.config

Removed "pipeline_info" path for standard nextflow reports in nextflow.config since it has already been specified in tracedir parameter i.e. tracedir = "${params.outdir}/pipeline_info".

Updated tracedir path

---

nf_core/bump_version.py
tests/test_bump_version.py
tests/test_lint.py

The nextflow scripts access this variable at `workflow.manifest.version`, but the nextflow config has it just at `manifest.version` (so that's what `nextflow config` returns)

Make linting check manifest.version instead of workflow.manifest.version

---

CHANGELOG.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/environment.yml

This should address https://github.com/nf-core/tools/issues/160 by reversing the channel order of bioconda and conda-forge in the `environment.yaml`.

Update channel order for environment yaml

---

CHANGELOG.md
docs/lint_errors.md
nf_core/lint.py
tests/test_lint.py

Check for PyPi and Conda package version availability

---

nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.travis.yml

This adds `pip upgrade` to update the outdated pip version in the TravisCI build automatically to the template.

Add PIP testing

---

.travis.yml
CHANGELOG.md
README.md
nf_core/create.py
nf_core/pipeline-template/cookiecutter.json
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/Dockerfile
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/LICENSE
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/README.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/Singularity
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/nextflow.config
scripts/nf-core

* Click command line flags now prompt for a response if required flags are not supplied when calling `nf-core create`
* Author metadata now collected when creating a pipeline and inserted into template
Still need to finish the checklist:

Added author to create command. Use prompts.

---

CHANGELOG.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/nextflow.config

- [x ] This comment contains a description of changes (with reason)
We can now centrally store and maintain custom configs that are specific to individual Institutions. Config files have been moved to `nf-core/configs` and will be pulled by nextflow before pipeline execution.

Moved custom Institutional configs to nf-core configs on github

---

CHANGELOG.md
nf_core/lint.py
nf_core/list.py
nf_core/utils.py

As described in Slack, there is an error for a site-wide installation of the `nf-core` package due to the `requests` sqlite cache:
```python
Traceback (most recent call last):
File "/usr/local/bin/nf-core", line 217, in <module>
nf_core_cli()
File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
return self.main(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
rv = self.invoke(ctx)
File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, …
```

Requests caching - multi user fix.

---

CHANGELOG.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/main.nf

This puts all files into separate channels that should remove the issues people had when e.g. linking across filesystems (e.g. home of logged in user is on different FS than the workDir).
https://github.com/nf-core/tools/issues/222

Put all input files into channels in template

---

CHANGELOG.md
nf_core/list.py

`nf-core list` now shows `-` instead of `No` if a pipeline isn't pulled locally. Makes more sense and reduces visual clutter.
Before:
```
$ nf-core list
,--./,-.
`._,._,'
Name                       Version    Published     Last Pulled     Default local is latest release?
-------------------------  ---------  ------------  --------------  ----------------------------------
nf-core/ampliseq           1.0.0      5 days ago    -               No
nf-core/eager              2.0.3      6 days ago    -               No
nf-core/rnaseq             1.2        6 days ago    just now        Yes
nf-core/hlatyping          1.1.2      6 days ago    -               No …
```

List: local is latest only if pulled

---

nf_core/launch.py
scripts/nf-core

New subcommand to interactively prompt the user to set workflow flags before launching.
For example:
```
$  nf-core launch methylseq
,--./,-.
`._,._,'
INFO: Launching nf-core/methylseq
INFO: Main nextflow options:
Config profile to use [standard]:
Unique name for this nextflow run [False]: Phil's test run
Work directory for intermediate files [work]:
Resume a previous workflow run [False]: true
Release / revision to use [False]: 1.0
INFO: Pipeline specific parameters:
--mindepth [0]:
--nodedup [false]: true
--reads ['data/*_R{1,2}.fastq.gz']:
--numMismatches [0.6]:
--igenomes_base ['s3://ngi-igenomes/igenomes/']:
--container ['nfcore/methylseq:1.0']: …
```

nf-core launch: new subcommand

---

nf_core/pipeline-template/{{cookiecutter.name_noslash}}/main.nf

Custom config logging in `main.nf` was failing due to
```
ERROR ~ expecting ':', found 'params' @ line 337, column 1.
params.config_profile_contact ? summary['Config Profile Contact'] = params.config_profile_contact
^
```
Added an `if` statement to only report these variables if `params.config_profile_description == true`.
Also, adjusted some of the spacing for easier readability.

Changed logic for reporting custom config logging

---

CHANGELOG.md
docs/lint_errors.md
nf_core/lint.py
tests/lint_examples/minimal_working_example/environment.yml
tests/test_lint.py

The linting tested that pip packages should contain a single equals sign, instead of two (this is a difference between conda and pip syntax). Updated, along with a new mention of this in the lint error docs.

Lint pip version fix

---

CHANGELOG.md
nf_core/launch.py

* Always try to get extra params by calling `nextflow config` (instead of just when `parameters.settings.json` isn't found)
* Also search` main.nf` and config files for `params.something` values
We should probably refactor some of this code to make it more reusable elsewhere. For example, it would be good to use it in the linting to highlight if there are any `params` that are not in `parameters.settings.json`.

Always call nextflow config

---

CHANGELOG.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/docs/usage.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/nextflow.config

Catch the error if we're offline and trying to load remote config files. See nf-core/configs#1 and https://github.com/nf-core/atacseq/pull/22

Handle running offline when we can't fetch nf-core/configs

---

CHANGELOG.md
docs/lint_errors.md
nf_core/download.py
nf_core/lint.py
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.travis.yml
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/conf/base.config
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/nextflow.config
tests/lint_examples/failing_example/nextflow.config
tests/lint_examples/minimal_working_example/nextflow.config
tests/test_lint.py

Update the template and linting to remove `params.container` and just directly define `process.container`. Linting now also checks for and warns if `params.container` is still present.

Don't use params.container, just directly use process.container

---

CHANGELOG.md
bin/blacklist.json

This removes rnaseq https://github.com/nf-core/rnaseq/pull/170 from the blacklist.

Drop Rnaseq from blacklist

---

CHANGELOG.md
nf_core/download.py

@orzechoj spotted that using `nf-core download` without a specific release would not pull the latest release by default. In fact, it just grabs the first in the list, which is probably the oldest.
This PR just sorts the list of releases by release date, so it now gets the most recent release instead 👍

Get the latest release with nf-core download

---

CHANGELOG.md
nf_core/download.py

`nf-core download` uses the Python `zipfile` module to unzip the downloaded pipeline scripts. This package strips all file permissions, so the files are no longer executable.
In this PR, the code just traverses the downloaded files and does a `chmod 775` to make them executable. It's a bit like swatting a fly with a hammer, but it should work..
x-ref https://github.com/nf-core/tools/issues/289

download: Make unzipped files executable. Fixes nf-core/tools#289

---

CHANGELOG.md
README.md
nf_core/lint.py
nf_core/list.py
scripts/nf-core

I found a few bugs and things to tidy up..
1. `nf-core --help` now sorts the commands in a more logical order. 
* User commands are first, developer commands are second
* `bump-version` is no longer the first command you see!
2. I realised that the sorting functionality of `nf-core list` had been broken
* Fixed it, so that `-s` flags work again
* Fixed it so that the default is release again, instead of name
* Added `-s pulled` to sort by the most recently pulled to local
* I added a fair bit more to the readme as the docs were a bit lackign.
3. The new `nf-core launch` command wasn't documented at all. So I added that to the readme.

Fixed list, documented sort, better order of command in --help

---

CHANGELOG.md
nf_core/lint.py

Not sure why this code was there, but for some reason we were going through the conda channel order in reverse.
When packages are only in one channel, this didn't have any negative effect (except for slower lint execution times and more API calls). However, when packages were in multiple channels with different version numbers, it could cause the linting to fail incorrectly (cf. https://github.com/nf-core/atacseq/pull/26)
Just removing the `reverse()` seems to fix this behaviour. Arguably we could extend the linting to check subsequent channels if the correct version isn't found in the first found, but I think it's very unlikely that this will happen so I can't be bothered now.
Phil

Linting - don't reverse conda channel order

---

CHANGELOG.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/main.nf

* Remove duplicate checks: Decided for `s3:` since it is more likely that a local outdir starts with `s3`
* Remove check for `s3:` prefix of `work-dir` since it is removed by nextflow and therefore not found at this state. Nextflow checks for the correct `work-dir` location when executing with awsbatch by itself.
* Nextflow removes the `s3:/` prefix from the workdir now. Removed check to make pipeline executable again on awsbatch. 

awsbatch fix - remove unsatisfiable check

---

CHANGELOG.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/main.nf

In response to #103 
Using the `workflow.stats.ignoredCountFmt`

Add logging of ignored errored processes

---

CHANGELOG.md
bin/sync

The syncing was not very verbose, I changed it, made some refactoring of the code to make it more descriptive (hopefully), and let the script NOT fail, even if errors occured.
The errors will be cought and printed on the travis log though, so we can track issues. But I see no reason to let the travis build fail on a nf-core tools release because of that.

Refactors the syncing script

---

CHANGELOG.md
README.md

Fix typo in tools readme

---

CHANGELOG.md
nf_core/licences.py
nf_core/lint.py
tests/test_lint.py

Since PyYAML 5.1, a warning is thrown when yaml.load() is called without a loader argument.
More info:
https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation

Specify yaml Loader argument

---

CHANGELOG.md
nf_core/lint.py

Working on a fork of a pipeline with an own temp. container reference will raise an error during linting, as the container slug does not contain `nf-core`.
Whilst this is technically correct, we should not let linting raise an error during development, but a warning instead. During `release mode` of nf-core tools, the container definitions must reference a container slug within the nf-core community on Dockerhub, which is the case for a pipeline release.

Prints warning in dev mode for unequal container name

---

CHANGELOG.md
nf_core/lint.py

When testing edge versions the current regex removes the `-edge`  string. This changes copes with this eventuality.
PR against dev

Cope with edge versions when linting

---

CHANGELOG.md
nf_core/create.py
setup.py

This adds the ability to the `create` command to automatically set up the TEMPLATE branch required for syncing pipelines. 
Demo:

Add create to TEMPLATE setup

---

nf_core/pipeline-template/{{cookiecutter.name_noslash}}/nextflow.config

Hello! I had been running into some docker errors and tracked down some magic settings that made them go away. This PR adds those settings to the default nf-core created sample.

Add docker.runOptions to avoid memory swap error

---

nf_core/pipeline-template/{{cookiecutter.name_noslash}}/environment.yml

The base template didn't specify channels for `conda` packages: `multiqc` and `fastqc`. Should be specified.

specified conda channels in template (#333)

---

CHANGELOG.md
Dockerfile

This fixes some nasty behaviour, e.g. being unable to install conda post-link scripts such as `bioconductor-genomeinfodbdata` correctly, which has been addressed upstream in conda 4.6.X releases. I checked our current setup and we had 4.5.X installedd still, so the 4.6X update should also give us a significant speedup! 
https://github.com/conda/conda/issues/8306

Bump version of Conda in base to 4.6.14

---

.github/CONTRIBUTING.md
CHANGELOG.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.github/CONTRIBUTING.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/CODE_OF_CONDUCT.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/docs/usage.md

We just updated the way that people can join slack, using a shared invite link instead of the heroku app. Because this URL is long and may change in the future, we're redirecting from a stable URL https://nf-co.re/join/slack
This PR replaces the old herokuapp URLs with the new nf-co.re URL.

Replace URL for joining slack

---

CHANGELOG.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/environment.yml

Hi,
I was just setting up syncing for guideseq and soon proteomicslfq.
Hence, I followed the instructions and recreated the template. Then, as a sanity check, I wanted to run the example boilerplate code of the template (fastqc and multiqc) and ran into the following:
```
ERROR ~ Error executing process > 'output_documentation (1)'
Caused by:
Process `output_documentation (1)` terminated with an error exit status (127)
Command executed:
markdown_to_html.r output.md results_description.html
Command exit status:
127
Command output:
(empty)
Command error:
/usr/bin/env: 'Rscript': No such file or directory
```
I propose that nfcore create should always output a minimal working example.

[FIX] Missing r-markdown dependency

---

CHANGELOG.md
nf_core/CODE_OF_CONDUCT.md

This adds a code of conduct for the nf-core/tools project to address
#384
Closes #384

chore: Add Code of Conduct for Tools

---

CHANGELOG.md
docs/lint_errors.md
nf_core/lint.py
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.travis.yml
tests/lint_examples/minimal_working_example/.travis.yml

After changing / testing this on `hlatyping`, I figured that we need to change this in linting and the template too:
https://travis-ci.com/apeltzer/hlatyping/jobs/238549269

Add Patch to enable PRs coming from patch branch

---

.travis.yml
CHANGELOG.md
bin/syncutils/utils.py
nf_core/download.py
nf_core/launch.py
nf_core/list.py
nf_core/utils.py
tests/test_list.py

Turns out that nf-core/tools wasn't working on Py3.7 - see https://github.com/nf-core/tools/issues/393
This PR resolves those issues. Namely:
- Don't use `os.errno` as this is gone in Python 3.7 (`import errno` instead)
- `requests_cache` cache is python version specific, so include version number in cache directory
- Remove single usage of `nose`
@sven1103 - the requests cache directory continues to provide entertainment!! 😅 
I also cleaned up a Travis bug where it tried to build and push the API docs, even on forks.
Travis should now test Py 3.7 as well, and _hopefully_ it'll be passing now....

Py3.7 compatibility

---

CHANGELOG.md
nf_core/download.py
tests/lint_examples/minimal_working_example/nextflow.config
tests/test_download.py

Added to the `nf-core download` command so that it also fetches the configs repo.
1. Downloads and extracts a zip file of the configs master
2. Edits the downloaded pipeline `nextflow.config` file so that `https://raw.githubusercontent.com/nf-core/configs/${params.custom_config_version}` is switched with `../configs/`
Doing this means that the pipeline is automatically configured to use the downloaded configs, so institutional profiles continue to work offline.
@sven1103 - I even added some tests!!
Phil

nf-core download: Get nf-core/configs

---

CHANGELOG.md
nf_core/bump_version.py
nf_core/create.py
nf_core/download.py
nf_core/launch.py
nf_core/lint.py
scripts/nf-core
tests/test_download.py

New feature for `nf-core download` - compress the downloaded files into a single archive. Uses `.tar.gz` by default, can also choose `.tar.bz2`, `.zip` or to not compress.
Logging gives command needed to decompress files, as well as a MD5 checksum for the file.

Download tar

---

.travis.yml
CHANGELOG.md

This adds the possibility to test PRs automatically from `patch` branches to `nf-core/tools` itself. Had that already done for the template, but not for `nf-core/tools` yet and @ewels mentioned I should add it ;-)

Add Patch testing to main travis.yml

---

CHANGELOG.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/main.nf

Refactoring all of the header code to use the `Ansi` library like Nextflow does was too much hard work. I figured it was weird that we were only getting the partial code shown for the codes at the start of the strings though, so played around with that. Sure enough - if there is a character before the first code, then the existing code works fine.
So, now, we have some bling _undimmed_  hyphens are the start of the log. I added one at the end of the hyphen line too, to make it symmetrical:
Sparkly! ✨ And seems to fix #329.. ✅

Template: Fix ANSI codes in header

---

CHANGELOG.md
docs/lint_errors.md
nf_core/create.py
nf_core/lint.py
nf_core/pipeline-template/cookiecutter.json
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/Dockerfile
tests/lint_examples/minimal_working_example/Dockerfile

Instead of always using `nfcore/base` as the base image in the `Dockerfile`, use the tag from the current release being used (eg. `nfcore/base:1.7`). If the current version contains the word `dev`, just pull the `dev` tag instead (eg. `nfcore/base:dev`).
Closes nf-core/tools#335

Template Dockerfile: use tagged nfcore/base

---

CHANGELOG.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/conf/igenomes.config

This should fix the issue @drpatelh found!

Fix #418 (iGenomes GRCm38 paths)

---

CHANGELOG.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.travis.yml

The nice new ansi logging is great in interactive terminals, but causes the Travis CI logs to be super super long and difficult to read. In this PR I just add `-ansi-log false` to the travis `nextflow run` commands.

Travis disable ansi

---

CHANGELOG.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.travis.yml

Now that https://github.com/nf-core/methylseq/pull/104 is passing, added support for nf-core@mailinator.com nf-tower monitoring to the template.

Add travis test support for nf-tower

---

nf_core/pipeline-template/{{cookiecutter.name_noslash}}/main.nf

workflow.container is mentioned twice as it is now in the initial summary log. Removed it from the final completion log messages.

avoid duplicate workflow.container log

---

CHANGELOG.md
nf_core/list.py

Fixes crash in `nf-core list` caused by pre-releases with no release date.
Alternative implementation of https://github.com/nf-core/tools/pull/455

nf-core list: ignore pre-releases

---

CHANGELOG.md
docs/lint_errors.md
nf_core/lint.py
tests/lint_examples/failing_example/Singularity
tests/test_lint.py

Resolving https://github.com/nf-core/tools/issues/458

Check for singularity file and raise error if found

---

CHANGELOG.md
docs/lint_errors.md
nf_core/lint.py
tests/lint_examples/minimal_working_example/nextflow.config
tests/test_lint.py

As we're now moving to `snake_case` for all command line variables, the linter should be updated. Previously, a warning was thrown if `--singleEnd` was _not_ there. Now, it throws a warning if `--single_end` is not there and throws failures for `--singleEnd` and `--igenomesIgnore`.

Linting: single_end and igenomes_ignore now must be snake case

---

CHANGELOG.md
README.md
nf_core/launch.py

The `nf-core launch` command finishes by printing a command to the terminal for the user to run. It had a typo, with a double-hyphen for a core nextflow flag (`-params-file`).

Launch: fix double hyphen typo in final command example

---

CHANGELOG.md
nf_core/list.py

`nf-core list` broke when searching for keywords because a new template didn't have a description.
This fix handles the case when the name (??) or description could be false.

List: Handle missing description when searching

---

.travis.yml
CHANGELOG.md
tests/test_lint.py

Currently, CI tests on the linting code fail when the package version is stable.
This is because the minimal working example hardcodes `dev` for the Dockerfile version:
https://github.com/nf-core/tools/blob/615c6a57d0cddefb7f38bac1c4ea83704bfd9214/tests/lint_examples/minimalworkingexample/Dockerfile#L1
The template tags this Dockerfile version based on the active python version number:
https://github.com/nf-core/tools/blob/615c6a57d0cddefb7f38bac1c4ea83704bfd9214/nf_core/pipeline-template/%7B%7Bcookiecutter.name_noslash%7D%7D/Dockerfile#L1
The lint code checks for the same:
https://github.com/nf-core/tools/blob/615c6a57d0cddefb7f38bac1c4ea83704bfd9214/nf_core/lint.py#L920
This fix is a little hacky, but basically just makes the package version number include `dev` if it doesn't, so that …

CI Tests: Force package version to be dev

---

CHANGELOG.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.github/workflows/ci.yml

The CI tests should probably be customised to run with different parameters. Added a `TODO` statement that should be flagged as a warning by the linting code to encourage this.

GitHub Actions: add TODO statement to encourage customisation

---

CHANGELOG.md
nf_core/lint.py

The http://nf-co.re/errors links can be corrupted in some cases by having an adjacent `:` character. Adding a space after the link should resolve this.
Reported by @MaxUlysse

Lint errors: pad with whitespace

---

CHANGELOG.md
docs/lint_errors.md
nf_core/lint.py

Linting: Allow `!>=` as well as `>=` for minimum nextflow version check
Closes https://github.com/nf-core/tools/issues/506

Linting: Allow !>= for minimum nextflow version check

---

.travis.yml
CHANGELOG.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/assets/multiqc_config.yaml
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/main.nf
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/nextflow.config

MultiQC config: If `--multiqc_config` given, supply this to MultQC _in addition_ to the config that is bundled with the pipeline instead of clobbering it.
This hit this when the pipeline failed due to missing output files because we didn't have `export_plot: true` in our custom MultiQC config file.
The config files are loaded in order, so it should be possible to overwrite anything that's in the bundled MultiQC config file still.

Don't clobber MultiQC config file

---

CHANGELOG.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/main.nf

This PR is to address the issue #484 . The updated template will no longer stage the workflow summary YAML file in the root of workDir. It will help avoid potential file conflict when workDir is used by multiple Nextflow runs simultaneously.

Stage workflow summary within MultiQC work dir

---

CHANGELOG.md
docs/lint_errors.md
nf_core/lint.py
tests/lint_examples/failing_example/nextflow.config
tests/test_lint.py

Checks that the pipeline version looks like a development version. That is, that `manifest.version` ends in `dev`.
If running lint with `--release` then checks for the opposite.
Triggers a warning if dev not found when it should be, a failure if it is found when it shouldn't be.

Linting: check for 'dev' in pipeline version

---

.github/workflows/create-lint-wf.yml
.github/workflows/tools-api-docs.yml
CHANGELOG.md

* Don't need to create and test a workflow on all python versions
* Also build tools api docs on both dev and master for now - should mean I can actually get it running before the release
* Can wind back to only master at a later date if we want to. Maybe can leave it like this though.

More GitHub Actions tweaks

---

.gitignore

Don’t ignore the built api docs!

Remove api build dir from gitignore

---

CHANGELOG.md
nf_core/utils.py

We had an error where the config parsing code broke because it couldn't tolerate unexpected output from the `nextflow config` command:
```python
Traceback (most recent call last):
File \"/lupus/ngi/irma3/nf-core-env/bin/nf-core\", line 279, in <module>
nf_core_cli()
File \"/lupus/ngi/irma3/nf-core-env/lib/python2.7/site-packages/click/core.py\", line 764, in __call__
return self.main(*args, **kwargs)
File \"/lupus/ngi/irma3/nf-core-env/lib/python2.7/site-packages/click/core.py\", line 717, in main
rv = self.invoke(ctx)
File \"/lupus/ngi/irma3/nf-core-env/lib/python2.7/site-packages/click/core.py\", line 1137, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File \"/lupus/ngi/irma3/nf-core-env/lib/python2.7/site-packages/click/core.py\", line 956, in invoke
return …
```

Utils: Tolerate extra output from nextflow config

---

CHANGELOG.md
scripts/nf-core

I realised that the header ascii artwork was being printed to `STDOUT`, when log messages etc go to `STDERR`.
Changed so that everything goes to `STDERR`.

Use stderr instead of stdout for header artwork

---

CHANGELOG.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/README.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/docs/usage.md

This PR includes some small template changes on the README and usage documentation files, to emphasise that docker/singularity is preferred over conda for full (and more stable) reproducibility of running pipelines, after the discussion on #help slack channel on 2020-02-20.

Template documentation emphasises container usage

---

CHANGELOG.md
setup.py

Bumping version number for tools from `v1.9dev` to `v1.9`
Only merge after https://github.com/nf-core/tools/pull/543 and https://github.com/nf-core/tools/pull/542

Bump to v1.9

---

.github/workflows/branch.yml
CHANGELOG.md

I was surprised that tests passed on https://github.com/nf-core/tools/pull/547 when I had accidentally made the PR against `master` instead of `dev`.
Looking now I see that we have this test in the pipeline template, but not for the tools repo itself. Added it here.

Add PR branch check to tools repo

---

.github/workflows/branch.yml
CHANGELOG.md
docs/lint_errors.md
nf_core/lint.py
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.github/workflows/branch.yml
tests/lint_examples/minimalworkingexample/.github/workflows/branch.yml

So this ended up being quite a minor PR in the end. I did a bunch of refactoring, felt smug about how much cleaner and easier to read the code was, then realised that it no longer did what it was meant to 😆 After looking at it for a while, I came to the conclusion that what we already had was already optimal..
Couple of things I did change:
* Action now only runs on the main nf-core repo and not forks
* Am I missing something here? I feel like the previous code would have failed for PRs coming to `master` on forks as well..
* Linting code is hopefully now a little more tolerant for variable YAML structures
* Minor tidying and a couple of small tweaks
The `$(git remote get-url origin)` bugs me! There's `$GITHUB_REPOSITORY` which is the base repo as far as I can tell, so why is there not …

Refactor actions branchcheck linting

---

.github/workflows/branch.yml
CHANGELOG.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.github/workflows/branch.yml

If the GitHub Actions test for the PR target branch fails, automatically add a comment to the PR explaining what went wrong and how to fix it.
Closes nf-core/tools#558
Also updated variable handling mentioned in nf-core/tools#554

Comment on PR if branch test fails

---

README.md
docs/lint_errors.md
nf_core/download.py
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/docs/usage.md

Streamlined the various different spellings of Docker Hub to the one they use on their website https://docs.docker.com/docker-hub/.
See also https://github.com/nf-core/nf-co.re/pull/315.

 fix spellings of Docker Hub

---

CHANGELOG.md
docs/lint_errors.md
nf_core/lint.py
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.github/workflows/branch.yml
tests/lint_examples/minimalworkingexample/.github/workflows/branch.yml

Instead of calling `$(git remote get-url origin)`, use `${{github.event.pull_request.head.repo.full_name}}`
Should fix this error: https://github.com/nf-core/chipseq/pull/143/checks?check_run_id=474749336
I think that the above error is because we are not calling the checkout action step before it, so we don't actually have the repo in the working directory. So when we call `$(git remote get-url origin)` it fails. Instead of changing this by checking out the repo, we can just use the `${{github.event.pull_request.head.repo.full_name}}` variable though, from the GitHub API. This should be properly populated and work.
Note that I already made this change in the branch CI for the main tools repo, I just didn't do it in the template. It seems to be working ok there - I tested a variant on my …

Template: branch check, use GH API var

---

README.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/README.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/docs/README.md

Simplify the description of docs in `README.md` and `docs/README.md`.
Closes nf-core/tools#562
See also https://github.com/nf-core/nf-co.re/issues/316

Rewrite documentation index pages / texts

---

CHANGELOG.md
docs/lint_errors.md
nf_core/lint.py
tests/test_lint.py

Adds a new lint test that looks for cookiecutter template placeholders.
Failures produce error messages like this:
```
ERROR: Test Failures:
http://nf-co.re/errors#13 : Found a cookiecutter template string in 'nf-core-philtest/README.md' L1: {{cookiecutter.pipeline_name}}
```
Reports the filename, line number and the cookiecutter variable that was found. One failure is generated per match, so if a file has a bunch then they are all reported in one scan.
Closes https://github.com/nf-core/tools/issues/564

Add new lint test for cookiecutter strings

---

CHANGELOG.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/conf/igenomes.config

I added the missing `mac_gsize` for danRer10. Is that something I need to add to the changelog?

add `mac_gsize` for danRer10

---

CHANGELOG.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/Dockerfile
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/nextflow.config

* Fixes https://github.com/nf-core/tools/issues/541
* Tested by @mashehu on the `atacseq` pipeline https://github.com/nf-core/atacseq/issues/94

Isolate R to look for packages in container only

---

CHANGELOG.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/main.nf

Previously MultiQC reports would only be sent with pipeline completion email if sendmail was used. Here we add the 'mail' version of the attachment.

Add attaching MultiQC report to 'mail' based emails

---

.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.github/ISSUE_TEMPLATE/bug_report.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.github/ISSUE_TEMPLATE/feature_request.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.github/PULL_REQUEST_TEMPLATE.md

When we originally started using templates for PRs and issues, I assumed that people would read the text _(delete whatever is not relevant)_. But a lot of people do not, and many PRs and issues still contain this helping text.
This PR moves this stuff into `` which don't render, so if people do leave them in then they won't show up at least. It also makes all templates a little more consistent.
---

Move some of PR and issue templates into comments

---

.github/markdownlint.yml
CHANGELOG.md

Removed a stray comma from the yaml config file. This looks like a copy+paste error from the example file on the markdownlint-cli repo, which uses JSON for config files.
I'm not sure that it makes any difference, but I figured it shouldn't hurt to fix it.

Remove stray comma from markdownlint config yaml file

---

.github/PULL_REQUEST_TEMPLATE.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.github/PULL_REQUEST_TEMPLATE.md

A bit more simplification of the pull-request templates for both the tools package and the pipeline template.
Basically just removing the stuff that I delete 99% of the time and moving more of the help text into a hidden comment.

Remove and reorder some checklist points from PR templates

---

CHANGELOG.md
README.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/README.md

Template update to add a Slack badge in the pipeline readme.
See nf-core/rnaseq#428 for pipeline implementation:

Slack readme badge

---

CHANGELOG.md
Dockerfile

Bump to latest stable conda 4.8.3 for next tools release to get rid of warning.

Conda Bump for base image

---

CHANGELOG.md
README.md
nf_core/create.py

Adds enormous green log output after running `nf-core create` to encourage users to come and talk on Slack before writing a new pipeline:
See also https://github.com/nf-core/nf-co.re/pull/385

Massive warning when using nf-core create

---

.github/workflows/code-tests.yml

Having all of the Python CI tests running, complete with the CodeCoverage report, is kind of annoying when you're just tweaking a Markdown documentation file or editing some nextflow code in the template.
This PR modifies the Python CI workflow to only run if a `.py` script has been modified.

Only run Python CI tests if Python script edited

---

nf_core/launch.py
nf_core/schema.py
nf_core/utils.py
scripts/nf-core
setup.py
tests/test_launch.py
tests/test_schema.py

New code for using a nice web graphical user interface when running `nf-core launch`. Should work with any nextflow pipeline.
Bunch of other small tweaks and improvements to `nf-core launch` and `nf-core schema` too.
Tests haven't been updated so will probably get a lot of failures. Will fix these next week. In the mean time, any code review and / or testing the tools are very welcome!
Works in tandem with changes to the nf-core website, see https://github.com/nf-core/nf-co.re/pull/400
See Slack `#json-schema` for screen capture demos: https://nfcore.slack.com/archives/CUC8PPDL2/p1593212486143900

nf-core Launch web GUI

---

CHANGELOG.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/main.nf

Realised that without this, the body content is not actually displayed on viewing by a user (and was typically being replaced by the HTML attachment in fancy email browsers).

Add missing content type definition for mailutils email server emails

---

CHANGELOG.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/main.nf

Hi, I added the `workflow.configFiles` information to the summary. In this way it will automatically be added to the email and pipeline_report.
Regarding the nextflow version, it works already for v19.10.0, so it should be fine.
I also changed the summary names from "Config Description" to "Config Profile Description" etc., to distinguish this information about profiles from general config files.

Add information about config files to summary

---

scripts/nf-core

New improved command line help for `nf-core launch`, hopefully a little clearer now. Note that I removed all mention of `JSON`, `schema` and `template` to try to avoid confusion.
New output:
```console
(python3)  ~ » nf-core launch --help
,--./,-.
`._,._,'
nf-core/tools version 1.10.dev0
Usage: nf-core launch [OPTIONS] <pipeline name>
Launch a pipeline using either an interactive web GUI or command line
prompts to set parameter values.
When finished, saves a file with the selected parameters which can be
passed to Nextflow using the -params-file option.
Run using a remote pipeline name (org/repo), a local pipeline directory or
an ID from the nf-core web …
```

Try to improve command line help for nf-core launch

---

Dockerfile

Taken from:
https://docs.docker.com/develop/develop-images/dockerfile_best-practices/
"In addition, when you clean up the apt cache by removing /var/lib/apt/lists it reduces the image size, since the apt cache is not stored in a layer. Since the RUN statement starts with apt-get update, the package cache is always refreshed prior to apt-get install."
This PR brings the dockerfile inline with docker best practices

Add extra clean step to the apt cache in the dockerfile

---

nf_core/launch.py
setup.py

Includes rich to setup.py and uses it to print parameter headers with Markdown in the CLI launch.py
Not sure how to test it, since it is mostly visual and interactive.

[Feature] Use rich for Markdown rendering in launch.py

---

nf_core/launch.py
tests/test_launch.py

* Fixed error with launching from web, where empty strings were removed but then validated (resulted in a `KeyError`)
* Refactored the launch code a bit for when `--id` is supplied
* Removed need to poll the web for the schema results twice
* Just use the supplied schema instead of overwriting it with the one from the pipeline

Launch bugfix

---

nf_core/modules.py

When installing modules, use path `modules/nf-core/software` instead of just `modules/software/`

modules install to nf-core subfolder

---

CHANGELOG.md
nf_core/__main__.py
nf_core/lint.py

Added `rich` support for tracebacks and linting progress bars
I tried to make the progress bar use the function name as it updates, as the current bar does. But I struggled a bit and moved on. If anyone else knows how to do this nicely, then that would be a good improvement 👍

Use rich for linting progress bar and tracebacks

---

nf_core/pipeline-template/{{cookiecutter.name_noslash}}/nextflow_schema.json

I just changed the order of the elements, so that `properties` is the last element of each object, which makes it easier to see all the keys of a group element.

make json-schema template  more human-readable.

---

nf_core/__main__.py
nf_core/lint.py
nf_core/list.py
tests/test_list.py

More epic formatting for `nf-core lint` output using `rich`:
I would love for markdown formatting of the lint error messages in the console, however I can't figure out how to do that within the `rich.panel` element. I quite like those panels, as you get coloured bars at the side - useful when the lint output is very long.
I tried to manually do some markdown formatting (code, italics) using a custom highlighter, but that also doesn't seem to work. I really can't figure that out - see the `# DEBUG` lines of code at the bottom. This makes no sense to me.
Any ideas on how to improve this @Zethson @jpfeuffer?

Amazing lint formatting

---

.github/workflows/create-lint-wf.yml
CHANGELOG.md
codecov.yml
nf_core/__main__.py
nf_core/bump_version.py
nf_core/create.py
nf_core/download.py
nf_core/launch.py
nf_core/licences.py
nf_core/lint.py
nf_core/list.py
nf_core/modules.py
nf_core/schema.py
nf_core/sync.py
nf_core/utils.py
tests/test_licenses.py
tests/test_schema.py

Trying to strip out `click.style` from the codebase and use `rich` instead.
* Use `rich` for logging
* Use a named log handler
* Go through systematically removing `click.style()` everywhere
There's a couple of instances left, that's because they are currently used in a `click.confirm` call (not logs).
This PR needs a lot of care and testing, as I've changed just about every file. So I'm a bit scared that I will have broken lots of stuff 😱

Use Rich logging and terminal styling

---

.github/CONTRIBUTING.md
.github/workflows/pytest.yml
README.md
nf_core/launch.py
nf_core/schema.py
requirements-dev.txt
setup.py
tests/test_launch.py

Remove the pre-release functionality from PyInquirer so that we don't have to wait for v1.0.3. Reverts to stable 1.0.2 version for now. 
Tested with the latest version of `master` code for PyInquirer and this breaks, as they have merged in some fairly major structural changes. So I've pinned `PyInquirer==1.0.2` for now.
This will hopefully be stable enough for a release of tools. Can look into switching to Questionary / another tool at a later date still. I'm not writing that out.
_Sidenote: I tested Questionary and the switch was easy, but it has the same two problems that PyInquirer has, yet without any fixes in the pipeline._

Do not use pre-release PyInquirer

---

nf_core/pipeline-template/{{cookiecutter.name_noslash}}/nextflow_schema.json

First try at #687 
Not sure if we really need to ditch `type:object`for groups as done in the example, because they still contain properties. This would also mean less changes in the other code (which often identifies a group by `type==object`). But maybe I misunderstood the changes for the new structure. 🤷‍♂️

update json-schema template to new structure

---

nf_core/__main__.py
nf_core/bump_version.py
nf_core/create.py
nf_core/launch.py
nf_core/lint.py
nf_core/schema.py
nf_core/sync.py
setup.py

Use new argument for the Rich logging handler. Removed all of the `extra={"markup":True}` statements in various logging calls.
See https://github.com/willmcgugan/rich/issues/171 - thanks for the super-fast feature addition @willmcgugan!

Use new Rich syntax for markup logs.

---

.gitignore
CHANGELOG.md
nf_core/lint.py

Use `fnmatch` to properly apply glob expressions found in the `.gitignore` file when searching all pipeline files for `TODO` strings.
Closes https://github.com/nf-core/tools/issues/477

Lint TODO - ignore editor files

---

.gitignore
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.github/workflows/ci.yml
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.github/workflows/push_dockerhub.yml
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.gitignore

Move the new DockerHub GitHub action out into its own file.
Means that it now runs even if tests are failing. However, PRs shouldn't be merged / pipelines shouldn't be released with failing tests, so can't see that it will be a problem. In fact, release tests are failing at the moment because of broken CI, so it's probably actually a good thing.
Main reason for moving was that it was showing up as being skipped on every PR, causing some confusion (https://github.com/nf-core/chipseq/pull/171#issuecomment-664989452). If in its own file like this then it doesn't show at all unless it's running.
Also fixed a broken `.gitignore` pattern that I added recently, which was matching _all_ files 🤦🏻

Dockerhub ci actions

---

nf_core/__main__.py
nf_core/lint.py
nf_core/schema.py
tests/test_lint.py
tests/test_schema.py

Schema linting - split out the title + description checks:
* Don't call as part of the main schema validation function
* This means that `nf-core launch` and other tools that require a valid schema to work still launch even if you have a typo in your schema description
* `nf-core schema validate` throws log warnings to the command line about this check
* `nf-core lint` throws lint warnings about this check

Schema lint - warn about invalid title + description

---

CHANGELOG.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.github/.dockstore.yml

Added a `.github/.dockstore.yml` config file for automatic registration with [dockstore.org](https://dockstore.org/)
Many thanks to @agduncan94 for working on this and suggesting this route for us.
Please wait to merge until we have confirmation that having the config file inside the `.github` directory will be supported by Dockstore.

Add Dockstore config file to template

---

nf_core/schema.py

Reverting the whitespace padding for the launch prompt, as it looks weird when you have lots of prompts about adding and removing params:
And to be honest, I'm not sure that I love it even when it's just `INFO` statements.. 🤔 For me it is a prompt and not a log statement, so I find it a bit jarring if it has the same indentation as a log message. But I am _very_ used to looking at these logs which most people aren't.

Revert extra whitespace for schema web builder prompt

---

.github/workflows/create-lint-wf.yml
.github/workflows/sync.yml
CHANGELOG.md
nf_core/__main__.py
nf_core/lint.py
nf_core/sync.py
setup.py

Patch release to fix the automatic template synchronisation, which failed in the v1.10 release.
* Improved logging: `nf-core --log-file log.txt` now saves a verbose log to disk.
* nf-core/tools GitHub Actions pipeline sync now uploads verbose log as an artifact.
* Sync - fixed several minor bugs, made logging less verbose.
* Python Rich library updated to `>=4.2.1`
* Hopefully fix git config for pipeline sync so that commit comes from @nf-core-bot
* Fix sync auto-PR text indentation so that it doesn't all show as code
* Added explicit flag `--show-passed` for `nf-core lint` instead of taking logging verbosity

v1.10.1 patch release

---

CHANGELOG.md
docs/lint_errors.md
nf_core/lint.py
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.github/workflows/awsfulltest.yml
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.github/workflows/linting.yml
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.github/workflows/push_dockerhub.yml
nf_core/sync.py
setup.py
tests/lint_examples/minimalworkingexample/.github/workflows/linting.yml

PR to `dev` for 1.10.2 patch release. See milestone: https://github.com/nf-core/tools/milestone/9
Extra stuff from https://github.com/nf-core/chipseq/pull/177 template merge
Stretch goal:

1.10.2 patch

---

nf_core/pipeline-template/{{cookiecutter.name_noslash}}/README.md

I am not sure, but it seems like the template readme does not really fit the auto-generation of the usage docs anymore.
Also, the link to the general docs was broken ("." missing).

[FIX] Doc links in Readme template

---

nf_core/pipeline-template/{{cookiecutter.name_noslash}}/docs/usage.md

Noted  when doing sync for eager.
`-c` is now sitting above description when you should use it.
As so minor, CHANGELOG not necessary

Fix typo of where -c param is described

---

CHANGELOG.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.github/CONTRIBUTING.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/README.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/docs/README.md

- As shortly discussed on slack, removing the TODO mentioning the option of additional doc files besides `usage.md` and `output.md`.
- Fix now dead `/docs` links

remove outdated TODO in template

---

CHANGELOG.md
nf_core/__main__.py
nf_core/lint.py
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/nextflow_schema.json
nf_core/schema.py
nf_core/sync.py
pyproject.toml
setup.py
tests/test_lint.py

Minor bump to Rich, as a change to how it does escaping meant that all of the square brackets in the logs were showing up as double square brackets.

Update rich to >=9 and update [] escaping

---

nf_core/__main__.py
nf_core/lint.py

Quick fix for stuff I broke in https://github.com/nf-core/tools/pull/748
I had checked the pytest results but hadn’t tried running the linting in the console again after adding some of that. Turns out that it broke a bunch of rendering.
I think this PR treads the line where pytest no longer throws warnings, but the output still looks as intended.

Hotfix for broken PR

---

CHANGELOG.md
docs/lint_errors.md
nf_core/lint.py
tests/test_lint.py

* Warn if `Dockerfile` doesn't exist, instead of failure
* Fail if the old markdown to HTML R script is found
* Update documentation to describe missing files in this lint test
Closes nf-core/tools#367

Lint updates - Dockerfile give a warn, fail for old R script

---

nf_core/pipeline-template/{{cookiecutter.name_noslash}}/README.md

The link to the folder docs in the Documentation section is not working:
https://nf-co.re/rnaseq/dev#documentation
-> https://nf-co.re/rnaseq/dev/docs
I propose to actually remove the mention of this folder, and link directly the md files which should simplify the whole section.
Only issue, I would want to link `docs/usage.md` and `docs/output.md` which are not accessible in the current website from this README.
Any idea on how to improve all that?

remove docs from README Template and simplify Documentation section

---

nf_core/pipeline-template/{{cookiecutter.name_noslash}}/docs/output.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/docs/usage.md

Notice added to the top of the markdown files that shows when viewing on GitHub but is not rendered on the nf-core website (as long as you have the `## Introduction` header below it).
Example: https://github.com/ewels/nf-core-methylseq/blob/usage-md-notice/docs/usage.md
Fixes nf-core/tools#727

Added notice to top of docs markdown files to use the website.

---

.github/workflows/sync.yml
CHANGELOG.md

I'm not really sure how to test this and see how it works? But hopefully means that we can manually kick off the template sync GitHub action if ever we need to.

GitHub Actions sync - add manual 'workflow' trigger

---

nf_core/__main__.py
nf_core/launch.py
nf_core/lint.py
nf_core/utils.py
tests/test_utils.py

Should hopefully make GitHub Actions logs show coloured output. Especially useful for `nf-core lint` results.

Logging - force colours if certain env vars are set.

---

README.md
nf_core/lint.py

The GitHub Actions "terminal" window is pretty narrow. At least the Rich output for it is. This PR just makes a couple of common lint messages shorter so that they can be read without being truncated.
Currently I get a lot of this, which is not super helpful:
```
│ https://nf-co.re/errors#8: Conda package is not latest available: conda-for… │
│ https://nf-co.re/errors#8: Conda package is not latest available: conda-for… │
│ https://nf-co.re/errors#8: Conda package is not latest available: conda-for… │
│ https://nf-co.re/errors#8: Conda package is not latest available: bioconda:… │
```

Make some lint messages shorter

---

CHANGELOG.md
nf_core/lint.py

Currently, linting _always_ fails if you are using the development version of nf-core/tools, as it wants every pipeline to have the Dockerfile start with `FROM nfcore/base:dev`. In practice, what we actually want is the latest stable version.
This PR only checks for that string if we're running a stable version. That way, tests still pass locally with the dev version of tools but will fail when running on CI with a stable version.

Don't lint for dockerfile base image if running nf-core/tools dev version

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.md
CHANGELOG.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.github/ISSUE_TEMPLATE/config.yml

The GitHub issue templates had stopped working. This PR adds in the now-required YAML frontmatter to the templates, along with a new config that adds in external links to Slack.
See https://github.com/nf-core/nf-co.re/pull/556 for working proof of concept.
The main tools package didn't have any templates at all, so I added these.

Get GitHub issue templates working again

---

.github/workflows/branch.yml
CHANGELOG.md
nf_core/lint.py
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.github/workflows/branch.yml
tests/lint_examples/minimalworkingexample/.github/workflows/branch.yml

Use pull_request_target event for branch protection CI

---

.github/workflows/branch.yml
nf_core/lint.py
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.github/workflows/branch.yml
tests/lint_examples/minimalworkingexample/.github/workflows/branch.yml

In https://github.com/nf-core/tools/pull/766 we started using the `pull_request_target` workflow event, which is awesome. It allows us to have automated comments on PRs even when coming from forked repos.
After testing on the new nf-core/testpipeline we found that (a) it works well but (b) the actions _payload_ name is unchanged. So to get the variables in the comment we need to revert `github.event.pull_request_target` back to `github.event.pull_request`
Tested and working on `master` in https://github.com/nf-core/testpipeline/pull/6#issuecomment-724876835

Fix new Branch CI GitHub Actions

---

CHANGELOG.md
nf_core/lint.py
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.github/workflows/linting.yml
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.github/workflows/linting_comment.yml
tests/test_lint.py

Post comment about linting results to a PR, even when that PR comes from a fork. See https://github.com/nf-core/tools/issues/765
This is complex, as the GitHub Actions event that posts the comment cannot come from the PR base - the forked repo. So here we introduce a new workflow specifically for the comment that is triggered when the lint action is complete.
Tested here: https://github.com/ewels/nf-core-testpipeline/pull/2

New GitHub Actions workflow to add lint results to a PR as a comment

---

CHANGELOG.md
docs/lint_errors.md
nf_core/lint.py
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.github/workflows/awsfulltest.yml
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.github/workflows/push_dockerhub_dev.yml
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.github/workflows/push_dockerhub_release.yml
tests/lint_examples/minimalworkingexample/.github/workflows/awsfulltest.yml

Trying to fix the GitHub Actions full-scale AWS tests. Problem was that the trigger went immediately after release, before the Docker Hub images were ready.
This PR splits the docker hub builds into two (one for `dev`, one for releases). The AWS full test workflow is then triggered by the release workflow.
The key point is that I removed the branch filtering from the workflow trigger on the full tests. I think that the release event does not have branch information.

Split docker push GHA workflows, update trigger for AWS full test

---

nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.github/workflows/awsfulltest.yml
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.github/workflows/awstest.yml
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.github/workflows/ci.yml

PR to fix #739 
Changed the actions in awstest.yml and awsmegatest.yml to
`conda-incubator/setup-miniconda@v2`
and switched version of `get-diff-action@v1` to `get-diff-action@v4` in ci.yml.
Also changed the PREFIX_FILTER to FILES command in ci.yml, because the former is deprecated.
These changes fix the problems of deprecated `set-env` commands in GitHub actions.
- [x ] This comment contains a description of changes (with reason)

Updated github actions

---

nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.github/workflows/ci.yml

In https://github.com/nf-core/tools/pull/774 @KevinMenden updated the `technote-space/get-diff-action` so that GitHub Actions runs with the new security settings rolled out by GitHub.
This fixed the GitHub Actions and got things running again. However, I noticed in https://github.com/nf-core/methylseq/pull/177 that when I copied over the changes, the Docker image was building even though I hadn't touched any of the listed files.
I had a look over the [docs for the action](https://github.com/marketplace/actions/get-diff-action#examples-of-env) and I think that we need to switch `env.GIT_DIFF` to `env.MATCHED_FILES`. This then returns true if any of the files listed under `FILES` have been changed. `env.GIT_DIFF` now basically always returns true, so currently the Docker image always …

CI Docker diffs - use env.MATCHED_FILES

---

.github/workflows/create-lint-wf.yml
.github/workflows/pytest.yml
.github/workflows/sync.yml
CHANGELOG.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.github/workflows/ci.yml
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.github/workflows/linting.yml
tests/lint_examples/minimalworkingexample/.github/workflows/ci.yml
tests/lint_examples/minimalworkingexample/.github/workflows/linting.yml

Reduce the GitHub Actions CI logs for the Nextflow installation from 5,186 lines to 10.
See https://github.com/nextflow-io/nextflow/issues/1800

Quietly install Nextflow in CI

---

CHANGELOG.md
docs/lint_errors.md
nf_core/lint.py
tests/lint_examples/minimalworkingexample/.github/workflows/ci.yml
tests/lint_examples/minimalworkingexample/README.md
tests/test_bump_version.py
tests/test_lint.py

Add in lint test for old `push_dockerhub.yml` file to make sure that it is removed after the pipeline sync.
See https://github.com/nf-core/tools/pull/770 for refactoring.

Lint fail push_dockerhub.yml

---

docs/api/_src/bump_version.rst
docs/api/_src/create.rst
docs/api/_src/download.rst
docs/api/_src/index.rst
docs/api/_src/launch.rst
docs/api/_src/licences.rst
docs/api/_src/lint.rst
docs/api/_src/list.rst
docs/api/_src/modules.rst
docs/api/_src/schema.rst
docs/api/_src/sync.rst
docs/api/_src/utils.rst

Sorry for all the PRs - docs looking a lot better now! Messed up the toc on the homepage though so all links vanished. Also the `:special-members:` directive was overkill as we get all the `__dict__` inherit functions etc which we don't care about: https://nf-co.re/tools-docs/modules.html
Many more functions now showing up though, so docs are looking a lot fuller now ✅

Sphinx homepage

---

CHANGELOG.md
nf_core/list.py
nf_core/utils.py

Look for and use `$NXF_HOME` for stuff if set, before defaulting to `~/.nextflow`
Closes nf-core/tools#798

Use NXF_HOME env var for nextflow home directory, if set

---

setup.py

I just switched computers and for some reason, `pip` was quite happy to install the dev code here without updating prompt-toolkit. To make it work I had to uninstall pyinquirer and then manually update prompt-toolkit.
As we can assume that most people will have the old version of nf-core/tools installed, and so the same pyinquirer / prompt-toolkit versions that I did, I'm a bit worried that this will happen to other people.
To try to help avoid that, I've added a minimum version of prompt-toolkit to our `setup.py`. This should already be set in questionary, but it uses poetry instead of setuptools so that could be one reason why stuff is being strange. Hopefully this addition may avoid some issues with `pip` installation.
Phil

Add minimum version for prompt_toolkit

---

CHANGELOG.md
nf_core/lint.py

Fixes nf-core/tools#796
Also switched the log message from error to critical when halting linting due to failed tests.

Catch FileNotFoundError when looking for TODO comments

---

CHANGELOG.md
setup.py

Bump to development version number on `dev` again after the 1.12.1 release.

Bump version to 1.13dev

---

.github/workflows/tools-api-docs.yml

The built docs are ignored by gitignore now, so need to ignore the gitignore so that the built docs are not ignored.

Ignore the gitignore for sphinx docs

---

CHANGELOG.md
nf_core/launch.py
tests/test_launch.py

Refined UI around the Questionary prompts:
* Fixed bug where you couldn't delete something you'd entered
* Empty answers were ignored, so if you typed something then went back and deleted it then the interface would revert to whatever you typed last - you couldn't reset it to nothing. Now fixed.
* Group select lists
* Removed duplicated group heading
* Stronger highlighting of group title
* Default values of options formatted with dim text
* Inputted values of options formatted with yellow text
* Required options shown with hint if not yet set
* Errors shown at top of list (as disabled options) if _Continue_ selected with required options not set
* Single parameters
* Removed duplicated parameter title
* Stronger highlighting of parameter title
Screenshots of cli interface before and …

Better UI for command line launch

---

CHANGELOG.md
nf_core/lint/schema_lint.py
nf_core/schema.py

Simply added a jsonschema validation check to the `schema_lint.py` function check.
So the steps are now to:
* load the schema
* get schema defaults
* check for correct format as before
* then validate the default params against the schema itself
The `AssertionError` was exchanged with an `Exception` because we capture two different errors now.
Will probably make this more finegrained.

added validation check for default params to nf-core lint

---

CHANGELOG.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.github/workflows/linting.yml

Back in https://github.com/nf-core/tools/pull/769 I added functionality to get the output of `nf-core lint` as a markdown file and automatically post it on a PR, even if the PR comes from a fork of the repo (see https://github.com/nf-core/tools/issues/765 for discussion). This went out in release v1.12, however I realised that I haven't really seen any of these popping up.
Looking specifically at `nf-core/ampliseq`, I realised that the step to find the PR number couldn't find the file:
```
Run echo "::set-output name=pr_number::$(cat linting-logs/PR_number.txt)"
cat: linting-logs/PR_number.txt: No such file or directory
```
The step above showed the files being fetched from the artefact, so the file was there:
```
Run dawidd6/action-download-artifact@v2
==> Repo: nf-core/ampliseq
==> …
```

Fix GitHub Actions typo that broke PR lint comments

---

CHANGELOG.md
nf_core/bump_version.py
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.github/ISSUE_TEMPLATE/bug_report.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/README.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/conf/charliecloud.config
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/docs/usage.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/nextflow.config
tests/test_bump_version.py

Closes https://github.com/nf-core/tools/issues/824

add Shifter + Charliecloud profiles

---

CHANGELOG.md
README.md
nf_core/__main__.py
nf_core/download.py
nf_core/utils.py
tests/test_download.py

With DSL2, we have multiple containers and they are specified within module files. These are no longer found by `nextflow config` and therefore `nf-core download` doesn't see them (#818).
This PR adds several new bits of functionality to `nf-core download` for singularity containers:
The tool now scrapes any `.nf` files in `modules/` recursively, and parses them to look for a lines that look like this:
```nextflow
container = "xxx"
```
If multiple matches are found in a file, any that start with `http` are prioritised and the first match after that is used.
> NB: Scraping code only handles simple strings and will fail with anything more complicated (e.g. [Sarek](https://github.com/nf-core/sarek/blob/bce378e09de25bb26c388b917f93f84806d3ba27/conf/base.config#L71)). This kind of thing needs …

Download: Get DSL2 singularity containers

---

nf_core/lint/files_exist.py

Mini PR to add a check for an additional file that should no longer be present.
This config has been moved to nf-core/configs and is no longer referenced in `nextflow.config`, but the template sync doesn't seem to pick up that the config file should be deleted.

Linting: Check that aws.config is deleted

---

CHANGELOG.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/docs/usage.md

This fixes a mistake in the template usage documentation how profiles are loaded.
It also adds a line describing where to find the exact names of processes you may wish to customise resources for,
Both at suggestion of an eager user who is trying to create a profile.

Template profile docs fix

---

nf_core/lint/files_exist.py
nf_core/lint/files_unchanged.py

Check for new files added in the now-merged #852 - fail if not present.

Lint validation

---

nf_core/pipeline-template/{{cookiecutter.name_noslash}}/nextflow_schema.json

* Remove `--name` from the schema since we removed this core nextflow option from `nextflow.config` in #852 (throws a linting warning instead of fail, so wasn't caught by the CI)
* Added `pattern` regexes for validation of `--max_memory` and `--max_time`
* Patterns are fairly strict - must now be in the format `123.GB` or `456.h`
* Used the prefixes listed on the nextflow docs, neither now allowed without any prefix (e.g.`789`)
* `--max_cpus` is already set as an `int` so fully validated already

Schema validate max resources

---

Dockerfile
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/Dockerfile

I don't think that these commands need to go out into all pipelines. Simpler and less error prone if they are instead added to the base image that all other DSL1 containers are built from.

Move commands into base image instead of Dockerfile in template

---

CODE_OF_CONDUCT.md

Replace Slack link in enforcement section to core@ email alias

---

.github/workflows/branch.yml
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.github/workflows/branch.yml

Test was working, but printing the wrong repo name in the comment which was kind of confusing. See https://github.com/nf-core/tools/pull/859#issuecomment-780681860
I also added an extra sentence explaining that the test will not switch to ✅ after the branch is updated, until new commits are pushed.

Branch CI test - fix repo name in comment

---

nf_core/pipeline-template/{{cookiecutter.name_noslash}}/docs/output.md

Remove warning from `output.md` in the template as discussed here:
https://github.com/nf-core/tools/issues/810

remove warning from output.md file

---

CHANGELOG.md
nf_core/__main__.py
nf_core/modules.py
tests/test_modules.py

This PR adds the command
`nf-core modules md5`
which automatically generates a yaml file containing the md5sums and paths of all files in the `output` directory.
So for writing module tests, you would run your test inside the module directory, which should generate the `output` directory. Then, you can run `nf-code modules md5 <path_to_modules_dir>`
Which generates output such as:
```yaml
- name: <name of test>
command: <command here>
tags:
- <tag>
files:
- path: modules/output/star/star/chrStart.txt
md5sum: faf5c55020c99eceeef3e34188ac0d2f
- path: modules/output/star/star/chrNameLength.txt
md5sum: c7ceb0a8827b2ea91c386933bee48742
- path: modules/output/star/star/chrLength.txt
md5sum: f2bea3725fe1c01420c57fb73bdeb31a
- path: modules/output/star/star/sjdbList.fromGTF.out.tab
md5sum: …
```

Add module test-yml generation tool

---

CHANGELOG.md
docs/api/_src/lint_tests/merge_markers.rst
nf_core/lint/__init__.py
nf_core/lint/merge_markers.py
tests/lint/merge_markers.py
tests/test_lint.py

Adds a lint test looking for merge markers.
Closes https://github.com/nf-core/tools/issues/321

Add lint test for merge markers

---

nf_core/pipeline-template/{{cookiecutter.name_noslash}}/lib/NfcoreSchema.groovy
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/main.nf
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/nextflow.config

Follow-on to https://github.com/nf-core/tools/pull/857
Tried to add `params.input_paths = null` to `nextflow.config` to avoid the warning that Nextflow threw about undefined params and hit a bug in the new unexpected params code:
```
JSONObject["input_paths"] not found.
-- Check script 'nf-core-test/main.nf' at line: 28 or see '.nextflow.log' file for more details
```
After a bit of digging I figured out that it was because this code was removing anything evaluating to `false` from the parameters map:
https://github.com/nf-core/tools/blob/729f03ae5bd13ce588e367d333d594fb2185f482/nf_core/pipeline-template/%7B%7Bcookiecutter.name_noslash%7D%7D/lib/NfcoreSchema.groovy#L197-L200
So just switching to use `params` instead of `cleanedParams` when printing the value of the unexpected parameter …

Fix bug in unexpected param log with false values.

---

nf_core/pipeline-template/{{cookiecutter.name_noslash}}/lib/NfcoreSchema.groovy
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/main.nf
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/nextflow.config
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/nextflow_schema.json

* Improved the colours map to include all colour variants and styles
* Removed broken ascii colour codes in help output (it was missing a reset code)
* Added nicer colouring to the help output
* Removed duplicate dashed line at the end of the help block
* Replaced `baseDir` with `projectDir` for schema path
Before:
After:

Make --help output look nicer

---

nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.github/.dockstore.yml

Add new parameter to Dockstore config YAML file that tells Dockstore to automatically publish newly discovered workflows. This means that we don't need to go in to Dockstore and manually publish any new workflows, as soon as the new repo is added to nf-core it should show up publicly on Dockstore 🥳 
See dockstore/dockstore#3876 for details.

Dockstore pipeline config - add publish:True

---

nf_core/modules/pipeline_modules.py
nf_core/sync.py
nf_core/utils.py

If you use the GitHub `gh` command line tools (https://cli.github.com) then you will have a local config file set up at `~/.config/gh/hosts.yml` with your oauth token. You can see this with the command `gh auth status`.
This PR checks if that file exists and tries to parse your username and token. If successful, it passes these as authentication in the GitHub API calls used by `nf-core modules install` to increase the rate-limit cap on the API.

Use gh cli auth details for GH API if we can

---

.github/workflows/create-lint-wf.yml
nf_core/__main__.py
nf_core/modules/create.py
nf_core/modules/pipeline_modules.py
nf_core/modules/test_yml_builder.py
nf_core/utils.py

All `nf-core modules` commands now take the module name as an option instead of argument (`--tool` instead of positional) and are able to run if it is not given. If not supplied, all tools use the cool fuzzy-finder interface thing to collect module name.

Make all modules commands use --tool and fuzzy module name input

---

.github/workflows/create-lint-wf.yml
nf_core/__main__.py
nf_core/lint/__init__.py

New feature for main pipeline linting - flag `--fail-on-ignore`.
Not useful for much except the CI tests for tools itself. No tests should be ignored on a vanilla template so this lets us check that there isn't any funky stuff going on.

Lint fail on ignore

---

nf_core/pipeline-template/conf/test.config
nf_core/pipeline-template/conf/test_full.config

Fix the test CI workflow by ignoring `--input` from the schema, which is not used in this config.

Ignore --input schema in test.config

---

nf_core/lint/__init__.py

I noticed during my bytesize live-demo that the markdown comment had a typo, saying `warnings` when it should have said `ignored` in the little diff block.

Fix ignored typo in lint markdown comment

---

nf_core/pipeline-template/lib/NfcoreSchema.groovy
nf_core/pipeline-template/nextflow_schema.json

Fix test ci ignore input

---

nf_core/modules/create.py

Stops this from working:
```bash
nf-core modules create . -t tool
nf-core modules create . -t tool/subtool
```
```console
CRITICAL Module './software/test/main.nf' exists already, cannot make subtool 'test_test'
```
Also the reverse:
```bash
nf-core modules create . -t tool/subtool
nf-core modules create . -t tool --force
```
```console
CRITICAL Module subtool './software/test/test/main.nf' exists already, cannot make tool 'test'
```

Module create - don't make tool/subtool if tool/main.nf exists.

---

nf_core/module-template/tests/test.yml
nf_core/modules/create.py

When no `subtool` was provided to `modules create`, the  created `test.yml` was rendering the `tag` content: 
`- name: tool_name None`
Changed to render:
`- name: tool_name`

Do not show None on test.yml name when subtool is missing

---

nf_core/module-template/tests/test.yml

When no subtool present, there appear two equal tags on the `test.yml`:
```yaml
tags:
- tool
- tool
```
Put a conditional in the template to avoid this behavior.

Only one tag on test.yml when no subtool set

---

CHANGELOG.md
nf_core/lint/__init__.py
nf_core/pipeline-template/.github/workflows/branch.yml
setup.py

Fixes bug in linting markdown output: https://github.com/nf-core/tools/issues/914
Also tweaks the markdown comment added for the PR branch test checking for PRs to `master`,  now with a _TLDR_ section at the top to make it more attention grabbing:
https://github.com/nf-core/ampliseq/pull/228#issuecomment-801977264

Fix lint md

---

nf_core/modules/lint.py

This fixes the following issues:

Patch fix triage #1

---

nf_core/modules/lint.py

This fixes the problems with wrapping and order of the output table. Also fixes any missing file paths in the table (they got wrapped earlier).
Checks whether all module dir's in `modules/software` are actually directories and raises an exception if not (to catch cases like `modules/software`.
Although to be honest we have to assume some kind of structure of the repo and there are lots of other places where files that shouldn't belong would break the code.

Path fix triage 2

---

nf_core/modules/lint.py
tests/test_modules.py

Fixes the bug that happens when all modules of a nf-core pipeline are up to date.
closes #928

fix bug for updated messages

---

nf_core/lint/nextflow_config.py
nf_core/pipeline-template/lib/NfcoreSchema.groovy

If we use `.keySet().contains()`  instead of `.containsKey()`, the problems at https://github.com/nf-core/diaproteomics/pull/103/checks?check_run_id=2167429157 are fixed.

remove containsKey() from validateParams()

---

.github/workflows/create-lint-wf.yml
.github/workflows/markdown-lint.yml
.github/workflows/python-lint.yml
CHANGELOG.md
setup.py

* Split up CI commands into separate steps for `create-lint-wf` to make it easier to read
* Added automated PR comments for markdown + Python code linting CI

Split steps create lint wf

---

CHANGELOG.md
nf_core/modules/create.py

Add a better logging message if a directory  has not specified correctly.
closes https://github.com/nf-core/tools/issues/940

better logging if directory not correctly specified

---

nf_core/create.py

This PR tries to address the bugs in https://github.com/nf-core/tools/issues/931
closes https://github.com/nf-core/tools/issues/931
(once ready)

Fixing bugs in nf-core create

---

CHANGELOG.md
nf_core/create.py
nf_core/modules/create.py

Get the file mode from the template file and apply it to the new file in `nf-core create`
Fixes nf-core/tools#932

Pipeline create - apply file permissions to new files

---

.github/workflows/markdown-lint.yml
CHANGELOG.md
nf_core/pipeline-template/.github/workflows/linting.yml

Added linting CI test PR comments for all code language linting in the pipeline template. Tweaked the markdown comment slightly for tools too.

Add code lint CI PR comments to pipeline template

---

CHANGELOG.md
setup.py

Bump to v1.13.2

---

.github/workflows/sync.yml
CHANGELOG.md
setup.py

* Bump to v1.14dev
* Move `NXF_VER` up to the workflow scope for the sync job so that we use the latest edge release of Nextflow in the sync

Bump to v1.14dev, move NXF_VER up in scope in sync wf

---

CHANGELOG.md
nf_core/lint/__init__.py
nf_core/lint/version_consistency.py

Bug in the linting when in release mode, missing an import after the code restructure.
Also added an extra line break in the linting markdown outputs, as the header doesn't render on GitHub properly without it.

Fix bug in lint with release mode

---

nf_core/modules/create.py
nf_core/modules/test_yml_builder.py

tweak TODO string in test_yml_builder.py

---

.github/workflows/create-lint-wf.yml
nf_core/__main__.py

* Run an extra job in the CI to do linting with `--release` to try to pick up any other nasty hidden errors like the one that sneaked into the recent releases.
* Tweak the traceback setup so that they are not so long and people can paste them into Slack 😉

Extra lint test with --release

---

CHANGELOG.md
nf_core/pipeline-template/nextflow.config

In https://github.com/nf-core/tools/pull/866, we increased the strictness for container profiles by explicitly disabling other container engines if a profile is selected.
Right now nothing is broken per se, but for the `conda` and `podman` profiles, we currently do not disable `charliecloud` properly. This fixes it.

fix conda and podman profile strictness

---

CHANGELOG.md
nf_core/pipeline-template/nextflow.config
nf_core/pipeline-template/nextflow_schema.json

Turns out that Nextflow has been tolerating broken AWS s3 paths for us for years. Let's fix it before anyone notices 🤫 
Discussion on Slack in `#aws` channel: https://nfcore.slack.com/archives/CE7FBAMRP/p1616747167005700

Remove trailing slash from `params.igenomes_base`

---

CHANGELOG.md
nf_core/launch.py
nf_core/schema.py

* If a param doesn't have a default in the schema and the input is False / None / , strip it
* Sanitise the default values in the schema so that they are the correct type
* Don't surround command-line params with quotes if numeric
Fixes nf-core/tools#976

Launch: Strip unset params with no defaults.

---

CHANGELOG.md
nf_core/sync.py

* Fixes main bug that the default value for the Retry-After header was an int and not a str
* Make the default wait random, between 10 - 60 seconds
* Some tweaks, print the headers in more log messages, make them prettier.
Fixes nf-core/tools#970

Sync: Try to fix the GitHub abuse mechanism coping code

---

CHANGELOG.md
nf_core/__main__.py
nf_core/modules/create.py
tests/test_modules.py

This PR adds a `--conda-name`, `-c` flag to `nf-core modules create` to allow sidestepping of questionary, e.g. during pytest. 
Fixes https://github.com/nf-core/tools/issues/988

Conda name flag

---

nf_core/pipeline-template/.github/PULL_REQUEST_TEMPLATE.md
nf_core/utils.py

Couple of minor fixes for things that I spotted whilst doing stuff this evening.
* Fix list indentation for correct GitHub rendering. GitHub needs 4 spaces, markdownlint likes 2. I have added a mdl comment to avoid the mdl linting from triggering a CI error.
* Schema build - add exception type to handle. This is one I ran into and I don't know why. I couldn't replicate it but figured that I could catch it properly next time.

Minor tweaks

---

nf_core/__main__.py

Currently the `nf-core module lint` command exits with code `0` even if there are failures, meaning that the CI always passes. This PR addresses that, mimics how `nf-core lint` works.

Modules lint - exit code 1 if we have failures

---

CHANGELOG.md
nf_core/module-template/tests/test.yml
nf_core/modules/create.py
nf_core/modules/lint.py
nf_core/modules/test_yml_builder.py

This updates the module commands `create` and `create-test-yml` with the new module format for the `test.yml` 
Instead of `tool_subtool` the tag will now be `tool/subtool`  (see here: https://github.com/nf-core/modules/pull/389) 
Still need to update the lint command to look for the correct tags if we decided to go only for these tags instead of having things like "my_tool_single_end" etc.

update module commands with new format

---

nf_core/module-template/tests/test.yml

Tiny fix of the module template (unconditional use of "subtool" in the template)
Closes https://github.com/nf-core/tools/issues/993

fixed template for "modules create"

---

nf_core/modules/test_yml_builder.py

Removes the `tool_subtool` tag from the default list of tags, as we decided to only run with:
- tool
- tool/subtool
as tags.

remove the "tool_subtool" tag from create-test-yml

---

nf_core/pipeline-template/nextflow.config

The parameter `custom_profile_name` is in the schema but was missing in the nextflow config, causing the linting to warn. This should fix it.

Initialize `custom_profile_name`in nextflow config

---

CHANGELOG.md
README.md

@ErikDanielsson has done an awesome job and we now have a functioning `nfcore/tools` docker container that seems to be working nicely! (x-ref https://github.com/nf-core/tools/issues/917)
I have done a bit of testing and figured out the required `docker run` flags needed to use it. Here is some documentation.

Write docs for running nf-core tools docker image

---

CHANGELOG.md
nf_core/pipeline-template/lib/NfcoreSchema.groovy

As discussed on slack, replace `d` with `day` for Nextflow Duration objects within `cleanParameters()`

make cleanParameters more robust

---

nf_core/pipeline-template/main.nf

Minor tweak to the `checkHostname()` function to make the bottom border the same length as the top.
Also added red colours for both.

Fix mismatch === chars and colours in `checkHostname()` function

---

nf_core/list.py

Missing space in list.py was causing 'nf-core launch' to to fail when running with revision.

Add missing space to list.py

---

tools.Dockerfile

Make sure users other than root can run `nextflow` within the container.

Fix nextflow permissions for non-root users in docker

---

CHANGELOG.md
nf_core/utils.py
tests/test_utils.py

Catch permission errors while setting up cache directories for requests.
This allows at least starting `nf-core` and some operations (e.g. `download`) without a writable directory designated by `$HOME`.

Ignore any permission errors while creating/checking requests cache dirs

---

nf_core/__main__.py
nf_core/modules/lint.py

Previously, the `-r` and `-b` arguments, specifying the GitHub repository and branch from which to download modules, wasn't used in the module specific lint command. This meant that if you installed a module from a repository other than `nf-core/modules`, and then used `nf-core modules lint` to check if the module was out of date, then it would always be compared to the `nf-core/modules` repository. I've made it so that the `ModuleLint` class uses the `-r` and `-b` command line parameters when it checks for a remote copy.

Module lint uses repository and branch specified on command line

---

CHANGELOG.md
docs/api/_src/pipeline_lint_tests/params_used.rst
nf_core/lint/__init__.py
nf_core/lint/merge_markers.py
nf_core/lint/params_used.py

Check if all params returned from `nextflow config` are mentioned somewhere in `main.nf`.
Will need updating for DSL2 to run with... all `.nf` files maybe? Or in certain paths?
Closes #1038

New lint test: `params_used`

---

CHANGELOG.md
nf_core/create.py
nf_core/lint/merge_markers.py
nf_core/utils.py

Merge markers lint test:
* Ignore binary files
* Added ability to ignore specific files in the lint config.
Moved binary detection function into utils.

Lint - merge markers - ignore binary files.

---

CHANGELOG.md
nf_core/pipeline-template/lib/NfcoreSchema.groovy

Temporary fix for https://github.com/nf-core/tools/issues/1035

fix camelCase params warnings

---

.github/workflows/create-lint-wf.yml
.github/workflows/pytest.yml
.github/workflows/sync.yml
CHANGELOG.md
nf_core/bump_version.py
nf_core/pipeline-template/.github/workflows/ci.yml

Now that the stable 21.04.0 Nextflow release is out, we can revert to using the latest stable version of Nextflow for CI tests etc.
Hopefully I got them all...

Remove special nxf 21.03.0-edge versions

---

CHANGELOG.md
nf_core/download.py

So apparently I added this code back for the `v1.13` release, but I think it breaks stuff. As much as that hyphen brings back a certain aesthetic to the image filenames, it also means that they do not match the filename that Nextflow is looking for when it runs the pipeline. This means that Nextflow then tries to fetch the image.
Discovered in diaproteomics pipeline [in Slack](https://nfcore.slack.com/archives/C017PDRCQQG/p1620252286147100). Kind of surprised that we haven't had more bug reports about this one 🤔 
Sorry all.. 🙏🏻

Singularity download - don't add hyphen

---

CHANGELOG.md
nf_core/utils.py

This is better as we don't lose the cache from other calls, but we do still get fresh data from the website poll.
As a side-effect, we lose the `INFO` log messages which closes nf-core/tools#1029

Don't clear entire requests_cache cache when polling the website

---

nf_core/lint/params_used.py

Add `igenomes_base` and `igenomes_ignore` to the params to ignore in `params_used` lint test.

Add `params_used` lint ignore list

---

CHANGELOG.md
nf_core/__main__.py
nf_core/sync.py

Trying to fix the automated sync again. See https://github.com/nf-core/tools/issues/1071 for debrief.

Fix sync. Again.

---

CHANGELOG.md
nf_core/schema.py

Schema - don't make default null for null values.

---

CHANGELOG.md
nf_core/module-template/software/functions.nf

As discussed on #1076, the comments on `functions.nf` template have been updated to follow the new commenting style.
Closes #1076

Update comments on functions.nf

---

CHANGELOG.md
nf_core/pipeline-template/lib/NfcoreSchema.groovy
tests/test_modules.py

Fixes the bug described in #1087 
Now typos like `--clip_R1` instead of `--clip_r1` are properly recognized again.

fix bug in parameter validation

---

CHANGELOG.md
nf_core/modules/test_yml_builder.py

The `contains:` map needs an array of strings.  By placing the TODO comment between brackets I hope that the user will be more likely to produce a valid file. 
Closes: #1082

Put the TODO comment in a YAML array.

---

nf_core/pipeline-template/conf/igenomes.config

Rnor_5.0 is available in AWS iGenomes, but missing in the config file leading to pipeline errors. This commit should fix it and propagate the fix to all pipelines.
See also https://github.com/nf-core/rnaseq/issues/639
I don't think such a small change warrants this, but let me know if it does.
I hope existing tests cover this small change.

Add missing iGenome - Rnor_5.0

---

CHANGELOG.md
nf_core/download.py
tests/test_download.py

Small bugfix - when running `nf-core download` it edits the `nextflow.config` file to make it work with the downloaded files with relative links.
The singularity cacheDir stuff correctly uses `$projectDir` to make these paths relative to the workflow, irrespective of where it was run from. However, the config base did not.

Download - use relative path for configs import

---

nf_core/module-template/software/functions.nf
nf_core/modules/lint.py
tests/test_modules.py

`nf-core modules lint` currently generates a warning if the `functions.nf` doesn't match that present in the modules template. This PR downgrades it to a failure so it is more visible to developers who submit to nf-core/modules. Much easier than checking manually and commenting.

Fail if functions.nf doesnt match template

---

nf_core/launch.py
nf_core/schema.py
tests/test_launch.py
tests/test_schema.py

the website counterpart was fixed in https://github.com/nf-core/nf-co.re/pull/760 and I forgot that the tools part also checks for it, sorry.

fix status typo for schema

---

CHANGELOG.md
setup.py

Looks like the version number was never bumped after the release - probably my fault, sorry (this is what you get for doing a live release during a talk!).
Bumping to v1.15dev now.

Bump to v1.15dev

---

CHANGELOG.md
nf_core/module-template/software/main.nf
nf_core/modules/create.py
nf_core/utils.py

Use the Biocontainers API instead of quay.io to get container tags for Docker and Singularity containers as suggested in #875 
I have not implemented any questionary selection now, as you have suggested @ewels . Mainly because I think it would be good to have the most recent version as default, and allowing users to choose a container tag/version for both Docker and Singularity could mean they choose different builds. The linter should complain about this, or we could directly check within `nf-core modules create`, but easiest would be to just avoid this in the first place.
Wouldn't be too hard to add it in though so up for discussion I'd say :-)

Biocontainer api

---

.github/workflows/tools-api-docs-release.yml

This should hopefully solve #1073.

Updated gh actions for release 

---

CHANGELOG.md
nf_core/modules/remove.py

Updated `nf-core modules remove` to remove entry in `modules.json` as suggested in #1115. If entry is missing from `modules.json` the user is asked if they want to continue removing the module directory.

Updated `nf-core modules remove` to remove entry in `modules.json`

---

CHANGELOG.md
nf_core/modules/install.py
nf_core/modules/modules_command.py
nf_core/modules/remove.py

Fixed the interactive prompt in `nf-core modules install` for selecting modules version which was failing due to too few arguments. I took the liberty of placing the reads and writes to the `modules.json` file in their own methods also.

Fix bug in `nf-core modules install` version prompt

---

CHANGELOG.md
nf_core/modules/list.py
nf_core/modules/module_utils.py
nf_core/modules/modules_command.py
tests/test_modules.py

Updated `nf-core modules list` to show 
- the commit SHA
- the commit message
- the commit date
for the locally installed modules, if the `modules.json` file is present. If the `modules.json` file is missing the old version of the `list` command is shown, i.e. only the names of the installed modules

Update `nf-core modules list` to show module versions

---

CHANGELOG.md
nf_core/__main__.py
nf_core/modules/create.py
nf_core/modules/install.py
nf_core/modules/lint/__init__.py
nf_core/modules/lint/module_tests.py
nf_core/modules/list.py
nf_core/modules/module_utils.py
nf_core/modules/modules_command.py
nf_core/modules/modules_repo.py
nf_core/modules/remove.py

Cleaned up exit behavior in `modules` directory. Instead of doing hard exits with `sys.exit` we raise exceptions which are passed down the calling stack and causes the program to exit from `__main__.py`.

Clean up program exits in `modules`

---

nf_core/modules/module_utils.py

Added API response code to error when `module_utils/get_module_git_log` fails to fetch the git log of a module.

Add API response code to error from `module_utils/get_module_git_log`

---

nf_core/list.py

I tried doing a live demo earlier today and ran `nf-core list modules`. To my confusion, this just returned an empty table.
This PR:
* Shows a message if no pipelines are found, instead of printing an empty table
* Shows a bonus help message if `modules` was the only filter keyword
```console
$ nf-core list modules
,--./,-.
`._,._,'
nf-core/tools version 1.14.dev0
No pipelines found using filter keywords: 'modules'
💡 Did you mean 'nf-core modules list' instead?
```

List - message if no results, suggest similar but different command

---

.github/workflows/create-lint-wf.yml
CHANGELOG.md
README.md
nf_core/__main__.py
nf_core/bump_version.py
nf_core/lint/__init__.py
nf_core/modules/module_utils.py
nf_core/modules/modules_command.py
nf_core/schema.py
nf_core/sync.py
nf_core/utils.py

Updated passing of arguments to `nf-core` commands and subcommands:
- Pipeline directory is now passed with `--dir <pipeline directory>` with `.` as default, for all `nf-core` commands that previously had it as an argument. Resolves #1140
- Pipeline directory for `nf-core modules list` is now passed with `--installed <pipeline directory>`. Partially resolves #1139
- `--tool <tool name>` for `nf-core modules` subcommand are now replaced by optional argument `<tool>`. For example: `nf-core modules install fastqc`.
- Updated docs text, but not the console logs.

Refactor passing of command line arguments to `nf-core` commands

---

CHANGELOG.md
nf_core/modules/test_yml_builder.py

Fixes a bug in `nf-core create-test-yml` (introduced by yours truly).
Because I moved the work directory to the temp dir that we use to create the output files and calculate the hash sums, things like `.command.out` and the entire content of the `work` dir is added to the `test.yml`
So instead we're just making an extra temp dir now and use that as the `work` directory.

Fix create test yml

---

CHANGELOG.md
nf_core/__main__.py
nf_core/modules/list.py

Added new positional argument `<keywords>` to `nf-core modules list` which takes zero or more keywords and uses them to filter the retrieved modules. Should close #1139.

Added filtering by keywords to `nf-core modules list`

---

CHANGELOG.md
docs/api/_src/pipeline_lint_tests/modules_json.rst
nf_core/lint/__init__.py
nf_core/lint/modules_json.py
tests/lint/modules_json.py
tests/test_lint.py

This PR adds a new pipeline lint check (`nf-core lint`) which looks for module entries in the `modules.json` of modules that are not actually installed in the pipeline.
I thought it makes sense to package that into the `nf-core lint` command as it looks at a general pipeline file (`modules.json`) and compares that against all installed modules. The `nf-core modules lint` command is more module-centric, meaning that it runs specific lint tests for every module separately. Therefore I think it is more logical to add this check here.

Lint the `modules.json` for uninstalled modules

---

CHANGELOG.md
nf_core/modules/test_yml_builder.py

Fix bug in `nf-core modules create-test-yml` that occurs when specifying the output directory.
Now the simply doesn't compare md5 sums when a output directory is specified. Otherwise we'd have to ask the user for two directories which gets a bit much. The best way is to run it without a specified directory anyway.
Fixes #1148

fix create-test-yml

---

CHANGELOG.md
tests/lint/files_unchanged.py
tests/lint/modules_json.py
tests/lint/nextflow_config.py
tests/modules/bump_versions.py
tests/modules/create.py
tests/modules/create_test_yml.py
tests/modules/install.py
tests/modules/lint.py
tests/modules/list.py
tests/modules/remove.py
tests/test_lint.py
tests/test_modules.py

Refactored test directory:
- The test for the different `nf-core modules` subcommands are now placed in individual files
- The last few direct tests that depend the number of passed/warned/failed tests are now replaced with inequalities, e.g.:
`assert len(self.passed) == 37` ==> `assert len(self.passed) > 0`.
- Renamed the test in `lint/modules_json.py`.
Partially resolves #1158.

Refactor tests

---

nf_core/modules/install.py
nf_core/modules/module_utils.py
nf_core/modules/modules_command.py
nf_core/modules/modules_repo.py
tests/modules/install.py

Updated `nf-core modules install` (and some other stuff...) to accommodate new directory structure, as suggested in #1159:
- Update structure in `modules.json` to: 
```json
...
repos: {
"repo_owner/repo_name": {
"module_name": {
"git_sha": commit_sha
}
...
} 
...
}
```
- Updated creation of `modules.json` accordingly. 
- Changed default value for `since` in `module_utils.get_module_git_log` due to breaking changes in `nf-core/modules`.
- Changed references to `software` directory to `modules` in `ModulesRepo`.

Adapt `modules install` to new directory structure

---

CHANGELOG.md
nf_core/modules/list.py
nf_core/modules/modules_command.py
nf_core/modules/remove.py

Updated `modules remove` and `modules list` for restructuring and changed some features: 
- `ModulesCommand.get_pipeline_modules()` now assigns a dictionary instead of a list to `module_names`.
- The install repository is now included in the `modules list` table. 
- Deprecated the old style of `modules list` (i.e. the one for pipelines without a `modules.json` file)
- `modules remove` prompts the user for the remove repository, if there is more than one present in the pipeline and the `--repository` option is set to `nf-core/modules`. 
I'm not sure about the last point, there should be a better way to configure this. My idea was to make it a bit more convenient for someone who has a pipeline with several install repos.

Updated `modules remove` and `modules list` for restructuring 

---

nf_core/modules/module_utils.py

Issue a warning when we can't get the `git_sha` for a module instead of raising a warning and exiting.
This way the `modules.json` get's created and we can continue installing modules.
The linting still warns about missing entires in the `modules.json`.

Don't exit `modules install` when no commit hash is found

---

CHANGELOG.md
nf_core/__main__.py
nf_core/modules/install.py
nf_core/modules/modules_command.py

Added `--all` flag to `nf-core modules update`. When running with the `--all` flag the command  has the same effect as looping `nf-core modules install --force` over all installed modules. For example:
- When `nf-core modules install --all` is run, there is a cli prompt for every module.
- To update all modules to the latest version _without a prompt_: `nf-core modules install --all --latest`
- To change all modules to a specific version _without a prompt_: `nf-core modules install --all --sha <commit sha>`

Add `--all` flag to `nf-core modules install`

---

CHANGELOG.md
nf_core/__main__.py
nf_core/modules/list.py
tests/modules/list.py

Added `remote` and `local` subcommands to `nf-core modules list` for listing modules available from the `nf-core/modules` repository and modules installed in the current pipeline respectively.

Add subcommands to `nf-core modules list`

---

nf_core/pipeline-template/modules/nf-core/modules/fastqc/main.nf

Just bring the fastqc module to the latest version so there are less linting warnings with a fresh template

update fastqc module in template to latest version

---

CHANGELOG.md
nf_core/module-template/tests/main.nf
nf_core/module-template/tests/test.yml

The `tests` directory in the module template was not updated after the restructuring of `nf-core/modules`. This should fix the issue.

Fix bug in module template due to restructuring

---

CHANGELOG.md
README.md
nf_core/modules/install.py
nf_core/modules/lint/__init__.py

Update docs for v2.0 release:
- Changed version numbers in console output to 2.0 for all commands except `licenses`. 
- Updated console output for `lint` and `modules lint`, and added console output for `modules list local`. 
- Added docs for `modules list` subcommands.  
- Made a few cosmetic changes to the console output for `modules install` and `modules lint`.

Update docs for v2.0 release

---

CHANGELOG.md
nf_core/modules/module_utils.py
nf_core/modules/modules_command.py

`nf-core modules list local` (and probably other commands as well)  were failing on pipelines with the older directory structure. This should fix the issue, by checking that the remote modules directories in the pipeline have a valid GitHub repository before doing anything else.

Added additional checks for module remote repos

---

CHANGELOG.md
nf_core/pipeline-template/.github/workflows/linting.yml

`nf-core lint` is failing for all pipelines because we missed a `--dir` declaration in the `linting.yml` Github Actions used by pipelines.

Add --dir parameter to pipeline template linting CI

---

CHANGELOG.md
nf_core/modules/install.py
nf_core/modules/list.py
nf_core/modules/module_utils.py
nf_core/modules/modules_command.py
nf_core/modules/modules_repo.py
nf_core/utils.py

Added consistency checks between modules present in pipeline and `modules.json`:
- If a module is missing from the directory but is present in the `modules.json` file we try to reinstall it at the given commit SHA
- If the install fails, we remove the entry in `modules.json`
- If a module is present in the directory, but missing from `modules.json` we try figure out the correct one using the file contents. If that fails, we continue but warn the user. 
These checks are run when either `nf-core modules install` or `nf-core modules list local` are run. Should resolve #1199.

Add consistency checks between installed modules and `modules.json`

---

CHANGELOG.md
nf_core/lint/__init__.py
nf_core/modules/lint/__init__.py

Fixed the `modules lint` tests not filtering properly when running `nf-core lint` with the `--key` option. One can now select both `modules lint` and `lint` tests with `--key`. Should close #1203.

Fix `nf-core lint` running unwanted modules test when using `--key` option

---

CHANGELOG.md
nf_core/lint/__init__.py

The `nf-core lint` command was complaining about missing the `modules.json` file, as reported in #1198. This PR adds the `ModulesCommand.has_valid_pipeline` function that checks whether the pipeline is valid and adds the `modules.json` file if it is missing.

Add pipeline verification function to `nf-core lint` 

---

CHANGELOG.md
nf_core/bump_version.py
nf_core/pipeline-template/README.md

Updated changed link for Nextflow installation from `nf-co.re/usage/installation` to `https://www.nextflow.io/docs/latest/getstarted.html#installation` as suggested in #1201. Updated `nf-core bump-version` to check for references to `nf-co.re/usage/installation` and replace them with the Nextflow link.

Update Nextflow installation link in pipeline template

---

CHANGELOG.md
nf_core/modules/module_utils.py
tests/modules/lint.py

Fixed `nf-core modules install` incorrectly installing from the `master` branch when `--branch` is supplied, as reported in #1218.

Fix `nf-core modules install` ignoring `-b` option

---

.github/workflows/create-lint-wf.yml
CHANGELOG.md
README.md
nf_core/__main__.py
nf_core/modules/__init__.py
nf_core/modules/install.py
nf_core/modules/module_utils.py
nf_core/modules/modules_command.py
nf_core/modules/update.py
tests/test_modules.py

Moved the module updating duties from `nf-core modules install` to `nf-core modules update`. 
`nf-core modules install` has the following changes:
- The `--all` flag is removed
- `--latest` is made default. One can select the version using the cli prompt with `--prompt`. 
`nf-core modules update` has the following features:
- Checking the version of a single module and updating if needed: `nf-core modules update`
- Selecting a specific version to update to `nf-core modules update --prompt`
- Updating a single module to a specific version if needed: `nf-core modules update --sha <commit sha>`
- Forcing the reinstallation of the module files: `nf-core modules --force`
- Running the command on all modules in the pipeline `nf-core modules update --all`. All of the other flags works with …

Add `nf-core modules update`

---

.github/workflows/sync.yml
CHANGELOG.md
README.md
nf_core/__main__.py
nf_core/download.py
tests/test_download.py

Changed the names of some flags with `-r` as short options to make the flags more consisten between commands:
- The `--release` flag for `nf-core download` is renamed to `--revision` (as well as some of the names in the code). 
- The `--repository` flag for `nf-core modules` and `nf-core sync` is renanmed to `--github-repository` with the accompanying short option renamed from `-r` to `-g`.
- The short option for the `--run-tests` flag for `nf-core modules create-test-yml` is renamed from `-r` to `-t`. 
Also added a section for the `nf-core modules` level flags in the docs.

Update flags with `-r` as short option

---

CHANGELOG.md
README.md
nf_core/modules/install.py
nf_core/modules/modules_repo.py
nf_core/modules/update.py
nf_core/utils.py

Added support for ignoring modules and specifying module versions in `.nf-core.yml` when running `nf-core modules update` at both the module and repository level. A `.nf-core.yml` can for example be configured in the following way:
```yaml
lint:
...
bump-versions: 
...
update: 
nf-core/modules:
fastqc: False
multiqc: True
untar: "e937c7950af70930d1f34bb961403d9d2aa81c7"
another-user/modules: False
yet-another-user/some-repo: "e937c7950af70930d1f34bb961403d9d2aa81c7"
```
Leaving out a module or a repository has the same effect as settting it to `True`. The commit SHAs set in `.nf-core.yml` ` command has higher precedence than commit SHAs set with `--sha`. 
Should close #1204.

Add support for `.nf-core.yml` to `nf-core modules update`

---

CHANGELOG.md
nf_core/modules/update.py

Added an interactive prompt in `nf-core modules update` if neither a module name nor the `--all` flag is supplied.

Add prompt in `nf-core modules update` if neither module name nor `--all` flag are supplied

---

nf_core/modules/lint/main_nf.py

`modules lint`command is not formatting correctly the line corresponding to the conda version
```
│ adapterremoval                           │ modules/adapterremoval/main.nf        │ Conda package is the latest available: {bp}                                                                                  
```
The reason is that the corresponding `f-string` is missing the  `f`

f missing on f-string lint message conda version

---

CHANGELOG.md
nf_core/modules/install.py
nf_core/modules/module_utils.py
nf_core/modules/modules_command.py
nf_core/modules/update.py

Added verification that a commit SHA provided through `--sha` in `nf-core modules update/install` exist in the remote.

Add verification of SHA from `--sha`

---

CHANGELOG.md
nf_core/modules/bump_versions.py

Using `nf-core modules bump-versions --all` fails the ECLint tests because a new-line isn't added to the end of `main.nf` once it is written. e.g.
https://github.com/nf-core/modules/pull/629/checks?check_run_id=3171084274

Add new-line to main.nf after nf-core modules bump-versions

---

nf_core/modules/module_utils.py

Change from `Select <module> version` to `Select <module> commit` in `install/update` prompts.

Change from version to commit

---

nf_core/__main__.py

Updated  `nf-core modules create --author` help message to inform user that the username should be prefixed with @.

Update `nf-core modules create --author` help message

---

CHANGELOG.md
nf_core/module-template/modules/main.nf

Fixed `nf-core modules create` duplicating parts of the links to the docker and singularity containers.

Fix duplication of links by `nf-core modules create`

---

CHANGELOG.md
nf_core/modules/module_utils.py

Fixed a potentially dangerous typo in `module_utils.py`

Fix typo in `module_utils.py`

---

CHANGELOG.md
nf_core/modules/bump_versions.py
nf_core/modules/create.py
nf_core/modules/remove.py
nf_core/modules/update.py

A few of the commands weren't exiting properly or at all due to the `KeyboardInterupts` being caught by the `ask` function from `questionary`. They are now changed to `unsafe_ask` so the process exits on keyboard interupts. Should close #1237.

Change `questionary` `ask` to `unsafe_ask` to cancel execution on keyboard interupts

---

nf_core/modules/create.py

The `nf-core modules create` was the module name as missing from the Anaconda API even when `-c <conda name>` was specified, which was causing the issue in #1255. Fixed by updating the error message when the Anaconda API call fails.

Fix bug in `nf-core modules create` due to bad Anaconda API error handling

---

CHANGELOG.md
nf_core/launch.py

Fixed bug due to pipeline revision specified with the `-r` flag to `nf-core launch` command not being added to the Nextflow command, as reported in #1246.

Fixed `nf-core launch` not passing `--revision` value to the Nextflow command

---

CHANGELOG.md
nf_core/lint_utils.py

Update "fix" message from `nf-core lint` to conform to the current command line options. Should close #1259.

Update outdated "fix" message from `nf-core lint`

---

CHANGELOG.md
nf_core/lint/readme.py

Updated the Nextflow installation link in the `readme` test of `nf-core lint` to agree to the link in the pipeline template. Should close #1260.

Update regex in `readme` test of `nf-core lint` 

---

CHANGELOG.md
nf_core/__main__.py

Updated help text for `nf-core modules create`which were not changed after the introduction of the `--dir`flag.

Update `nf-core modules create` help text

---

nf_core/pipeline-template/CITATIONS.md

The multiqc link kept the old format in the citations template, to be consistent with the other pubmed links (nf-core and nextflow) it was updated.

Update multiqc link in citations template

---

nf_core/modules/lint/main_nf.py

The script section must contain `getProcessName(task.process)` - The process name must be contained
in the `versions.yml` file. 
PR related to https://github.com/nf-core/modules/pull/744

Update linting for versions.yml

---

nf_core/module-template/modules/main.nf
nf_core/module-template/modules/meta.yml
nf_core/pipeline-template/modules.json
nf_core/pipeline-template/modules/local/samplesheet_check.nf
nf_core/pipeline-template/modules/nf-core/modules/custom/dumpsoftwareversions/main.nf
nf_core/pipeline-template/modules/nf-core/modules/fastqc/main.nf
nf_core/pipeline-template/modules/nf-core/modules/multiqc/main.nf
nf_core/pipeline-template/subworkflows/local/input_check.nf
nf_core/pipeline-template/workflows/pipeline.nf

Porting fixes from https://github.com/nf-core/modules/pull/780

 Update modules in pipeline template with new versions syntax

---

CHANGELOG.md
nf_core/download.py
nf_core/utils.py
tests/test_download.py

Dear developers,
This PR will solve #1296 (`test_wf_use_local_configs` is not working as expected) by disabling caching config during test

fix test_wf_use_local_configs

---

CHANGELOG.md
nf_core/lint/__init__.py

Dear all,
while I was working on another issue, I found that I can't call tests only on `tests/test_modules.py` since a circular import prevents me to call those tests, as described by @grst in #1270. I think I solved by changing the import in `nf_core/lint/__init__.py` and by calling `ModuleLint` using full module path. This let you to import `nf_core.modules.lint` from a Python terminal and to call the individual tests on modules with:
```bash
pytest --color=yes tests/test_modules.py --verbose
```
Hope this helps.
----
This could close #1270

fix issue with Circular import of ModuleLint

---

nf_core/pipeline-template/README.md

Trying to make the quickstart section easier to read, as we keep having people running the pipelines with just `-profile test`.
* Avoid using `<docker>` etc as that is less clear that it's required
* Avoid very long string of different container technologies
* Minor tweaks of text

pipeline readme - docs tweak for config profile quickstart

---

nf_core/modules/module_utils.py

When `--dir` option was provided to `nf-core lint` it was throwing an exception. Fixed by joining `dir` when checking for the `README.md` 
Closes #1328

Join dir to readme to determine repository type

---

tests/test_modules.py

After PR  #1322 tests were failing since `create_modules_repo_dummy()` was not creating a README.md in the module tree.

Create README.md when a dummy module is created

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/workflows/create-lint-wf.yml
.github/workflows/create-test-wf.yml
CHANGELOG.md
nf_core/lint/readme.py
nf_core/module-template/modules/main.nf
nf_core/module-template/tests/main.nf
nf_core/pipeline-template/.github/ISSUE_TEMPLATE/bug_report.yml
nf_core/pipeline-template/.github/workflows/ci.yml
nf_core/pipeline-template/README.md
nf_core/pipeline-template/conf/modules.config
nf_core/pipeline-template/docs/usage.md
nf_core/pipeline-template/modules.json
nf_core/pipeline-template/modules/local/samplesheet_check.nf
nf_core/pipeline-template/modules/nf-core/modules/custom/dumpsoftwareversions/main.nf
nf_core/pipeline-template/modules/nf-core/modules/custom/dumpsoftwareversions/meta.yml
nf_core/pipeline-template/modules/nf-core/modules/custom/dumpsoftwareversions/templates/dumpsoftwareversions.py
nf_core/pipeline-template/modules/nf-core/modules/fastqc/main.nf
nf_core/pipeline-template/modules/nf-core/modules/fastqc/meta.yml
nf_core/pipeline-template/modules/nf-core/modules/multiqc/main.nf
nf_core/pipeline-template/modules/nf-core/modules/multiqc/meta.yml
nf_core/pipeline-template/nextflow.config
nf_core/pipeline-template/nextflow_schema.json
nf_core/pipeline-template/subworkflows/local/input_check.nf
nf_core/pipeline-template/workflows/pipeline.nf
tests/test_bump_version.py

x-ref: https://github.com/nf-core/tools/issues/1290 https://github.com/nf-core/tools/issues/1289

Update module and pipeline template

---

nf_core/module-template/modules/main.nf
nf_core/modules/lint/main_nf.py
nf_core/pipeline-template/conf/modules.config
nf_core/pipeline-template/modules.json
nf_core/pipeline-template/modules/nf-core/modules/fastqc/main.nf

**DO NOT MERGE UNTIL AFTER ELIXIR WORKSHOP**
This replaces the slightly restrictive `$suffix` to a completely flexible `$prefix` parameter for naming output files - as made possible by DSL2 v2 syntax. 
This corresponds to what will change in the modules repository:
- https://github.com/drpatelh/nf-core-modules/commit/01d0b699359232835aac5c79af68c6267bdf05c5
- https://github.com/drpatelh/nf-core-modules/commit/90a41f843273b350bf216b41c7d2c47fefc60960
I think I caught everything (did a search with vscode for `suffix`)

Replaces suffix with completely customisable prefix variable

---

nf_core/modules/modules_command.py
nf_core/modules/modules_repo.py

Don't set the module repo branch to `master` by default if we're not working with the main nf-core/modules repo.

Don't assume that the module repo branch is master if not set

---

CHANGELOG.md
nf_core/pipeline-template/.github/CONTRIBUTING.md
nf_core/pipeline-template/.github/workflows/awsfulltest.yml
nf_core/pipeline-template/.github/workflows/awstest.yml

We detected some missing points during have been detected during the release of fetchngs version 1.5, see [here](https://github.com/nf-core/fetchngs/pull/59). Namely:
* Update `CONTRIBUTION.md` bullets to remove points related to `scrape_software_versions.py`
* Update AWS test to set Nextflow version to 21.10.3

Update template with some DSL2 v2.0 bits detected during fetchngs ver 1.5 release 

---

.github/workflows/pytest.yml
CHANGELOG.md
nf_core/modules/lint/module_tests.py
nf_core/modules/test_yml_builder.py

Brace yourselves for lots of new modules linting errors.. 😱 
Can think about changing this from a warn to a fail once the offending md5sums are all removed. I'd prefer that as I don't think that there's a good reason to have the md5sum in this case (?) but don't want to suddenly introduce so many failures.
Addresses #1302

Modules lint: Check for md5sums of empty files

---

CHANGELOG.md
nf_core/modules/lint/module_changes.py
tests/modules/bump_versions.py
tests/modules/create_test_yml.py
tests/test_modules.py

If the local copy of a module is edited and does not match the remote, throw an error instead of a warning (with a clearer message too).
Fixes #1313
Not sure if there are cases where we don't want this to happen? But I can't think of any.

Module lint: Fail instead of warn if local copy edited

---

nf_core/pipeline-template/.github/workflows/ci.yml

Don't run `nextflow self-update` in CI tests. Should fix https://github.com/nf-core/tools/issues/1361
Also, move static env vars to top level of the workflow.

Don't run `nextflow self-update` in CI tests

---

.github/workflows/create-lint-wf.yml
.github/workflows/create-test-wf.yml
CHANGELOG.md

Fixing the CI workflows of nf-core/tools in a similar way as for the pipelines

Fix tools CI workflows

---

nf_core/modules/lint/module_changes.py

Reverts https://github.com/nf-core/tools/pull/1357 because modules will be changed on PRs to nf-core/modules and hence always result in linting failures.
Couldn't see a `CHANGELOG` entry so just the 1 word to change. Nothing else to see here.

Warn instead of fail if module is different from remote

---

CHANGELOG.md
nf_core/modules/lint/__init__.py
nf_core/modules/lint/module_changes.py

Revert #1364 which reverted #1357
Brings back a failure instead of a warning if a module doesn't match the remote copy in nf-core/modules. _However_, now this particular lint test is only run when linting a pipeline, not when linting the modules repo.
Should mean that people can now propose changes to modules.. 🙄

Check modules fail, but for pipelines only

---

CHANGELOG.md
nf_core/download.py

Update the code-scraping-code that discovers container URLs in DSL2 module code. Hopefully now works with both old and new DSL2 styles. Should close #1379.

First attempt to make download work with new DSL2 syntax.

---

nf_core/modules/module_utils.py

Handle a missing `modules` directory when running `nf-core modules list local` in a DSL1 pipeline. Give a nice error message instead of a big stack trace.

modules list local - handle DSL1 pipelines

---

CHANGELOG.md
nf_core/module-template/modules/main.nf

Addition:
Allow modules to use `when:` block by moving it to configuration.
```
when:
task.ext.when == null || task.ext.when
```
Allows modules to flexibly use the `when:` from the configuration file. 
Allows conditional process execution on settings not available in the `workflow` block. 
Configuration is set using `process.ext.when` allowing one to use process selectors and other configuration benefits to 
apply a when condition to a group of processes or test process specific values.
Execution conditions
```groovy
process {
withName: 'FOO' {
ext.args = 'module1,module2'
// Example settings
ext.when = null                           // Process executes - no conditional defined. 
ext.when = true                          // Process executes - e.g. override for existing configuration …
```

Allow conditional process execution from configuration

---

CHANGELOG.md
nf_core/pipeline-template/conf/igenomes.config

On the previous version of the `igenomes.config` only the `genome.fa` was fetch. This was an issue since with the current implementation of the `bwa_mem` it was not possible to only provide the `genome.fa` file. Changing the path to `${params.igenomes_base}/Homo_sapiens/Ensembl/GRCh37/Sequence/BWAIndex/`, also did not work since this folder content subfolder for the different versions of the `bwa` index which was not only breaking the module execution but also fetching unnecessary folders, e.g.:
```bash
$ tree /scratch/stage/f6/d7b7c4bdaca845ba403d1c844a11ee/BWAIndex/
├── genome.fa
├── genome.fa.amb
├── genome.fa.ann
├── genome.fa.bwt
├── genome.fa.pac
├── genome.fa.sa
├── version0.5.x
│   ├── genome.fa
│   ├── genome.fa.amb
│   ├── genome.fa.ann
│   ├── genome.fa.bwt
│   ├── …
```

Update igenomes path to BWAIndex

---

CHANGELOG.md
nf_core/modules/lint/main_nf.py

Adds module linting for when condition

Add module linting for when condition

---

.github/workflows/markdown-lint.yml
CHANGELOG.md
README.md
nf_core/pipeline-template/.github/workflows/linting.yml
nf_core/pipeline-template/docs/usage.md

Fixes markdown linting, which now requires at least node version 12.
Hopefully pushing to 16 gives us some future-proofing for a while.

Bump node-version to 16

---

nf_core/modules/lint/main_nf.py

Tweak lint message for checking `when:` condition

---

CHANGELOG.md
nf_core/__main__.py

Took code from rich-cli written by @willmcgugan and played around with until it worked for us.
It's so pretty 🤩 
* Help strings are no longer truncated if they're a bit on the long side
* Text now stuff wraps onto multiple lines for narrow terminals and long help texts
* I've set it to use a maximum width of 100 chars, instead of the full terminal width. Personal preference.
* ~We have a custom [`@click.version_option()`](https://click.palletsprojects.com/en/8.0.x/api/?highlight=version_option#click.version_option) which doesn't seem to make it into the help, I don't know how to fix this.~
<table>
<tr>
<th>Before</th>
<th>Afer</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>

First stab at nicely formatted cli help output using Rich.

---

CHANGELOG.md
nf_core/__main__.py

Keep @Midnighter happy ;)
This is in addition to the previous `--help`.
One piece of collateral damage: `nf-core launch` had a short form `-h` flag for `--hidden`. I've changed this to `-x`.

Use `-h` as a help flag

---

.yamllint.yml
CHANGELOG.md
nf_core/pipeline-template/.github/ISSUE_TEMPLATE/bug_report.yml
nf_core/pipeline-template/.github/workflows/linting.yml
nf_core/pipeline-template/.yamllint.yml

Adds a `.yamllint.yml` config to avoid `line too long` and `missing document start "---"` errors.
Closes #1407

Add yamllint config to template

---

nf_core/pipeline-template/docs/usage.md

Updates suggestion for writing custom configuration.

Update usage info

---

.github/workflows/yamllint.yml
.yamllint.yml
CHANGELOG.md
nf_core/pipeline-template/.github/workflows/linting.yml
nf_core/pipeline-template/.yamllint.yml

Use [this](https://github.com/marketplace/actions/yamllint-github-action) github action to enable the recognition of the `yamllint.yml` and avoid undesired errors.
Closes #1404

Make yamllint config recognisable by the yml lint github action

---

CHANGELOG.md
README.md
nf_core/__main__.py
nf_core/modules/bump_versions.py
nf_core/modules/create.py
nf_core/modules/lint/__init__.py
nf_core/modules/module_utils.py
nf_core/modules/modules_command.py
nf_core/pipeline-template/.nf-core.yml
tests/test_modules.py

As discussed on Slack, it's a fairly frequent problem for users to struggle with creating modules due to:
* not running in the root repo directory
* the automatic detection of repo type not working (eg. custom repos for modules)
* the automatic detection breaking / not working (eg. when we added a `main.nf` to nf-core/modules)
Here I've introduced more explicit declaration of the repo type:
* Use `.nf-core.yml` file if we can find it, with `repository_type` key
* Traverse parent directories to look for this file, reset target directory if found (so that we can run from a nested directory)
* Add command line `--repo-type` flag to specify repo type if no `.nf-core.yml` file available

Rewrite modules create repo type check.

---

CHANGELOG.md
nf_core/pipeline-template/nextflow.config

This is now utilised for a few pipelines (eager, sarek, rnaseq), but may not be full well known this exists.
This PR adds this as a possibility for pipeline devs once such a config exists, but otherwise is commented out to prevent config loading breaking if such a config doesn't exist.

Add to pipeline template optional loading of institution specific pipeline configs

---

.github/workflows/build_gitpod.yml

Builds Gitpod container on push to dev.
Propagates Gitpod image changes on push to dev so the changes can be available early.

Build Gitpod container on push to dev

---

CHANGELOG.md
nf_core/pipeline-template/.github/PULL_REQUEST_TEMPLATE.md
nf_core/pipeline-template/.github/workflows/awsfulltest.yml
nf_core/pipeline-template/.github/workflows/awstest.yml
nf_core/pipeline-template/.github/workflows/ci.yml
nf_core/pipeline-template/README.md
nf_core/pipeline-template/conf/modules.config
nf_core/pipeline-template/conf/test.config
nf_core/pipeline-template/conf/test_full.config
nf_core/pipeline-template/docs/usage.md
nf_core/pipeline-template/nextflow.config
nf_core/pipeline-template/nextflow_schema.json
nf_core/pipeline-template/workflows/pipeline.nf

Make `outdir` a mandatory parameter. Closes #1415

Make outdir a mandatory parameter

---

CHANGELOG.md
nf_core/__main__.py
nf_core/schema.py
requirements.txt
tests/test_schema.py

Per discussion in [Slack](https://nfcore.slack.com/archives/CUC8PPDL2/p1641920634004300) and partially addressing #741, I added a `nf-core schema docs` command which takes any nextflow_schema.json and generates Markdown documentation for it. 
A fully reproducible and state-of-the-art ancient DNA analysis pipeline
Define where the pipeline should find input data, and additional metadata.
|Parameter|Description|Type|Default|Required|Hidden
|-----------|-----------|-----------|-----------|-----------|-----------
|`input`|Either paths or URLs to FASTQ/BAM data (must be surrounded with quotes). For paired end data, the path must use '{1,2}' notation to specify read pairs. Alternatively, a path to a TSV file (ending .tsv) containing file paths and sequencing/sample metadata. Allows for merging …

Output schema documentation as Markdown

---

nf_core/pipeline-template/bin/check_samplesheet.py

With this PR I propose to make the following changes as briefly mentioned on Slack.
* `csv.Sniffer` should allow most tabular inputs but writes CSV as nf-core pipelines expect
* refactor validations into checker class
* relax accepted sequence file formats, as mentioned, this is easily changed by modifying
```py
VALID_FORMATS = (
".fq",
".fastq",
".fq.gz",
".fastq.gz",
)
```
in the `RowChecker` class. I like uncompressed formats for local pipelines with many small steps where de-/compression takes up the majority of time.
I will adjust documentation and tests when you have told me exactly what the desired behavior is.

refactor: enhance sample checking script

---

CHANGELOG.md
nf_core/modules/lint/main_nf.py

Prevent module linting KeyError edge case.

---

CHANGELOG.md
README.md
nf_core/__main__.py
nf_core/modules/module_utils.py

Since we now have a nice interactive prompt if the `repository_type` is not found in the `.nf-core.yml` config file (#1437), I figure a flag to override the repo type is not really needed and will just cause more problems if anything.
So best way of closing #1433 is to just strip `--repo-type` entirely.

Remove flag --repo-type

---

CHANGELOG.md
nf_core/modules/lint/module_tests.py
nf_core/modules/test_yml_builder.py

- Error instead of warning for md5s of empty files
- Don't skip adding the md5 to the test YAML if an empty file is found
⚠️ UNTESTED ⚠️  - would be fab if someone else could give this a spin and check that it works as intended 🙏🏻 
Fixes #1376

Tweak handling of empty files when generating the test YAML

---

CHANGELOG.md
nf_core/lint/pipeline_todos.py
nf_core/modules/lint/module_todos.py

Linting checks test files for `TODO` statements as well as the main module code

---

CHANGELOG.md
nf_core/list.py

Handle exception in `nf-core list` when a broken git repo is found

---

CHANGELOG.md
nf_core/modules/module_utils.py

Don't assume manifest will be set in the nextflow config.

---

CHANGELOG.md
nf_core/create.py

When we do a pipeline sync, many pipelines try to fetch logos at the same time. In previous syncs this has taken the website down and then a load of template syncs fail.
Also sometimes the website just borks for some other reason.
This PR adds code to check that the response from the website was sane:
- Catches raised `ConnectionError` errors from timeouts etc
- Pushes the default timeout period way up, to 3 minutes
- Checks to see if the website returned a HTML `200` code (all is well)
- After it saves the file, check that it looks like a PNG file
- If any of the above go wrong, try again
- Wait a random number of seconds for each attempt, increasing the duration for each wait
- Random number tries to un-synchronise the hits to the website during a release of tools
Hopefully fixes #1369 …

Updated `nf-core create` to tolerate failures and retry when fetching pipeline logos from the website

---

CHANGELOG.md
nf_core/lint/__init__.py

When you run pipeline linting you can ctrl+click the test name and it takes you to the website. This updates to the newer URL format and also pins the version of tools that you're currently running.
Fixes #1348

Updated URL for pipeline lint test docs

---

CHANGELOG.md
nf_core/gitpod/gitpod.Dockerfile

As discussed on Slack copy the repo content in the Docker image and avoid the installation of tools from conda

Install tools in the GitPod Docker from the repo itself

---

CHANGELOG.md
docs/api/_src/_static/css/custom.css

In order to address #1294, I have slightly modified the secondary colors of the light theme and added a few additional CSS selectors to ensure that there are no elements (like the hyperlinks) without associated styles. Those are styled with the default colors from the user's desktop theme and thus might play well with the theme.

Issue1294: Fixes to colors in Sphinx theme

---

nf_core/pipeline-template/bin/check_samplesheet.py

Noticed that when there are more dots in the FASTQ file name, the Path(file).suffixes returns all elements split by dot, which ends in list mismatch, therefore throwing an error. I think we should limit it to the last two items (according to VALID_FORMATS) for the extension check. Hope this PR helps to solve the problem.

Fix: Get file extensions correctly in validate_pair

---

CHANGELOG.md
nf_core/modules/modules_command.py

After updating a module or installing it and dumping the `modules.json` the last line of the file was lost and prettier complained. This is something already reported for JSON python dump, see [here](https://codeyarns.com/tech/2017-02-22-python-json-dump-misses-last-newline.html). This PR should fix it.

Add a last newline to modules.json to avoid prettier error

---

CHANGELOG.md
nf_core/pipeline-template/.github/workflows/awsfulltest.yml
nf_core/pipeline-template/.github/workflows/awstest.yml

Tower.nf is now running Nextflow 22.03.0.edge by default, which includes a new strategy to handle retrying jobs killed due to AWS spot policies. This was the reason for these lines of config, so they can now be removed.

Remove nextflow_config from AWS test CI

---

CHANGELOG.md
nf_core/launch.py
nf_core/modules/module_utils.py
nf_core/schema.py

Following @ewels comment on https://github.com/nf-core/tools/pull/1501, all the problematic instances where a `JSON` file was created without a last line were fix (prettier errors otherwise)
Files fixed are:
- `modules.json` (when file is created when `nf-core lint` identifies that is missing)
- `params.json` (`nf-core launch`)
- `nextflow-schema.json` (`nf-core schema build`)

Add last line to json files

---

CHANGELOG.md
nf_core/pipeline-template/.prettierignore

Direct copy of .gitignore.
Hopefully can get rid of this file again one day, see https://github.com/prettier/prettier/issues/4708
Fixes https://github.com/nf-core/tools/issues/1504

Add .prettierignore file

---

CHANGELOG.md
nf_core/modules/test_yml_builder.py

Escaped test run output before logging it, to avoid a rich `MarkupError`

---

nf_core/pipeline-template/.github/workflows/branch.yml
nf_core/pipeline-template/.github/workflows/ci.yml
nf_core/pipeline-template/.github/workflows/linting.yml
nf_core/pipeline-template/.github/workflows/linting_comment.yml

Reported by @d4straub - in https://github.com/nf-core/ampliseq/pull/417 the `branch.yml` workflow is complaining that the PR is against `master`. It is a valid PR against `master` so the bash logic is broken, presumably from [this change](https://github.com/nf-core/ampliseq/pull/413/files#diff-a1d832efe16369fb6549ffea0b71cfaf8da1bf641ff6be470ad40d2303f45577) in the workflow where I added quotes in the template.
Additionally, the floating `#` markers that have appeared at the end of the workflow files have confused a lot of people. @Emiller88 tried to address these in https://github.com/nf-core/tools/pull/1500 but here I have an alternative fix, where I just move the `{% endraw %}` statements off comment lines and on to the tail of the last statement to get rid of floating comment marker. …

GH Actions workflow YAML tweaks.

---

.prettierignore
CHANGELOG.md
nf_core/pipeline-template/.prettierignore
nf_core/pipeline-template/assets/email_template.html

Revert email template prettier

---

CHANGELOG.md
nf_core/lint/nextflow_config.py
nf_core/pipeline-template/nextflow.config

The current default DAG image format SVG requires Graphviz. Using the HTML version removes the Graphviz dependency.
It is now common to see the Warning about the missing Graphviz dependency when running nf-core pipelines. In my limited experience it is often the only warning and often not a very useful at that because the DAG is not a main product of the pipeline in most use cases.
To have the DAG image output as HTML should be fine, since most computers who can display a PNG will also have a browser that can render a HTML file.
Because the Graphviz dependency is on the host system rather than in a container, this means the hassle of installation is left with the user. A big part of Nextflow/nf-core is that it abstracts installations away from users. I consider the Graphviz dependency a …

Remove the graphviz dependency from nf-core

---

.github/workflows/create-lint-wf.yml
.github/workflows/create-test-wf.yml
.github/workflows/deploy-pypi.yml
.github/workflows/fix-linting.yml
.github/workflows/pytest.yml
.github/workflows/sync.yml
.github/workflows/tools-api-docs-dev.yml
.github/workflows/tools-api-docs-release.yml
CHANGELOG.md
nf_core/pipeline-template/.github/workflows/fix-linting.yml
nf_core/pipeline-template/.github/workflows/linting.yml

Add ability to use `@nf-core-bot fix linting` within PR comments. Both for the main nf-core/tools repo and also in the template.
The nf-core/tools action also runs Black as well as Prettier.
Also updated the setup-python action to v3 from v1.

Add fix-linting workflows

---

CHANGELOG.md
nf_core/lint/files_exist.py
nf_core/lint/files_unchanged.py

Disallow `.yaml` file extension for the nf-core config file. We definitely don't want two versions of this file, and the template has `.yml`.

Don't allow a .nf-core.yaml file (should be .yml)

---

CHANGELOG.md
nf_core/lint/nextflow_config.py

https://github.com/nf-core/tools/pull/1512 introduced code to allow all nf-core supported DAG graph formats in the default linting. This was not desired and thus removed in this PR.

revert to single dag.file file format for linting

---

CHANGELOG.md
nf_core/modules/test_yml_builder.py

Remove md5sum for `versions.yml` file when using `create_test_yml`

Remove md5sum for versions.yml file

---

.editorconfig
CHANGELOG.md
nf_core/__main__.py
nf_core/modules/__init__.py
nf_core/modules/mulled.py
requirements.txt
tests/test_mullled.py

Add a command `nf-core modules mulled` that can generate image names from given tool specifications. See the discussion at https://nfcore.slack.com/archives/C01LNCGJBMH/p1649431242727599

feat: add a modules mulled command

---

CHANGELOG.md
nf_core/modules/install.py

Closes #1420
When using `nf-core modules install` print the include statements to terminal for easy copy to destination files.

Print include statement when modules install

---

nf_core/lint/actions_ci.py

In cases where e.g. multiple aligners are specified in the GitHub Actions matrix, trying to pull a 'NXF_VER' key out of the include dictionary can cause line 140 of `actions_ci.py` to fail when it shouldn't. The `get()` method will not error if the key is not present, fixing this problem.

Tweak to actions_ci.py

---

CHANGELOG.md
nf_core/__main__.py
nf_core/modules/__init__.py
nf_core/modules/module_test.py
pytest.ini
tests/modules/module_test.py
tests/test_modules.py

Closes #1276
Add a new command `nf-core modules test` to run module tests locally.

add new command modules test

---

nf_core/launch.py

The weird dash (8211, Unicode "EN DASH") means the command will not work if one manually copy-pastes that bit from the log into the command. This kind of dash does not get interpreted flag starter but a string.
* I don't think this warrants an entry in the CHANGELOG.md (It's a weird bug, that's not even a bug in the code that gets executed.)
* I don't think this tests are required for this change
* I don't think additional `docs` are required.

replace a weird with a normal dash

---

CHANGELOG.md
nf_core/schema.py

Not all definitions in JSON schema have a "properties", leading to an error

---

nf_core/modules/test_yml_builder.py

Closes #1547 
The command output when running the test is a byte object. Decode it to string to allow the formatting with rich.

Decode bytes-like object for logging

---

nf_core/modules/lint/main_nf.py

Replace commands using complex split() expressions with regular expressions, as mentioned in [#1374 comment](https://github.com/nf-core/tools/pull/1374#discussion_r771317580) and [#1542 comment](https://github.com/nf-core/tools/issues/1542#issuecomment-1118770105)

Replace complex split() by regex

---

CHANGELOG.md
nf_core/module-template/tests/test.yml
nf_core/modules/test_yml_builder.py

Make module template and `test_yml_builder` default commands match.

---

CHANGELOG.md
nf_core/modules/test_yml_builder.py

Closes #1564 
When output files are inside a folder (e.g. index files from bowtie2/align module), `os.walk()` needs the parameter `followlinks=True` when creating the test.yml file to be able to retrieve all files.

fix missing output files in test.yaml

---

CHANGELOG.md
nf_core/modules/lint/main_nf.py

No more split, regexes FTW!
Fixes nf-core/tools#1542

Module linting: refactor parsing of input channel names.

---

nf_core/__main__.py
nf_core/modules/mulled.py

Mulled: handle invalid versions with a nice error message instead of a traceback

---

nf_core/__main__.py
nf_core/modules/mulled.py

* Don't print the mulled hash if the container doesn't exist
* Don't debug log the entire page contents, just the URL
* Bit more rich logging, including with a console hyperlink to the quay.io page

Mulled: Nicer CLI output

---

CHANGELOG.md
nf_core/lint/__init__.py
nf_core/modules/lint/__init__.py

Tweaks to the linting output for modules, fixing some minor things that have bugged me for a while:
* Drop header row for pipeline / modules (include this in the header)
* Better grouping of linting results + section (less visual noise)
* Use `dim` instead of `magenta` to differentiate table rows
* Use panels for grouping instead of tables
Old, module:
New, module:
Old, pipeline:
New, pipeline:

Module lint styling

---

nf_core/modules/lint/main_nf.py
nf_core/modules/lint/meta_yml.py

In https://github.com/nf-core/tools/pull/1374 @drpatelh updated linting to allow `input` and `output` to be omitted from `main.nf`. However, the linting was still checking for these in `meta.yml`.
Also added in some slight lint message tweaks to help clarify things.

Module lint: Allow no input or output in YAML

---

nf_core/gitpod/gitpod.Dockerfile

Update Gitpod image
- update nextflow version 21.10.6 -> 22.04.0
- update mamba version 0.22.1 -> 0.23.1
- remove `nextflow self-update` as it defeats the purpose of versioning.

Update gitpod image

---

nf_core/list.py
nf_core/modules/list.py
tests/test_list.py

The tests for list left a remnant folder in `/tmp/` named `nxf` which I believe to be an undesired behaviour. 
I also took the opportunity to use pathlib.Path, isort and simplify some of the code in `list.py` (and make it marginally faster).
Closes #1565

Make temporary folders temporary

---

CHANGELOG.md
nf_core/lint/readme.py

Close #1589
Remove color label in Nextflow image from readme linting to fix "readme: README did not have a Nextflow minimum version badge." warning.

remove color label in Nextflow image from readme linting

---

tests/lint/actions_schema_validation.py
tests/test_lint.py

The linting test were broken because they introduce new properties to the schema, but some external change makes the additional properties fail now. 
This PR skips the generation of new properties and the tests now exclusively test for the lack of required properties.
The answer to the above question will decide if the additional test for failure upon additional parameter will be merged or if it should be dropped.
Key words: additionalProperties, jsonschema

fix-broken-linting-tests

---

CHANGELOG.md
nf_core/lint/files_exist.py
nf_core/lint/files_unchanged.py

Check that the `.prettierignore` file exists and that starts with the same content.

Lint for `.prettierignore` 

---

CHANGELOG.md
nf_core/__main__.py
nf_core/modules/lint/__init__.py
nf_core/modules/lint/main_nf.py
nf_core/modules/update.py

Related to #1434 
Add the --fix argument to linting of modules. 
If --fix flag is provided, the module is updated to the latest version.

Add option to update modules with linting

---

tests/test_download.py
tests/test_list.py
tests/test_schema.py
tests/test_utils.py

pytest.mark.xfail was used to test if the code raises certain exceptions in certain cases. This PR moves uses pytest.raises instead, which is the pytest way to test if code raises exceptions when desired.

use pytest.raises to test for raised exception

---

nf_core/modules/lint/main_nf.py

Modules linting is failing when the regex parsing the inputs is unable to find a match.
Example: https://github.com/nf-core/modules/runs/6813009605?check_suite_focus=true
Module artic/minin has these two input lines
```
path  ("primer-schemes/${scheme}/V${scheme_version}/${scheme}.reference.fasta")
path  ("primer-schemes/${scheme}/V${scheme_version}/${scheme}.scheme.bed")
```
The regular expression parsing the inputs `r"\((\w+)\)"` doesn't match those.

Check regex match during modules linting

---

CHANGELOG.md
nf_core/download.py
tests/test_download.py

There has been a test that xfailed -  It seems that failing to retrieve a container image should have always raised an exception, but it didn't. Now it does and the test that was maked xfail is now split into two tests, one that tests the failure mode if Singularity isn't installed and one for the case Singularity is installed but the container image retrieval fails.

raise if Singularity container retrieval fails

---

nf_core/schema.py

It was not clear to a developer what the following message actually meant:
```
schema_params: Default value for param bgc_antismash_database invalid: Not in pipeline parameters
```
i.e. whether pipeline parameters referred to parameters being passed on the CLI or not. However when I looked at the code, my understanding is this comes up when there is a parameter listed in the schema, but is not detected in the resolved parameters, namely: `nextflow.config`.
To make it clearer for people to know where to possibly look, I add a sentence to check `nextflow.config`.

Clarify error message when parameter in schema not present in nextflow.config

---

CHANGELOG.md
nf_core/utils.py

The base cache directory was changed in a previous PR be to `$XDG_CONFIG_DIR` or `.config`. In my opinion it makes more sense to use [`$XDG_CACHE_DIR`](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) or `.cache`.

Change base cache dir

---

.github/workflows/create-lint-wf.yml
.github/workflows/create-test-wf.yml
.github/workflows/pytest.yml
.github/workflows/sync.yml
CHANGELOG.md
nf_core/bump_version.py
nf_core/lint/actions_ci.py
nf_core/pipeline-template/.github/workflows/ci.yml
nf_core/pipeline-template/.github/workflows/linting.yml
tests/test_bump_version.py

Switches the workflows in this repo and the template to point to use [setup-nextflow](https://github.com/MillironX/setup-nextflow), rather than try to manually install Nextflow in a `run:` block. This allows for simplifying the execution matrix, and removes the need to keep track of whether a stable or edge release is actually the most recent.
- [na] If you've fixed a bug or added code that should be tested, add tests!
- [na] Documentation in `docs` is updated

Switch CI to nf-core/setup-nextflow action

---

CHANGELOG.md
README.md

Added example of how to use the `--git-remote` option to specify a custom remote. Will close #1645.

Update docs with custom URL example

---

CHANGELOG.md
nf_core/modules/info.py

`nf-core modules info` was failing with a cryptic error message if no tool name was provided. This fixes this by prompting the user if no module name is provided. In addition, I've updated the logic to work better with custom remotes. Will close #1644

Add prompt to `nf-core modules info` if no module name is provided

---

CHANGELOG.md
nf_core/lint/readme.py

Fixing https://github.com/nf-core/tools/issues/1613
Update the regexp to accept any characters except numbers, dot and dash before number version.

Fix Issue #1613

---

CHANGELOG.md
nf_core/modules/module_test.py
nf_core/modules/modules_command.py
nf_core/utils.py
tests/modules/module_test.py
tests/test_modules.py

Close #1615 
When `nf-core modules test` is run without specifying a module name, the suggestions from the prompt are obtained from the installed modules (instead of nf-core/modules repository).

obtain module suggestions from installed modules

---

nf_core/modules/lint/main_nf.py

Small change in a regular expression to allow both, single and double quotes, in container links from modules.
For example, trying to update module bowtie2/align was giving an error due to [links quoted by double quotes](https://github.com/nf-core/modules/blob/master/modules/bowtie2/align/main.nf#:~:text=%22https%3A//depot.galaxyproject.org/singularity/mulled%2Dv2%2Dac74a7f02cebcfcc07d8e8d1d750af9c83b4d45a%3A1744f68fe955578c63054b55309e05b41c37a80d%2D0%22%20%3A).

allow single and double quotes when matching container links

---

CHANGELOG.md
nf_core/lint/modules_json.py
nf_core/modules/install.py
nf_core/modules/lint/__init__.py
nf_core/modules/list.py
nf_core/modules/modules_command.py
nf_core/modules/modules_json.py
nf_core/modules/remove.py
nf_core/modules/update.py
tests/modules/modules_json.py

Renamed methods names in `ModulesJson` to not explicitly reference `modules.json`. This should have been done in #1655.

Rename methods in `ModulesJson`

---

nf_core/pipeline-template/conf/base.config

Follow-up of #1630 . For single-core tasks, there is no need to increase the number of cores at each attempt

Single-core tasks shouldn't request more than 1 core

---

CHANGELOG.md
nf_core/lint/schema_lint.py
nf_core/schema.py

Check that the `input` parameter has a mimetype. Should close #1647.

Add lint for input mimetype

---

CHANGELOG.md
nf_core/lint/__init__.py

When running `nf-core module --key <module-test>` all pipeline lint tests were run in addition to the supplied module test (#1681). With this PR only the tests specified by the `--key` option are run

Fix `--key` flag for `nf-core lint` for module lint tests

---

CHANGELOG.md
nf_core/__main__.py
nf_core/download.py
nf_core/lint/__init__.py
nf_core/modules/lint/__init__.py
nf_core/modules/lint/main_nf.py
nf_core/utils.py

Added lint test to check that the container names in modules are parsable, as was suggested in #1654. To have the possibility of making the warned module lint test more prominent, I also added a `--fail-warned` flag. This flag is *not* activated when `nf-core lint` is run with its `--fail-warned` flag, since this will make the "Create and lint pipeline" GH action fail. (An idea on how to solve this is suggested in #1684)

Lint for container names

---

CHANGELOG.md
nf_core/modules/modules_json.py

Fixed bug in `ModulesJson.check_up_to_date` causing local modules to not be filtered out when looking for the remote of untracked files.

Fix bug in ModulesJson

---

CHANGELOG.md
requirements-dev.txt
tests/test_cli.py
tests/test_download.py
tests/test_launch.py
tests/test_lint.py
tests/test_list.py
tests/test_schema.py
tests/test_sync.py
tests/test_utils.py

The mock package is now part of the standard library of Python integrated into unittest. The mock package itself is not (regularly) updated any more. See https://pypi.org/project/mock/ (the latest release as of writing has been in 2020).

remove dependency on package mock

---

nf_core/pipeline-template/conf/test.config
nf_core/pipeline-template/conf/test_full.config
nf_core/pipeline-template/lib/WorkflowMain.groovy

When creating a template without igenomes, a reference file has to be given with the `--fasta` parameter for the test pipeline to run.
Here we add the parameter to the example command from help message and also a reference fasta file to test.config and test_full.config
Closes [#1679](https://github.com/nf-core/tools/issues/1679)

add --fasta parameter to command when igenomes is not used

---

CHANGELOG.md
nf_core/modules/modules_differ.py
nf_core/modules/update.py

As I reported in #1694, `nf-core modules update --save-file` simply ignored files that were created or removed between updates. I've fixed this by letting the output `.diff` file be more similar to the output from `git diff`: 
- Created or removed files are shown to originate from/end up in `/dev/null`
- "from" and "to" file paths are prefixed with `a/` and `b/` respectively. 
I've moved the diff methods in `update` to a separate static class to make the update code a bit cleaner also

Make `nf-core modules update --save-diff` work when files are created or removed

---

CHANGELOG.md
nf_core/utils.py

Closes [#1656](https://github.com/nf-core/tools/issues/1656)
When obtaining Docker and Singularity containers from a bioconda package and version, get the latest common build for both containers.

retrieve last common build of a module for Docker and Singularity

---

nf_core/__main__.py
nf_core/bump_version.py
nf_core/launch.py
nf_core/licences.py
nf_core/lint/actions_schema_validation.py
nf_core/lint/modules_json.py
nf_core/lint/schema_description.py
nf_core/lint/schema_lint.py
nf_core/modules/bump_versions.py
nf_core/modules/info.py
nf_core/modules/lint/main_nf.py
nf_core/modules/lint/meta_yml.py
nf_core/modules/lint/module_changes.py
nf_core/modules/lint/module_version.py
nf_core/refgenie.py
tests/lint/files_exist.py
tests/lint/files_unchanged.py
tests/lint/merge_markers.py
tests/lint/modules_json.py
tests/lint/nextflow_config.py
tests/modules/lint.py
tests/test_cli.py
tests/test_launch.py
tests/test_licenses.py
tests/test_lint.py
tests/test_refgenie.py
tests/test_schema.py

Mostly removal of unused imports, with two minor off-topic additions: 1. cleanup of imports in refgenie and 2. replacement of deprecated calls to log.warn.

Remove unused imports

---

CHANGELOG.md
nf_core/create.py

Closes #1688 
If Git `defaultBranch` is set to `dev` or `TEMPLATE` nf-core commands that create a new pipeline repository fail with nice error message and the pipeline git repository is not initialised.

Git default branch

---

CHANGELOG.md
nf_core/lint/files_unchanged.py
tests/test_bump_version.py
tests/test_download.py
tests/test_launch.py
tests/test_modules.py
tests/test_utils.py

As mentioned in [#1688 comment](https://github.com/nf-core/tools/issues/1688#issuecomment-1197912918)
> I think in the case of nf-core lint you could actually pass no_git=True to PipelineCreate here, and skip making a git repository entirely, as the linter does not seem to require a git repository to compare the template files 
The argument no_git=True can be added when a pipeline is created but there's no need to initialise a git repository.

Add no_git=True when possible

---

CHANGELOG.md
docs/api/_src/api/lint.md
nf_core/lint/__init__.py
nf_core/utils.py
tests/test_lint.py
tests/test_utils.py

This is a utility function not necessarily specific to linting.
A minor issue was also the setup of the re.compile within the function. This would compile the regex every time the function is called, now it is only computed once upon import of utils.

provide ansi code stripping from utils

---

nf_core/modules/info.py

Closes #1719 
Adding missing argument `base_path` to ModuleInfo init method.
Part of implementation of git remotes in #1641 (Issue #1626 )

add base_path to ModuleInfo init method

---

CHANGELOG.md
nf_core/lint/modules_json.py
nf_core/modules/info.py
nf_core/modules/install.py
nf_core/modules/lint/__init__.py
nf_core/modules/list.py
nf_core/modules/module_test.py
nf_core/modules/modules_command.py
nf_core/modules/modules_json.py
nf_core/modules/patch.py
nf_core/modules/remove.py
nf_core/modules/update.py
tests/modules/module_test.py

As @awgymer reported in #1721, several of the `nf-core modules` commands depended on that git remotes had the same format as in GitHub, i.e. `owner/repo`. This meant that the commands failed when repo names of greater nesting were used, for example `group/subgroup/repo`.  
I've fixed this by letting the `modules.json` file be the only source of information for what modules are installed in a pipeline -- the commands should not need to interact with the directory structure directly.

Make `nf-core modules` commands work with arbitrary git remotes

---

CHANGELOG.md
README.md
nf_core/modules/modules_json.py
nf_core/modules/modules_repo.py

As reported in #1726, `--branch` and `--base-path` are a bit buggy. In this issue I've corrected the following behaviour:
- If new branches were created in an already cloned remote repo, `setup_branch` is unable to find the new branch. Therefore run git fetch in before trying to check out a branch. 
- Fix bug in `ModulesJson.remove_entry` causing empty repo entries to not be removed.
- Updated the `README.md` to better explain what `--base-path` can and can't do.
This is a continuation from #1724, so merge that one first.

Fix issues related to `--branch` and `--base-path`

---

CHANGELOG.md
nf_core/pipeline-template/README.md
nf_core/pipeline-template/docs/usage.md

`console` snippets are in general only nice to display terminal outputs, not anything related to scripts or commands.

convert `console` snippets to `bash` snippets in the template

---

CHANGELOG.md
README.md

Add links for `nf-core modules info` and `nf-core modules patch` commands documentation in `README.md`. Should close #1722.

Add links for `nf-core modules info` and `nf-core modules patch` commands documentation in `README.md`

---

CHANGELOG.md
nf_core/__main__.py
nf_core/lint/modules_json.py
nf_core/modules/list.py
nf_core/modules/modules_json.py
nf_core/modules/modules_repo.py
nf_core/modules/patch.py
nf_core/modules/update.py
nf_core/pipeline-template/modules.json
nf_core/utils.py
tests/modules/install.py
tests/modules/modules_json.py
tests/modules/update.py
tests/test_modules.py
tests/utils.py

As I reported in #1728, the commands that rely on version information in the `modules.json` fail if a module was installed from a branch other than the default branch. I've fixed this by adding branch information to the module entries in the `modules.json`. The updated `modules.json` looks something like this
```yaml
{
"name": "a/pipeline",
"homePage": "https://a-pipeline.com",
"repos": {
"some/cool/repo": {
"base_path": "modules",
"git_url": "https://git-provider.com/some/cool/repo.git",
"modules": {
"first-modules": {
"git_sha": "<some sha>",
"branch": "main"
},
"second/module": {
"git_sha": "<another sha>",
"branch": "other-branch"
}
}
}
}
}
```
To add this feature I needed to refactor the `check_up_to_date` method in `modules_json.py` since it was to big and unruly to be modified …

Add `branch` field to module entries in `modules.json` to record what branch a module comes from

---

CHANGELOG.md
nf_core/modules/update.py

There were some undefined behaviour in  `update.py` in a recently merged pull request as @fabianegli pointed out in https://github.com/nf-core/tools/pull/1738#discussion_r938898766. This fixes the issues mentioned there. I also took the opportunity to remove the `DiffEnum` class `update.py` which is not used any more.

Fix undefined behaviour in `update.py`

---

CHANGELOG.md
nf_core/modules/lint/main_nf.py

Closes #1733 
If the module process name doesn't start by `process_`, extract the process name and raise a linting warning. 
This PR also modifies the way of determining if the line contains the process name as suggested by @awgymer

Handle exception in `nf-core modules lint` when process name doesn't start with process

---

CHANGELOG.md
nf_core/utils.py

`distutils` Version classes are deprecated in favor of the ones in `packaging`.

use packaging instead of deprecated distutils Version classes

---

nf_core/__main__.py
nf_core/download.py
nf_core/launch.py
nf_core/licences.py
nf_core/lint/__init__.py
nf_core/lint/actions_schema_validation.py
nf_core/lint/modules_json.py
nf_core/lint/multiqc_config.py
nf_core/list.py
nf_core/modules/bump_versions.py
nf_core/modules/lint/main_nf.py
nf_core/modules/lint/module_patch.py
nf_core/modules/lint/module_tests.py
nf_core/modules/lint/module_version.py
nf_core/modules/modules_json.py
nf_core/modules/modules_repo.py
nf_core/modules/remove.py
nf_core/modules/test_yml_builder.py
nf_core/modules/update.py
nf_core/refgenie.py
nf_core/schema.py
nf_core/sync.py
nf_core/utils.py

A couple of minor code changes - mostly maintenance but also fixes one function call that had too many arguments.

Code maintenance

---

nf_core/utils.py

The `yaml.Dumper.increase_indent()` function only has the two arguments `flow` and `indentless`. There's no need for the `*args` and `**kwargs`.

[MAINT] fix argument order

---

nf_core/download.py
nf_core/lint/__init__.py
nf_core/modules/modules_json.py
nf_core/modules/modules_repo.py
nf_core/sync.py
tests/test_sync.py

This PR removes a now unnecessary hashlib import and come code in the tests that has no function.
Here's a link to the issue decribing the pylint inability in the case of `git.exc`: https://stackoverflow.com/questions/55244396/weird-errors-with-pylint-and-git-exc

fix a pylint issue caused by glob imports in `git.exc` and remove unused code

---

CHANGELOG.md
nf_core/modules/info.py

Close #1736 
Don't add the prefix `https://github.com` to the link created by nf-core modules info. Make the link clickable if `self.remote_location` starts by 'http'
The command was also failing when there wasn't any module installed from a remote repository. I added the attribute `self.local` to ensure that we only try to obtain information from a local module if it is locally installed.

Fix broken link in `nf-core modules info`

---

nf_core/modules/update.py

At least I guess they should not be there.

remove print statements from debugging 

---

CHANGELOG.md
nf_core/modules/modules_json.py
tests/modules/modules_json.py
tests/test_modules.py

Closes #1723 
When creating `modules.json` file, if a patch file exists for a module, apply the patch in reverse to find the commit_sha.

add apply patch reverse when create modules.json

---

CHANGELOG.md
README.md
nf_core/__main__.py
nf_core/modules/bump_versions.py
nf_core/modules/info.py
nf_core/modules/install.py
nf_core/modules/lint/__init__.py
nf_core/modules/list.py
nf_core/modules/modules_command.py
nf_core/modules/modules_json.py
nf_core/modules/modules_repo.py
nf_core/modules/patch.py
nf_core/modules/update.py
nf_core/pipeline-template/modules.json
tests/modules/modules_json.py
tests/test_modules.py

As discussed in #1732 
Remove --base-path option.

Remove --base-path option

---

requirements-dev.txt

MyST Parser is required for the docs generation.

Add MyST-Parser requirement for docs generation

---

nf_core/modules/lint/module_changes.py

Closes #1748 
The `dirs_exist_ok` is not available in the still supported Python 3.7 and it is also not necessary because a tree is copied into a newly created temporary folder.
This code is not tested. Tests are needed, hence the marking as WIP.

remove unnecessary dirs_exist_ok argument

---

nf_core/modules/lint/module_changes.py
tests/modules/lint.py
tests/test_modules.py

Fix issue introduced by https://github.com/nf-core/tools/pull/1755
Not sure what to write in the changelog.

workaround for shutil.copytree's lack of dirs_exist_ok in Python3.7 + added tests for module patch

---

nf_core/__main__.py
tests/lint/version_consistency.py
tests/modules/module_test.py
tests/test_launch.py
tests/test_modules.py
tests/test_schema.py

I find replacing builtin functions intransparent and hence propose to make the use of rich.print obvious.

transparently use the print function from rich

---

.github/workflows/tools-api-docs-dev.yml
.github/workflows/tools-api-docs-release.yml

GitHub Actions  seems to be deprecating Ubuntu 18.04 and thus some of the tests start failing. This PR makes it so ubuntu-latest is used in all workflows as the base image that until now use Ubuntu 18.04.
The issue surfaced because [this](https://github.com/fabianegli/tools/runs/7951535033?check_suite_focus=true) PR test failed.

use ubuntu-latest for api docs generatoin and release

---

.github/workflows/rich-codex.yml
README.md

This runs the rich-codex action only after an approved review (or when manually kicked-off).
Another solution for #1775.

change-rich-codex-run-condition

---

nf_core/pipeline-template/pyproject.toml

If we want to have consistent Python formatting in the nf-core ecosystem, isort should be part of that.

use nf-core tools isort settings in pipeline template

---

CHANGELOG.md
nf_core/lint/files_exist.py
nf_core/lint/files_unchanged.py

`nf-core lint` will WARN if file `pyproject.toml` doesn't exist. 
The file must contain the same lines as the template, and more lines can be added.

lint pyproject.toml file exists and content

---

nf_core/pipeline-template/bin/check_samplesheet.py

Fixes https://nfcore.slack.com/archives/CE5LG7WMB/p1661868498109569
This PR prevents the need for a `pyproject.toml` file in the pipeline template.

be compliant with black defaults in the pipeline template

---

CHANGELOG.md
nf_core/pipeline-template/lib/Utils.groovy

generalized code, better error message and link update

---

CHANGELOG.md
tests/modules/lint.py
tests/modules/module_test.py
tests/test_test_utils.py
tests/utils.py

Using contexts is safer because this way the working directory reset happens even if something unexpected happens between setting and resetting the working directory.

Use a context to temporarily change the working directory

---

CHANGELOG.md
nf_core/schema.py

Fixing bug reported by @robsyme [on Slack](https://nfcore.slack.com/archives/CE5LG7WMB/p1664200940775769).
```console
$ nf-core schema build
,--./,-.
`._,._,'
nf-core/tools version 2.5.1 - https://nf-co.re/
ERROR    Could not find pipeline schema for '.':                       schema.py:73
./nextflow_schema.json                                                    
INFO     No existing schema found - creating a new one from the       schema.py:568
nf-core template                                                          
WARNING  Removing empty group: 'input_output_options'                 schema.py:662
WARNING  Removing empty group: …
```

Schema: Remove `allOf` if no definition groups are left.

---

CHANGELOG.md
nf_core/download.py

More helpful error messages if `nf-core download` can't parse a singularity image download
Before:
```
ERROR    Cannot parse container string, skipping: 'main.nf'      
```
After:
```
ERROR    Cannot parse container string in 'nf-core-sarek-3.0.2/workflow/modules/nf-core/modules/deepvariant/main.nf':
${ workflow.containerEngine == 'singularity' && !task.ext.singularity_pull_docker_container ?
'google/deepvariant:1.3.0' :
'google/deepvariant:1.3.0' }
⚠ Skipping this singularity image..
```

Better download logging when errors with container

---

CHANGELOG.md
nf_core/lint/files_exist.py

Check that the old renamed `lib` files are not still present:
- `Checks.groovy` -> `Utils.groovy`
- `Completion.groovy` -> `NfcoreTemplate.groovy`
- `Workflow.groovy` -> `WorkflowMain.groovy`
See also: nf-core/methylseq#246

Check that the old renamed `lib` files are not still present

---

CHANGELOG.md
nf_core/gitpod/gitpod.Dockerfile

We had the vscode extensions there, but not prettier as a requirement in the container

Add prettier to dockerimage for gitpod

---

CHANGELOG.md
nf_core/modules/modules_repo.py

It's kind of amazingly difficult to intentionally corrupt a git repo to test this. But I think it should work.
Closes nf-core/tools#1850

Modules: If something is wrong with the local repo cache, offer to delete it and try again

---

CHANGELOG.md
nf_core/pipeline-template/workflows/pipeline.nf

I've tested creating a template from `nf-core/tools` `dev` and running it and the MultiQC execution didn't work, the MultiQC process was just not executed. This should introduce a fix for it.
I'm also puzzled why then the test `Create a pipeline and test it` worked, as there was also another issue with a variable name

Fix multiqc in template

---

CHANGELOG.md
nf_core/pipeline-template/nextflow.config

Jinja templating was a little too aggressive when skipping nf-core/configs.

Don't skip `base.config` when skipping nf-core/configs

---

docs/api/_src/module_lint_tests/module_changes.md
docs/api/_src/module_lint_tests/module_patch.md
docs/api/_src/module_lint_tests/module_tests.md
docs/api/_src/module_lint_tests/module_version.md
docs/api/_src/pipeline_lint_tests/modules_structure.md
nf_core/__main__.py
nf_core/lint/__init__.py
nf_core/lint/modules_structure.py
nf_core/modules/bump_versions.py
nf_core/modules/create.py
nf_core/modules/info.py
nf_core/modules/install.py
nf_core/modules/list.py
nf_core/modules/module_test.py
nf_core/modules/modules_command.py
nf_core/modules/modules_json.py
nf_core/modules/patch.py
nf_core/modules/remove.py
nf_core/modules/test_yml_builder.py
nf_core/modules/update.py

Add a step in all `nf-core modules` commands to check if the modules directory of a pipeline has the correct structure. See slack [discussion](https://nfcore.slack.com/archives/CJRH30T6V/p1664884189665479?thread_ts=1664882848.607819&cid=CJRH30T6V)

Check 'modules' directory structure

---

.github/workflows/push_dockerhub_release.yml
CHANGELOG.md

GitPod docker push on release was failing, as a copy+paste typo had `tools` instead of `gitpod`:
```bash
docker tag nfcore/gitpod:latest nfcore/tools:2.6
docker push nfcore/gitpod:2.6
```
Now fixed, should work next release 🤞🏻

Tag the correct gitpod docker image name

---

CHANGELOG.md
nf_core/modules/install.py
nf_core/subworkflows/install.py

The command `nf-core subworkflows install` installs also the modules and subworkflows imported in the subworkflow. 
To deal with already installed modules, I had to add a question asking if the modules should be re-installed with `--force`. Because subworkflows will need to work with the last version of the modules, the modules must be re-installed (aka. updated), otherwise the installation fails.
🧠 what will happen when installing an older version of a subworkflow?

update subworkflows install so it installs also imported modules and subworkflows

---

nf_core/pipeline-template/docs/usage.md

We introduced additional whitespace characters in the current version of `usage.md` in the template, which throw linting errors for every PR at the moment.

fix linting in `dev`

---

nf_core/modules/install.py
nf_core/subworkflows/install.py

the recursive install command from subworkflows updates modules.json with all installed modules

fix updating modules.json with install command

---

CHANGELOG.md
nf_core/modules/modules_json.py
nf_core/subworkflows/install.py

The `check_up_to_date()` function from `modules_json.py` also checks for subworkflows.
This also fixes the issue when installing a subworkflow from a new modules repo. To test:
```
nf-core create # Create a new test pipeline
nf-core subworkflows --git-remote https://gitlab.com/nf-core/modules-test.git --branch subworkflows install bam_sort_samtools # try installing a subworkflow from a new remote
```

check_up_to_date() also checks for subworkflows

---

CHANGELOG.md
nf_core/modules/modules_command.py
nf_core/modules/patch.py
nf_core/modules/update.py

Closes #1868 
The new function runs in every `nf-core modules` command, when we check if the `modules` directory structure is outdated and try to fix it.
It updates paths from patch files.

add a function to check if patch files contain outdated paths

---

CHANGELOG.md
nf_core/__main__.py
nf_core/create.py
nf_core/sync.py

Fixes #1879
Adds `-t/--template-yaml` to `nf-core sync`, so that users can update their pipeline based on existing template file.

NF-Core Sync includes template.yaml as option

---

nf_core/pipeline-template/.github/workflows/ci.yml

The changes I added will cancel all the workflows (that share the same concurrency group) related to the current PR when new changes are pushed. I've added it only to the CI pipeline which is the most resource intensive one.

Autocanceling previous tests when pushing changes

---

CHANGELOG.md
nf_core/sync.py
tests/test_sync.py

This PR improves the code coverage of the `sync` module and fixes a couple of bugs along the way.
Only the `sync` function remains untested but this one is kind of a beast so I leave it for now.
Closes #1913

Improve test coverage of sync.py

---

.github/workflows/create-lint-wf.yml
.github/workflows/create-test-wf.yml
.github/workflows/deploy-pypi.yml
.github/workflows/lint-code.yml
.github/workflows/push_dockerhub_dev.yml
.github/workflows/push_dockerhub_release.yml
.github/workflows/pytest.yml
.github/workflows/sync.yml
.github/workflows/tools-api-docs-dev.yml
.github/workflows/tools-api-docs-release.yml
CHANGELOG.md
nf_core/pipeline-template/.github/workflows/ci.yml
nf_core/pipeline-template/.github/workflows/linting.yml

https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
https://github.com/nf-core/modules/issues/2238

fix(template): Update ci jobs to use nodejs16

---

nf_core/pipeline-template/nextflow.config

This is the extension of https://github.com/nf-core/modules/pull/2306 requested by @jfy133 , to account for conda not being enabled by default with NXF 22.10, refer to that thread for discussion.

set conda.enabled=true for Conda

---

CHANGELOG.md
nf_core/create.py
tests/test_create.py
tests/test_sync.py

For reference: https://nfcore.slack.com/archives/CE5LG7WMB/p1665850093986309
When a local `.gitconfig` specified the `init.defaultBranch` to anything else than `master` one sync test would fail.
To make the tests system config agnostic, it is necessary to have a different way of telling nf-core tools what it should use as a default branch when creating new pipeline repositories. This PR implements just that in the internals and uses the feature to make tests pass on systems with `init.defaultBranch` not set to `master`. It does not expose this feature to the CLI - this should maybe be the topic of another PR that then also updates the docs.

enable setting defaulBranch for pipeline repo creation

---

CHANGELOG.md
nf_core/modules/test_yml_builder.py

close #1958
The file `versions.yml` was removed from `test.yml` by mistake. 
Add the check that the file exist back, but do not print the md5sum.

add versions.yml to create-test-yml but not md5sum

---

CHANGELOG.md
nf_core/modules/modules_command.py
tests/modules/install.py

Close #1941 
Only warn when checking that the pipeline directory contains a `main.nf` and a `nextflow.config` file if the pipeline is not an nf-core pipeline

when pipeline dir doesn't contain `main.nf` or `nextflow.config`

---

nf_core/pipeline-template/workflows/pipeline.nf

- Removes mixing MultiQC version into channel that is already closed and not used any more.
- Updates `unique` operator to filter on version file contents.
Fixes #1962

Remove multiqc versions channel mix

---

CHANGELOG.md
requirements-dev.txt
tests/modules/create.py
tests/test_modules.py
tests/test_subworkflows.py
tests/utils.py

Mock biocontainers and anaconda api calls to make tests faster.
Related to #1697

Mock biocontainers and anaconda api calls in module tests

---

.github/workflows/pytest.yml
CHANGELOG.md

Python 3.11 has been release - it's high time to run tests with Python 3.11.

Run tests with Python 3.11

---

CHANGELOG.md
nf_core/__main__.py
tests/test_cli.py

This PR adds unit test for the following commands: `list`, `launch`, `download`, `create` and `lint`.
The code of these commands is quite simple so what the tests do is mostly check that  no cli arguments are forgotten and that they are passed along to the correct function.
Related to #1937

Improve test coverage of `__main__.py`

---

.github/workflows/create-lint-wf.yml
.github/workflows/create-test-wf.yml
.github/workflows/lint-code.yml
.github/workflows/pytest.yml
.github/workflows/tools-api-docs-dev.yml
nf_core/pipeline-template/.github/workflows/linting.yml

This has been floating around. What it does is:
- Run when code is merged into dev
- Run *once* when a PR is created
- Run on a release(since it doesn't happen often we might as well check)
What this prevents:
- The same CI jobs running *twice* on a PR
- CI running whenever someone pushes code they're working on that isn't
a PR
https://github.com/orgs/community/discussions/26276 full explanation

Minimal ci runs

---

nf_core/gitpod/gitpod.Dockerfile

Update's Gitpod dockerfile
- openjdk: 11.0.15 -> 17.0.3
- nextflow: 22.04.0 -> 22.10.0
- add nf-test
- mamba: 0.24.0 -> 0.27.0
- pip: 22.1.2 -> 22.3
- black: 22.6.0 -> 22.10.0
Container builds successfully inside Gitpod.
`nf-core create` works inside the container as does `nextflow run main.nf -profile test,mamba,gitpod`.

Update Gitpod dockerfile

---

CHANGELOG.md
nf_core/launch.py

Skip the deletion step of `--params_in`, if `--params_in` == `--params_out`.
Fixes #1969.

Fix params-in functionality in `nf-core launch`

---

CHANGELOG.md
nf_core/components/components_install.py
nf_core/modules/install.py
nf_core/modules/modules_json.py
nf_core/modules/patch.py
nf_core/modules/update.py
nf_core/subworkflows/create.py
nf_core/subworkflows/install.py
tests/modules/install.py
tests/modules/update.py
tests/subworkflows/install.py
tests/test_modules.py
tests/test_subworkflows.py
tests/utils.py

add tests for subworkflows install command

---

.github/workflows/create-lint-wf.yml
.github/workflows/create-test-wf.yml
.github/workflows/fix-linting.yml
.github/workflows/lint-code.yml
.github/workflows/sync.yml
nf_core/create.py
nf_core/pipeline-template/.github/workflows/fix-linting.yml
nf_core/pipeline-template/.github/workflows/linting.yml
nf_core/pipeline-template/.github/workflows/linting_comment.yml
requirements.txt

Python:
imghdr -> filetype [PEP-594](https://peps.python.org/pep-0594/#imghdr
GH-Actions:
update `upload-artifact`, `isort-action`, `setup-node`, `setup-python`
switch to new style for `::set-output`

fix deprecation warnings for python and github actions

---

CHANGELOG.md
docs/api/make_lint_md.py
nf_core/components/components_create.py
nf_core/components/components_install.py
nf_core/modules/install.py
nf_core/modules/modules_json.py
nf_core/modules/remove.py
nf_core/modules/update.py
nf_core/pipeline-template/modules.json
nf_core/subworkflows/install.py
tests/modules/list.py
tests/modules/modules_json.py
tests/modules/patch.py
tests/modules/update.py
tests/test_subworkflows.py

Track from where modules and subworkflows are installed.
- a module installed with `nf-core modules install`: "modules"
- a subworkflow installed with `nf-core subworkflows install`: "subworkflows"
- a module or subworkflow installed automatically when installing another subworkflow: "<subworkflow name>"
Updates `modules.json` file adding a new field `installed` for every module/subworkflow
💭 With previously installed modules/subworkflows, it assumes they were installed by an nf-core command, without taking into account if they are used by other subworkflows.
I also fix some small bugs that I found on the way.

Track from where modules and subworkflows are installed

---

CHANGELOG.md
nf_core/modules/update.py
tests/modules/update.py
tests/test_modules.py

don't write file when applying a patch during update

---

nf_core/__main__.py
nf_core/modules/lint/__init__.py

Follow on from PR nf-core/tools#2016
Reported on Slack [here](https://nfcore.slack.com/archives/CJRH30T6V/p1668520998214899).
Failing action run [here](https://github.com/nf-core/modules/actions/runs/3470901919/jobs/5800144255).
Messed up the function keywords in #2016, this fixes it. Bug replicated locally and fixed locally.
To replicate with current dev in the modules repo, checked out with PR https://github.com/nf-core/modules/pull/2512:
```bash
nf-core --hide-progress modules lint gatk4/preprocessintervals
```

Fix hide-progress bug

---

nf_core/__main__.py

Fix the ungrouped subcommands.
Before (see _Commands_ at the bottom):
After:
Also for `nf-core subworkflows`:
Before:
After:

Properly group subcommands in help text

---

.prettierignore
CHANGELOG.md
nf_core/pipeline-template/.prettierignore
nf_core/pipeline-template/assets/slackreport.json
nf_core/pipeline-template/lib/NfcoreTemplate.groovy
nf_core/pipeline-template/nextflow_schema.json
nf_core/pipeline-template/workflows/pipeline.nf

Hello,
Got very interested in what @matthdsm did in #1798 . This is a small extension to support Slack as well, since Slack doesn't understand adaptive cards.
Here is how the notifications look like:
The JSON has a very long and tricky line where I try to improve the look-and-feel of the pipeline configuration:
- paths are printed as code
- dates are formatted according to the locale settings
- the hook_url itself is hidden
Note: I am using the legacy "attachments" method of the Slack API, rather than the now-recommended Block Kit method, because I couldn't find how to make the latter put some colour. I think one has to immediately know whether it failed or not, and the colour is faster to recognise than the text itself.

Extended the hook_url functionality to Slack

---

CHANGELOG.md
nf_core/lint/nextflow_config.py
nf_core/pipeline-template/lib/NfcoreSchema.groovy
nf_core/pipeline-template/lib/NfcoreTemplate.groovy
nf_core/pipeline-template/lib/WorkflowMain.groovy
nf_core/pipeline-template/nextflow.config
nf_core/pipeline-template/nextflow_schema.json

As briefly discussed in the nf-core Slack, I was recently asked by a user "how do I know what version I have of your workflow?" which seemed like a simple question!
I was surprised to find that `nextflow info <workflow>` does not provide this (but I can imagine why). `nextflow info` does list and show the current revision, which is fine if you've checked out a specific tag but not useful for users who have just pulled with `nextflow run <workflow>` without `-r`.
The `workflow.manifest.version` is used by nf-core's template to [populate an email message](https://github.com/nf-core/tools/blob/3db6e4be703a5ca0b4a747c030f5848e4b8d2304/nf_core/pipeline-template/lib/NfcoreTemplate.groovy#L64), and [the logo function](https://github.com/nf-core/tools/blob/3db6e4be703a5ca0b4a747c030f5848e4b8d2304/ …

Add --version to NfCoreTemplate

---

CHANGELOG.md
nf_core/pipeline-template/lib/WorkflowMain.groovy

This is to prevent 'hiding' or 'loss' of parameter errors (mainly non-failing typos in parameter names), that can come due to very long parameter summary + small terminal windows.
Originally proposed here: https://nfcore.slack.com/archives/CE4K7FEHE/p1669035465524059

Flip execution order of parameter summary and validation

---

nf_core/components/components_test.py
nf_core/modules/lint/__init__.py
nf_core/modules/modules_json.py
nf_core/modules/patch.py

There was duplicated functionality being used which has been superseded by the generalised `ModulesJson.get_all_components`

Remove duplicate code

---

.pre-commit-config.yaml
CHANGELOG.md
nf_core/lint/actions_ci.py
tests/lint/actions_ci.py
tests/test_lint.py

Don't check for `docker pull` commands in `actions_ci` lint test (leftover from DSL1)

Don't check for `docker pull` commands in `actions_ci` lint test (leftover from DSL1)

---

nf_core/components/components_utils.py
nf_core/components/install.py
nf_core/components/update.py
nf_core/modules/lint/__init__.py
nf_core/modules/modules_json.py

Correctly sets the installed_by also for subworkflows when no modules.json was found

fix modules.json recreation

---

CHANGELOG.md
setup.py

It is hitherto possible to install nf-core tools with pip and unsupported older Python versions. This PR prevents that.
Closes #1876

require minimum supported Python version for installation

---

.github/workflows/pytest-frozen-ubuntu-20.04.yml
CHANGELOG.md
nf_core/create.py
tests/test_sync.py

This PR fixes the following issues:
- Github's Ubuntu images use the very latest version of git (i.e. v2.38.1, see [here](https://github.com/actions/runner-images/blob/ubuntu20/20221119.2/images/linux/Ubuntu2004-Readme.md)). More specifically, this is different from the version available on the image that is used for the tests (Ubuntu 20.04, git 2.25.1).  Since nf-core/tools heavily depends on the git version available to the user, this PR downgrades git so that the testing environment is more similar to what a typical user would have.
- Consequently, some failed tests have been going under the radar in `test_create` and `test_sync`. This PR also fixes these tests.
Additionally, this is at least the second time we encounter bugs that are specific to the version of git being used so maybe …

Run tests with a realistic version of git

---

nf_core/modules/lint/main_nf.py

Avoid double quotes when specifying tool container URLs.
Close #2084

Lint container URLs in double quotes

---

nf_core/modules/modules_json.py

We initially had string entries in an older dev version, so this function can probably be removed with v2.8

correct the format of the `installed_by` entries

---

CHANGELOG.md
nf_core/modules/test_yml_builder.py
nf_core/subworkflows/test_yml_builder.py

run prettier on test yml file after creation

---

CHANGELOG.md
nf_core/pipeline-template/lib/NfcoreTemplate.groovy

I've noted in some cases that people believe a pipeline has completely failed, even though a pipeline developer allows some processes to fail, because the final completion message is red.
This switches from Red to Yellow to make it less 'failurey'.

Tone down colour in successful completion but some failed processes

---

MANIFEST.in
nf_core/.pre-commit-prettier-config.yaml
nf_core/lint_utils.py

Probably preferred to #2099.
Not sure that is the best way to handle the `stdout` from pre-commit, which is a bit confusing when you don't know that we run pre-commit. It just removes:
```
prettier.................................................................Failed
- hook id: prettier
- files were modified by this hook
```

Add specific prettier-commit config for prettier check, improve log message

---

nf_core/components/components_create.py
nf_core/modules/create.py
nf_core/subworkflows/create.py

Ensure component author is properly captured and stored

---

nf_core/create.py

Fix lint pipeline name

---

CHANGELOG.md
nf_core/modules/lint/main_nf.py

allow specifying only one container

---

CHANGELOG.md
nf_core/create.py
nf_core/sync.py

Related to #2117  and [slack discussion](https://nfcore.slack.com/archives/CE5LG7WMB/p1670591325094329)
The code will check that the pipeline name doesn't contain dashes if the name if provided by prompt. With `nf-core create` or `nf-core create --name my-name`.
It won't be checked if the pipeline name is provided with a template `nf-core create -t template.yml` where `template.yml` contains:
```
name: my-name
description: A test pipeline
author: me
prefix: my-org
```
If `template.yml` doesn't provide a custom prefix or the prefix is set to `nf-core`, dashes won't be allowed.
To sync a pipeline created with dashes, the template must be used: `nf-core sync -t template.yml`

only check pipeline name without dashes if the name is provided by prompt

---

README.md

add newline before table 🤞🏻

---

CHANGELOG.md
nf_core/launch.py
nf_core/lint_utils.py
nf_core/modules/modules_json.py
nf_core/schema.py

run prettier after dumping a json schema file

---

CHANGELOG.md
nf_core/lint/nextflow_config.py
nf_core/module-template/modules/main.nf
nf_core/pipeline-template/lib/WorkflowMain.groovy
nf_core/pipeline-template/modules.json
nf_core/pipeline-template/modules/local/samplesheet_check.nf
nf_core/pipeline-template/modules/nf-core/custom/dumpsoftwareversions/main.nf
nf_core/pipeline-template/modules/nf-core/custom/dumpsoftwareversions/templates/dumpsoftwareversions.py
nf_core/pipeline-template/modules/nf-core/fastqc/main.nf
nf_core/pipeline-template/modules/nf-core/multiqc/main.nf
nf_core/pipeline-template/nextflow.config
nf_core/pipeline-template/nextflow_schema.json
tests/modules/update.py

Close #2125
Follow up from #1952 and [modules/#2654](https://github.com/nf-core/modules/pull/2654)

Remove params.enable_conda

---

CHANGELOG.md
nf_core/lint/nextflow_config.py
nf_core/modules/modules_json.py
nf_core/pipeline-template/lib/WorkflowMain.groovy
nf_core/pipeline-template/modules.json
nf_core/pipeline-template/modules/nf-core/custom/dumpsoftwareversions/main.nf
nf_core/pipeline-template/modules/nf-core/custom/dumpsoftwareversions/templates/dumpsoftwareversions.py
nf_core/pipeline-template/modules/nf-core/fastqc/main.nf
nf_core/pipeline-template/modules/nf-core/multiqc/main.nf
nf_core/pipeline-template/nextflow.config
nf_core/pipeline-template/nextflow_schema.json
nf_core/schema.py
nf_core/utils.py
tests/modules/modules_json.py
tests/modules/update.py
tests/test_launch.py
tests/test_lint.py

Handle json.load() exceptions

---

CHANGELOG.md
nf_core/pipeline-template/nextflow.config

This ensures consistency across all profiles that only one software environment system is selected at any one time.
This also allows complete 'evaluation' of what container system is being used within a given pipeline run. 
This was motivated by: https://github.com/nf-core/modules/pull/2688/files where we have to check if conda is enabled with `session.config.conda.enabled`.

Explicitly disable conda container profiles

---

CHANGELOG.md
nf_core/pipeline-template/conf/test_full.config

To help reduce AWS S3 maintainence and costs

Activate work dir cleanup on successful completion

---

nf_core/schema.py

The code for `nf-core schema docs` assumed that `required` was a field on the `parameter` object in the `json`. It is actually an array at the level of the properties. Due to this `param.get('required')` was always false and auto-generated docs display every parameter as optional.
This PR fixes the code to check for the parameters inclusion in the `required` array.

schema docs correctly show required status

---

CHANGELOG.md
nf_core/pipeline-template/docs/usage.md

To address issues as discussed in: https://nfcore.slack.com/archives/CE6SDBX2A/p1674599225438509
Text is copied from @d4straub 's text in nf-core/ampliseq with minor modifications and extensions.
I've also tagged myself as contributors, to start that tradition as discussed in the maintainers channel (so each release CHANGELOG shows who contirbuted)

Add params file docs to usage.md in template

---

CHANGELOG.md
nf_core/bump_version.py
nf_core/create.py
nf_core/download.py
nf_core/launch.py
nf_core/lint/__init__.py
nf_core/lint/files_unchanged.py
nf_core/lint/template_strings.py
nf_core/list.py
nf_core/modules/bump_versions.py
nf_core/pipeline-template/conf/base.config
nf_core/utils.py
tests/test_download.py
tests/test_test_utils.py

now `130..145`
Discussion in `#configs` channel on the nf-core Slack.
'cc @pontus @pcantalupo @muffato @FelixKrueger
'cc @nf-core/core for visibility as this is a fairly wide ranging change (though hopefully not controversial)

Make jobs automatically resubmit for a much wider range of exit codes

---

README.md

Add `repository_type` in `.nf-core.yml` files from rich codex.

Fix rich codex images

---

CHANGELOG.md
nf_core/pipeline-template/bin/check_samplesheet.py

See https://github.com/nf-core/funcscan/pull/227 for more info
Closes #1539

Remove dodgy sniffer code from samplesheet_check.py

---

CHANGELOG.md
nf_core/pipeline-template/.github/PULL_REQUEST_TEMPLATE.md

Fixed minor Jinja2 templating bug that caused the PR template to miss a newline

Fixed minor Jinja2 templating bug

---

.github/RELEASE_CHECKLIST.md
.gitpod.yml
CHANGELOG.md
nf_core/gitpod/gitpod.Dockerfile

Add the Nextflow version to Gitpod container matching the minimal Nextflow version for nf-core (according to `nextflow.config`)
Use `nfcore/gitpod:dev` container in the dev branch. Add step to release checklist to change containers.

Use dev Gitpod container on dev branch

---

docs/api/_src/pipeline_lint_tests/system_exit.md
nf_core/lint/__init__.py
nf_core/lint/system_exit.py
nf_core/pipeline-template/lib/NfcoreSchema.groovy
nf_core/pipeline-template/lib/WorkflowMain.groovy
nf_core/pipeline-template/lib/WorkflowPipeline.groovy

#1840 for more details
This implements a very simplistic check of all `.nf` and `.groovy` files in the pipeline repo for `System.exit` calls.

Lint check for `System.exit` calls

---

CHANGELOG.md
requirements-dev.txt
tests/modules/create.py
tests/test_modules.py
tests/test_subworkflows.py
tests/utils.py

Just some yak shaving, `responses` has some nice features that might improve testing in the future such as [recording responses to files](https://github.com/getsentry/responses#record-responses-to-files).

Replace requests_mock with responses

---

CHANGELOG.md
nf_core/__main__.py
nf_core/components/components_command.py
nf_core/lint/nextflow_config.py

Previously `nf-core modules lint` would use a weird mixture of `.nf-core-lint.yml` (deprecated) and `.nf-core.yml`; I believe this PR removes all references to the former, except for the code in `nf_core/utils.py` that prints a warning if only the deprecated file is present.
For example, running `nf-core modules lint fastqc` on a freshly-created repo with the `fastqc` module shows a warning about fastqc being out of date, even with the following `.nf-core.yml`:
```yaml
repository_type: pipeline
lint:
main_nf: false
```
(if you instead put that lint config in `.nf-core-lint.yml`, you get... a weird crash "AttributeError: 'NFCoreModule' object has no attribute 'process_name'", but you do also get "INFO     Ignoring lint test: main_nf".)
With this PR, the deprecated config file is ignored …

Make `nf-core modules lint` use new config file

---

CHANGELOG.md
README.md
nf_core/__main__.py
tests/test_cli.py

`nf-core lint` and `nf-core modules lint` can both be called with no arguments, but `nf-core schema lint` requires that you pass the path to the schema. Since this will often just be at `./nextflow_schema.json`, defaulting to that reduces the length of the invocation in the common case and makes the usage of all three lint commands more consistent.
I'm not 100% sure of how `click.Path` works – is just providing a string as the default here correct? should I be using some other `Path` type?
Also I don't know how the fancy images in the readme get generated, I'm hoping based on looking at the commit history for them that there's some magic github action that will kick in once I open the PR...
Fixes #1838

Don't require an argument for `nf-core schema lint`

---

CHANGELOG.md
nf_core/__main__.py
nf_core/modules/lint/main_nf.py
tests/modules/lint.py

Addresses #2187 
usage of params.enable_conda has been deprecated. Currently it is a fail condition from the pipeline linter which only checks the config file but the module linter does not.
Tests were updated to catch new failures.

Lint check for params.enable_conda

---

CHANGELOG.md
requirements.txt

Older versions throw an error because of the  padding parameter.

update required rich version

---

.github/workflows/create-lint-wf.yml
CHANGELOG.md
nf_core/components/install.py
tests/modules/install.py
tests/modules/lint.py
tests/modules/patch.py
tests/modules/remove.py
tests/modules/update.py
tests/subworkflows/install.py
tests/subworkflows/list.py
tests/test_modules.py
tests/test_subworkflows.py
tests/utils.py

Log error when multiple remotes have the same org name

---

CHANGELOG.md
nf_core/modules/lint/__init__.py

Thanks to tests failing in https://github.com/nf-core/tools/pull/2190 I noticed that when linting a module providing a `--git_remote` and linting all modules with `--all` or indicating so by prompt, all modules are linted independent on the remote they come from.
This takes into account the `--git_remote` param and lints only the modules from that repo.

Take into accout a provided remote url when linting all modules

---

CHANGELOG.md
nf_core/pipeline-template/tower.yml

add tower.yml file to pipeline template

---

.github/workflows/create-lint-wf.yml
CHANGELOG.md
nf_core/lint/readme.py

remove bioconda badge check comment, add zenodo doi check

---

CHANGELOG.md
README.md
nf_core/download.py
nf_core/module-template/modules/main.nf
nf_core/modules/bump_versions.py
nf_core/modules/lint/main_nf.py
nf_core/pipeline-template/modules/local/samplesheet_check.nf
nf_core/utils.py
tests/utils.py

All modules will by default use relative Docker URI now, e.g. `biocontainers/fastqc` instead of `quay.io/biocontainers/fastqc`. Instead, `quay.io` should be set at the pipeline level (see #2233). The module creation should work as before and singularity is untouched.

Modules Docker containers no longer includes quay.io as prefix

---

nf_core/pipeline-template/.github/workflows/linting.yml

nf-core linting in pipeline uses python 3.8 instead of 3.7

---

CHANGELOG.md
nf_core/pipeline-template/conf/test_full.config
nf_core/pipeline-template/docs/usage.md

See discussion in [Slack](https://nfcore.slack.com/archives/CE5LG7WMB/p1683231603251939)
x-ref: https://github.com/nextflow-io/nextflow/issues/3645

Remove cleanup=true from test_full.config

---

.gitpod.yml
CHANGELOG.md
nf_core/gitpod/gitpod.Dockerfile
nf_core/pipeline-template/.gitpod.yml

We've had some issues where the GitPod Nextflow version is behind the stable release, and doesn't include important bugfixes and changes. It's difficult to remember to bump the version there manually every time. This PR makes sure that the latest stable version is in the image automatically.
* Don't pin the Nextflow version in the Conda install
* Run `nextflow self-update` as part of the build process, in case bioconda is not up to date
* GitPod config: Update Nextflow as an init task. Install pre-commit hooks.

GitPod base image: Always self-update to the latest version of Nextflow.

---

CHANGELOG.md
nf_core/module-template/modules/main.nf

Add stub to the modules template

---

CHANGELOG.md
nf_core/modules/lint/main_nf.py

Detects docker name by single slash and colon in string. 
Fixes #2280

Fix quay.io detection in simple docker names

---

CHANGELOG.md
nf_core/modules/lint/main_nf.py
tests/modules/patch.py

Changes:
- Linting error if container starts with quay.io/biocontainers but not quay.io/biocontainers/mulled
Fixes #2276

Linting error if quay.io found in biocontainer name

---

nf_core/pipeline-template/nextflow.config

The `docker.registry` configuration should always be set, as running on cloud executors will need to pull docker images but will not necessarily use the `docker` profile.

Move docker.registry definition out of docker profile

---

CHANGELOG.md
nf_core/pipeline-template/assets/slackreport.json

`sanger-tol/readmapping` is the name of the pipeline I used to test the feature. Sorry about that !

bugfix: the actual pipeline name should be shown

---

nf_core/utils.py

Trying to put the html request into the background, so it doesn't block the rest of the calls.
Difficult to test, because I can't seem to get rid of all the caches, but it makes it at least not slower...

Avoid blocking requests when checking for new version

---

nf_core/pipeline-template/lib/NfcoreSchema.groovy

As we always display params used for that, because default is the map inside the genomes map

Add more info about reference genome

---

nf_core/pipeline-template/nextflow_schema.json

When `params.max_time` is set to `72.h` for example, Nextflow converts that to `3d` which doesn't match the current pattern when using the `nf-validation` plugin. 
```
The following invalid input values have been detected:
* --max_time: string [3d] does not match pattern ^(\d+\.?\s*(s|m|h|day)\s*)+$ (3d)
```
This PR fixes that issue

Add `d` to the pattern of max_time

---

nf_core/pipeline-template/nextflow.config
nf_core/pipeline-template/nextflow_schema.json

as it doesn't renders properly in tower
cf 
https://github.com/nf-core/rnaseq/pull/964
https://github.com/nf-core/sarek/pull/1105

remove params.tracedir

---

README.md
nf_core/components/components_test.py

The command `nf-core modules test` runs tests using pytest. We use the pytest argument `--git-aware`.
This argument is used to avoid copying the whole `.git` directory and files ignored by git.
It will only include files listed by `git ls-files`.
In order to test a new module or subworkflow, the new files have to be committed, otherwise they will be ignored. This was reported in https://github.com/nf-core/tools/issues/2235 and nf-core Slack.
This PR adds documentation to advise committing changes before running the command, as it is better to keep the argument `--git-aware`.
It throws a warning if there are uncommitted changes:

add docs to commit new files before pytest

---

CHANGELOG.md
nf_core/schema.py

Lint for null values in the `nextflow_schema.json` to avoid errors where nulls are converted to "None" by the schema tooling. https://github.com/nf-core/sarek/pull/1116#discussion_r1233967703

lint for default values null, empty strings or none

---

CHANGELOG.md
nf_core/pipeline-template/assets/methods_description_template.yml
nf_core/pipeline-template/lib/WorkflowPipeline.groovy
nf_core/pipeline-template/workflows/pipeline.nf

Extends the methods description in the MultiQC report to optionally generate text dynamically depending on what steps in the pipeline are run, to include citations/references of the tools used in the given pipeline run.
This hopefully will improve method reporting and credit to all the authors of the tools used in pipelines, as it more actively shows citation information of these tools over `citations.md` or `meta.yaml`, neither of which are exposed to users. It also makes it easier for users to report these as the pipeline author can make the text only have references of tools used in the run, so the user does not have to scroll through 10s of bibliographic references in `citations.md` to find the ones of the tools they actually used.
Real life proof of concept can be seen here: …

Add option to dynamically insert tool citations into MultiQC report

---

CHANGELOG.md
nf_core/create.py
tests/data/pipeline_create_template_skip.yml
tests/test_create.py

Fix linting when createing a pipeline skipping some parts of the template
Close #2329

Fix linting when creating a pipeline skipping some parts of the template

---

nf_core/create.py

Fix linting error where log didn't match the template https://github.com/nf-core/pangenome/pull/135#issuecomment-1600931360

fix url when generating assets logo

---

CHANGELOG.md
nf_core/components/update.py

Close https://github.com/nf-core/tools/issues/2014

don't update modules_json if module is not updated

---

nf_core/gitpod/gitpod.Dockerfile

To test and develop the respective features for #2336, I had to install Apptainer in Gitpod several times a day.
Although I am not sure how often other people will need it, I see little harm in adding Apptainer by default to the Gitpod image. The image is already quite bloated with conda, so the additional 80MB-100MB will barely matter?
Unfortunately, I could not test the new image. I tried to build it locally, but the `RUN nextflow self-update` step seems to get stuck at  `Downloading dependency org.pf4j:pf4j-update:jar:2.3.0`. That one step is running now since 5h and the whole build so far is taking a little over 7h, which I think might be a MacM1 issue? 
So whoever will review this PR should please clone this, navigate to the folder `cd tools` and run
`docker build . -f …

Add Apptainer (Singularity) to Gitpod nf-core base image

---

CHANGELOG.md
nf_core/download.py
tests/data/mock_config_containers/nextflow.config
tests/test_download.py

When downloading a pipeline with `--container-system singularity `, tools will search for the respective containers at two different places:
1. In the modules (DSL2 syntax)
2. In the configs (Process scope)
While the module parsing was quite advanced, the config parsing assumed plain container definitions, which doesn't hold true e.g. for [differentialabundance 1.2.0](https://github.com/nf-core/differentialabundance/blob/3a849f046990707cad2a0df751c371ac7f1165ab/conf/modules.config#L298-L306):
Therefore, I have now broken up the function `find_container_images()`.  The part for cleaning the raw DSL2 matches was moved to a new helper function `rectify_raw_container_matches()` that is now also applied to the config matches.
_Just a draft for now, tests etc. will be added tomorrow._

Download: Improve container detection in configs, specifically the container parameter in process scope

---

CHANGELOG.md
nf_core/pipeline-template/nextflow.config

add apptainer.registry

---

CHANGELOG.md
nf_core/module-template/modules/meta.yml
nf_core/subworkflow-template/subworkflows/meta.yml

just a tiny, tiny change to hint that the description field can be markdown.

Add markdown hint to modules template

---

CHANGELOG.md
nf_core/download.py

Add apptainer keyword to the list of false positive matches. Bare minimum to possibly support a future `apptainer.registry` notation in the container specifications ?

Download: Add `apptainer` to the list of false positve container strings

---

nf_core/pipeline-template/main.nf

Following on from Slack, adding a `// TODO` comment explaining that this line is as an example only.

params.fasta - add TODO

---

CHANGELOG.md
nf_core/download.py
tests/data/mock_module_containers/modules/mock_docker_single_quay_io.nf
tests/data/mock_module_containers/modules/mock_dsl2_apptainer_var1.nf
tests/data/mock_module_containers/modules/mock_dsl2_apptainer_var2.nf
tests/data/mock_module_containers/modules/mock_dsl2_current.nf
tests/data/mock_module_containers/modules/mock_dsl2_current_inverted.nf
tests/data/mock_module_containers/modules/mock_dsl2_old.nf
tests/data/mock_module_containers/modules/mock_dsl2_variable.nf
tests/test_download.py

This PR improves the code in Download that detects and resolves container images in modules and configs. 
Previously, a loop was used to prioritize http:// downloads over docker URIs. For example, from
```
container "${ workflow.containerEngine == 'singularity' && !task.ext.singularity_pull_docker_container ?
'https://depot.galaxyproject.org/singularity/fastqc:0.11.9--0' :
'biocontainers/fastqc:0.11.9--0' }"
```
the strings `'singularity'`,  `'https://depot.galaxyproject.org/singularity/fastqc:0.11.9--0'` and `'biocontainers/fastqc:0.11.9--0'` were extracted into a list. Then we iterated over this list and broke the loop as soon as a match with a URL regex or Docker regex was found.
This approach was flaky, because `'singularity'` or `'apptainer'`  are valid Docker URIs. Thus, unless it …

Download: Improved container priority and resolution

---

CHANGELOG.md
nf_core/pipeline-template/nextflow_schema.json

Since v2.9 defaults to false were introduced in the nextflow schema. They are not required, as any value not evaluating to true won't be printed by `printSummaryParams()`. Those defaults are also automatically removed by `nf-core schema build`.

Remove default false from json schema

---

CHANGELOG.md
nf_core/utils.py

Initialise `docker_image_name` to avoid `UnboundLocalError` error

---

docs/api/_src/index.md
docs/api/_src/subworkflow_lint_tests/index.md
docs/api/_src/subworkflow_lint_tests/main_nf.md
docs/api/_src/subworkflow_lint_tests/meta_yml.md
docs/api/_src/subworkflow_lint_tests/module_changes.md
docs/api/_src/subworkflow_lint_tests/module_tests.md
docs/api/_src/subworkflow_lint_tests/module_todos.md
docs/api/_src/subworkflow_lint_tests/module_version.md
nf_core/subworkflows/lint/meta_yml.py
nf_core/subworkflows/lint/subworkflow_tests.py

- Add a test to ensure that `meta.yml` does not contain the deprecated "modules" section and uses "components" instead.
- If a module was used in the subworkflow and another imported subworkflow, the error was printed twice -> that is fixed here

Some modifications in subworkflows lint

---

nf_core/create.py
nf_core/lint/files_exist.py
tests/test_create.py

When customizing the pipeline template, information was saved to a file named `pipeline_template.yml`. This PR deprecates such file and stores the info to `.nf-core.yml` instead.
Partially close #2359 (needs a follow-up PR moving data from `pipeline_tamplate.yml` in old pipelines)

Save pipeline template info to `.nf-core.yml`

---

.github/workflows/create-test-lint-wf-template.yml
CHANGELOG.md
nf_core/__main__.py
nf_core/create.py
nf_core/sync.py

Follow up from #2388 
Close #2359

Save template info

---

CHANGELOG.md
nf_core/__main__.py
tests/test_cli.py

Removing the `--no-git` option from `nf-core create`.
The argument is maintained as it is used by other commands such as `sync` and several tests
Close #2081

remove `--no-git` option from pipeline create command

---

CHANGELOG.md
nf_core/modules/lint/main_nf.py

Changes:
- Container registries do not have a consistent API, so calling them
for container presence doesn't seem to work on GHCR or NVCR.
- In addition some registries require authentication and do not have a consistent method of authentication, likely oauth2 but not clear.
- This drops the error to a warning so we don't fail tests.
Relates to https://github.com/nf-core/modules/issues/3693 and https://github.com/nf-core/tools/issues/2393

fix: Drop container error to warning

---

.github/workflows/pytest.yml
.github/workflows/tools-api-docs-dev.yml
CHANGELOG.md
nf_core/download.py

Some pipelines respectively modules use full-length URIs such as `quay.io/qiime2/core:2022.11` when referencing the Docker container image. 
Such URIs were not properly accounted for when the new `-l` / `--container-library` feature for _tools 2.9_ was devised.   This prevented the user from successfully pulling the images, because the registry was duplicated in the final URI as is exemplified with `nf-core download ampliseq -r '2.6.1' -s 'singularity' -t`:
```
INFO     Pulling of "quay.io/qiime2/core:2022.11" failed.
Please troubleshoot the command
"singularity pull --name
/crex/proj/sllstore2017079/private/zepper/nextflow/download_pipelines/ampliseq/singularity-images/quay.io-qii
me2-core-2022.11.img docker://quay.io/quay.io/qiime2/core:2022.11" manually. 
```
In general, three possible …

Download: Trim explicit registries

---

CHANGELOG.md
nf_core/pipeline-template/nextflow.config

This PR adds autoMounts in apptainer.

Add apptainer automounts

---

CHANGELOG.md
tests/test_download.py

When I initially wrote the tests for the new `nf-core download --tower` functionality, there was little test coverage regarding container image detection. Therefore, I incorporated some functionality along in this line into a new test [`test_download_workflow_for_tower()`](https://github.com/nf-core/tools/commit/340c5195067809b27d1f1da5273d9d2ca99bafc3). 
Since I felt that testing everything with a real pipeline was preferable over a dummy pipeline with just one or two nicely formatted modules, I chose [rnaseq](https://nf-co.re/rnaseq/3.9) as a test subject. Since the test was never intended to actually download any of the detected images, I was not bothered about the pipeline comprising more than 30 modules. 
Initially, the test also performed as intended. But already two weeks later, we …

Download:  Fix unintentional downloading of containers in test

---

.github/workflows/create-lint-wf.yml
.github/workflows/create-test-lint-wf-template.yml
.github/workflows/create-test-wf.yml
.github/workflows/deploy-pypi.yml
.github/workflows/fix-linting.yml
.github/workflows/lint-code.yml
.github/workflows/pytest.yml
.github/workflows/sync.yml
.github/workflows/tools-api-docs-dev.yml
.github/workflows/tools-api-docs-release.yml
Dockerfile
README.md
nf_core/pipeline-template/.github/workflows/linting.yml

Bump Python 3.8 -> 3.11 for most CI tasks, plus docker base image.
This is a small measure to reduce the amount of CI jobs that we run.
I think it's vanishingly rare that anything fails only in a _middle_ version of Python - it's basically always one end of the range. So maybe it makes sense to only run tests on the extremes.
Might hopefully help with GitHub API rate limiting, and failing that should save a few grams of CO2.
Also, 3.11 is significantly faster than 3.8 so hopefully this alone will speed up CI a bit.

Only test min + max supported Python versions

---

CHANGELOG.md
nf_core/subworkflow-template/subworkflows/main.nf
nf_core/subworkflow-template/subworkflows/meta.yml
nf_core/subworkflow-template/tests/main.nf
nf_core/subworkflow-template/tests/test.yml

fix subworkflow template jinja variable for subworkflow name

---

CHANGELOG.md
nf_core/subworkflows/lint/main_nf.py

fix subworkflows linting: test passes if component.out.version is found in script

---

nf_core/list.py

Fixes #2414 
Ordering of `pipelines.json` `releases` section had been reversed. Change the lookup in tools to reflect this.

2414 nf core list only listing dev

---

CHANGELOG.md
nf_core/pipeline-template/lib/NfcoreTemplate.groovy

Currently the new `dump_parameters` added in v2.10 (#2425) only works on local files.
When using a remote publish dir such as s3, the json file will be written to a weird directory `s3 / path / to / outdir / params_{timestamp}.json` in the launchDir.
This small tweak first creates the parameter dump on the nextflow head machine as a hidden file and then moves it to the possibly remote outdir using the nextflow FilesEx helper to deal with the remote filesystems.

support remote paths in NfCoreTemplate:dump_parameters

---

CHANGELOG.md
nf_core/pipeline-template/.github/CONTRIBUTING.md
nf_core/pipeline-template/.github/PULL_REQUEST_TEMPLATE.md
nf_core/pipeline-template/nextflow.config

This addresses issue #2161.
Changes nextflow.config in the template to set `nextflow.enable.configProcessNamesValidation = false`. The `debug` profile can then be used to re-enable these warnings.
The pull request template is updated to include a "testing with `debug` profile" step.
I will also send a PR for the website (docs).

Ignore process selector warnings by default

---

nf_core/lint/nextflow_config.py
tests/lint/nextflow_config.py
tests/test_lint.py

This is the first part of  #1837.
See below comment: The following is no longer true (no way to "strike through" in github?):
It is not an ideal implementation, because it has to call `nextflow`, and only gets indirect indication of the failure due to the exit code. If there's a better way to reliably parse the config with python, I will use that instead- I hope someone can offer guidance on that if possible.
This is a draft PR, not ready for merge.

Add lint test to check existence of test profile

---

CHANGELOG.md
nf_core/modules/lint/main_nf.py
tests/modules/lint.py
tests/test_modules.py

This PR adds checks to see if there are spaces in the URLs used for container images - solving issue #2488 .
I'm adding tests for linting the container string, including the new check and the check for double quotes. (Similar to the tests for linting the process labels)

Check spaces in container links

---

CHANGELOG.md
nf_core/modules/lint/module_tests.py
nf_core/subworkflows/lint/subworkflow_tests.py

nf-test module/subworkflow lint

---

CHANGELOG.md
nf_core/pipeline-template/conf/modules.config

Add closure to multiqc ext.args

---

CHANGELOG.md
nf_core/bump_version.py

respect indentation on version bump

---

nf_core/modules/lint/module_tests.py
nf_core/subworkflows/lint/subworkflow_tests.py

linting tests requiring nf-test will be warnings instead of failures

---

.github/workflows/create-lint-wf.yml
.github/workflows/create-test-lint-wf-template.yml
.github/workflows/create-test-wf.yml
.github/workflows/deploy-pypi.yml
.github/workflows/fix-linting.yml
.github/workflows/lint-code.yml
.github/workflows/pytest.yml
.github/workflows/sync.yml
.github/workflows/tools-api-docs-dev.yml
.github/workflows/tools-api-docs-release.yml
CHANGELOG.md
README.md
mypy.ini
nf_core/pipeline-template/.github/workflows/linting.yml

update supported python version target to 3.12

run full test matrix only on PRs to the master branch,

---

CHANGELOG.md
nf_core/__main__.py
nf_core/components/create.py
nf_core/modules/create.py
nf_core/subworkflows/create.py
tests/modules/create.py
tests/subworkflows/create.py
tests/test_modules.py
tests/test_subworkflows.py

add --migrate-pytest option

---

CHANGELOG.md
README.md
nf_core/download.py

Unrelated to the bugfix, I have also made a small change to the documentation, since I recently had some odd issues with that one myself.

Download: Bugfix for AttributeError: 'ContainerError' object has no attribute 'absoluteURI'

---

CHANGELOG.md
nf_core/modules/lint/module_tests.py
nf_core/subworkflows/lint/subworkflow_tests.py
tests/test_modules.py
tests/test_subworkflows.py

Don't fail linting if md5sum for empty files are found in a stub test

---

CHANGELOG.md
nf_core/modules/modules_json.py

Sort the `installed_by` list in `modules.json`

---

CHANGELOG.md
nf_core/components/nfcore_component.py
nf_core/modules/lint/module_tests.py
nf_core/subworkflows/lint/subworkflow_tests.py
tests/modules/lint.py
tests/test_modules.py

All components used in chained nf-tests, defined with `script` in the file `main.nf.test` must be added to the tags.
Close #2559

nf-test linting tags

---

nf_core/modules/lint/meta_yml.py

Until we have figured out a better way to handle it in the meta.yml. This should at least avoid some confusion.

don't warn about missing `meta` value in meta.yml

---

CHANGELOG.md
nf_core/download.py
tests/test_download.py

This PR adds the `docker://` prefix to absolute URIs as well. 
While this will result in an error for prebuild Singularity images (and was thus once omitted deliberately), practical experience has demonstrated that the conversion of a Docker OCI is more common in nf-core pipelines.
It is a trade-off between Docker and Singularity support, however essentially all container-specifications I could find in custom, local modules refer to Docker images. Therefore, this change should increase the number of "_just works_" downloads.
It is also accompanied by two more tests that pull a tiny 3.5MB Docker OCI and convert it with `singularity build`.

Download: Add docker prefix for absolute container URIs as well.

---

.github/workflows/create-lint-wf.yml
.github/workflows/create-test-lint-wf-template.yml
.github/workflows/create-test-wf.yml
.github/workflows/deploy-pypi.yml
.github/workflows/fix-linting.yml
.github/workflows/lint-code.yml
.github/workflows/pytest.yml
.github/workflows/sync.yml
.github/workflows/tools-api-docs-dev.yml
.github/workflows/tools-api-docs-release.yml
CHANGELOG.md
README.md
nf_core/pipeline-template/.github/workflows/linting.yml

Due to some problems with changes in the mock functions (and problems installing the dev requirements locally).

downgrade to python 3.11 in the tests

---

CHANGELOG.md
nf_core/pipeline-template/nextflow.config

This option is about to be stripped out of Nextflow itself, so we need to remove it from the nf-core template.
See https://github.com/nextflow-io/nextflow/pull/4596
Should maybe consider adding a lint test that checks if the option is present? Though I don't think it'll trigger any errors or anything if left in, just be silently ignored. Setting `docker.fooNotexists = true` in a config seems to have no effect.

Remove docker.userEmulation

---

CHANGELOG.md
nf_core/modules/modules_json.py

only dump modules.json when it is modified

---

nf_core/module-template/tests/main.nf.test

adding positional input required for nf-test to template

fix positional input in template

---

.gitpod.yml
CHANGELOG.md
nf_core/pipeline-template/.gitpod.yml

Same as in https://github.com/nf-core/modules/pull/4682

use pdiff also on gitpod for nf-test

---

.github/renovate.json5
CHANGELOG.md

Fixes a few things:
- Ignore Dockerfiles(and conda) in modules in pipeline template
- Add python pep440 versioning for main Dockerfile
- Set renovate docker registry to docker.io (https://developer.mend.io/github/nf-core/tools/-/job/502f6333-fe00-4194-95ca-6c8237128324)

Fix Renovate Docker

---

CHANGELOG.md
README.md
nf_core/__main__.py
requirements-dev.txt
requirements.txt

Add support for [Trogon](https://github.com/Textualize/trogon) - a TUI for the click CLI interface
https://github.com/nf-core/tools/assets/465550/3a20001d-a979-4172-9f34-2a2df5fb177f

Add support for Click TUI with Trogon

---

CHANGELOG.md
nf_core/modules/lint/environment_yml.py

Close https://github.com/nf-core/tools/issues/2515
Linting that the name matches the one in `meta.yml` was done with #2490 
All names were changed to lowercase with https://github.com/nf-core/modules/pull/4332

Linting: environment.yml name must be lowercase

---

CHANGELOG.md
nf_core/__main__.py
nf_core/components/lint/__init__.py
nf_core/lint/__init__.py
nf_core/lint_utils.py
nf_core/pipeline-template/modules.json
nf_core/pipeline-template/modules/nf-core/custom/dumpsoftwareversions/environment.yml
nf_core/pipeline-template/modules/nf-core/custom/dumpsoftwareversions/main.nf
nf_core/pipeline-template/modules/nf-core/custom/dumpsoftwareversions/tests/main.nf.test
nf_core/pipeline-template/modules/nf-core/custom/dumpsoftwareversions/tests/main.nf.test.snap
nf_core/pipeline-template/modules/nf-core/fastqc/tests/main.nf.test
nf_core/pipeline-template/modules/nf-core/fastqc/tests/main.nf.test.snap
nf_core/pipeline-template/modules/nf-core/multiqc/environment.yml
nf_core/pipeline-template/modules/nf-core/multiqc/main.nf
nf_core/pipeline-template/modules/nf-core/multiqc/meta.yml
nf_core/pipeline-template/modules/nf-core/multiqc/tests/main.nf.test
nf_core/pipeline-template/modules/nf-core/multiqc/tests/main.nf.test.snap
tests/test_cli.py

Close https://github.com/nf-core/tools/issues/2671

Linting: linting a pipeline also lints the installed subworkflows

---

CHANGELOG.md
nf_core/pipeline-template/lib/WorkflowMain.groovy
nf_core/pipeline-template/main.nf

Close https://github.com/nf-core/tools/issues/2643

Template: add function to check `-profile` is well formatted

---

CHANGELOG.md
nf_core/pipeline-template/workflows/pipeline.nf

<3 to @mribeirodantas for the solution on the Nextflow discourse!

Add new error message pointing to docs when 'requirement exceeds available memory' error message

---

CHANGELOG.md
nf_core/lint/nextflow_config.py
tests/lint/nextflow_config.py
tests/test_lint.py

Close https://github.com/nf-core/tools/issues/1954

Linting: lint `nextflow.config` default values match the ones specified in `nextflow_schema.json`

---

nf_core/lint/__init__.py

Fix a bug introduced with #2677

Linting: fix bug when linting subworkflows from pipeline lint [skip changelog]

---

CHANGELOG.md
nf_core/lint/nextflow_config.py

Handle default value read from nextflow schema as a `float` when the type is `number`.

Linting: Handle default values of type number from nextflow schema

---

.github/renovate.json5
CHANGELOG.md

Following this: https://docs.renovatebot.com/configuration-options/#gitignoredauthors, otherwise renovate doesn't update open PRs after the bot has updated the changelog

Ignore nf-core-bot in renovate PRs

---

CHANGELOG.md
nf_core/pipeline-template/.github/workflows/download_pipeline.yml

When writing the CI test that tested nf-core download on the current pipeline, I intended to run the test for any push on a branch underlying an active PR to _dev_. This required that the CI action would dynamically determine the branch name, for which I naively queried `/refs/heads/`. 
However, I now learned [that resolving the branch name is a bit more complex than I initially thought](https://mirrors.edge.kernel.org/pub/software/scm/git/docs/gitrevisions.html), since there may be a `HEAD`, `FETCH_HEAD`, `ORIG_HEAD`, `MERGE_HEAD` and `CHERRY_PICK_HEAD` and [sadly branch determination already failed in practice](https://github.com/nf-core/taxprofiler/actions/runs/7742219884) (cc @sofstam ) because a `MERGE_HEAD` existed in addition to `HEAD`.
Since it is quite difficult to determine the …

Pipeline template: Fix download test CI

---

CHANGELOG.md
nf_core/pipeline-template/.github/workflows/ci.yml

Add Github Action to automatically cleanup ubuntu-latest runners to fix runner running out of diskspace errors

---

nf_core/components/update.py
tests/modules/update.py
tests/test_modules.py

Modules: keep custom *.config files also after `nf-core modules/subworkflows update`

---

.github/workflows/pytest.yml
CHANGELOG.md
nf_core/download.py
tests/test_download.py

This addition to `nf-core download` addresses #2751, #2644, [demultiplex#164](https://github.com/nf-core/demultiplex/issues/164) and multiple Slack issues: [1](https://nfcore.slack.com/archives/CGFUX04HZ/p1701112794985919),[2](https://nfcore.slack.com/archives/CE5LG7WMB/p1707923858337779),[3](https://nfcore.slack.com/archives/CGFUX04HZ/p1708068849565389).
Dropping the hardcoded registry from the modules in favour of the flexible config parameters `apptainer.registry`, `docker.registry`, `podman.registry` and `singularity.registry` was initiated by Seqera, but so far Nextflow has not received concordant updates to also resolve to images downloaded from alternative registries as a fallback.
The code in this PR creates a bunch of symlinks to the downloaded images to ensure that they are …

nf-core download: Create container image symlinks so images are still found, even if registry config diverges.

---

.github/actions/create-lint-wf/action.yml
.github/workflows/create-test-lint-wf-template.yml
.github/workflows/create-test-wf.yml
.github/workflows/pytest.yml
.github/workflows/rich-codex.yml
.github/workflows/sync.yml
CHANGELOG.md

setup-nextflow v2 has released. Update the CI to take advantage of the new API.

Update CI to use nf-core/setup-nextflow v2

---

.pre-commit-config.yaml
CHANGELOG.md
nf_core/pipeline-template/.pre-commit-config.yaml

not the most straight forward way, but the only way until the prettier-mirror is updated from 3.1.0
NB: Renovate doesn't check `additional_dependencies` yet, so we need to update this by hand.

update prettier to 3.2.5

---

CHANGELOG.md
nf_core/utils.py

#2833. Trying to only match assignments of params in `main.nf` and **not** references like, for instance, `params.aligner == "bwa-mem"`.
I tested this solution locally on [this](https://github.com/maxulysse/nf-core_sarek/blob/1bf5222acf8f1d83c374fe92307c97c0f37255b1/main.nf#L165-L166) version of Sarek.

Linting params in main.nf

---

nf_core/gitpod/gitpod.Dockerfile

This should allow faster opening times in codespaces and on gitpod 🤞🏻

optimize layers in dockerfile

---

CHANGELOG.md
nf_core/lint/nextflow_config.py
nf_core/pipeline-template/main.nf
tests/lint/nextflow_config.py
tests/test_lint.py

Trying to add some tests for the bug reported in #2833.
I locally tested that the test `test_allow_params_reference_in_main_nf` fails (as desired) with the former [regexp](https://github.com/nf-core/tools/blob/9eac5e9b33a4b86a5228e950a8c8fd16765f4a85/nf_core/utils.py#L291) which caused the bug  #2833.

Add tests for assignment and referencing of params in main.nf

---

CHANGELOG.md
nf_core/pipeline-template/subworkflows/local/utils_nfcore_pipeline_pipeline/main.nf

The following snippet was removed after v2.12.1 when we refactored the pipeline template to remove the `lib/` directory in favour of more granular `utils_*` subworkflows
https://github.com/nf-core/tools/blob/776089ac0e42f1fce9084182eba3b4ca0ed405e9/nf_core/pipeline-template/workflows/pipeline.nf#L130-L135
This PR adds it back in with the aim of catching any error and redirecting users to a single page where we can maintain a list of common errors encountered by users.

Template: Link to troubleshooting docs when pipeline fails

---

CHANGELOG.md
nf_core/pipeline-template/.github/workflows/download_pipeline.yml

- Apparently, not all nf-core pipelines fully support stub runs.  Since the `download_pipeline.yml` GitHub Actions workflow tested the pipeline in `-stub`/`-stub-run` mode, this test failed on some pipeline repositories. With this update, the workflow will still attempt running the downloaded pipeline with the -stub option first, but if that fails, it tries to run the pipeline without the -stub option. _Mind that any step failure will trigger the regular run, whether it is related to the `-stub` parameter or not._
- Additionally, I have added the `edited` and `synchronized` types to the event trigger, so the test is automatically rerun, if further changes to `dev` are made while the PR to `master` is open.

Add fallback to Download Pipeline Workflow

---

CHANGELOG.md
nf_core/pipeline-template/.github/workflows/download_pipeline.yml

While testing raredisease pipeline, download_pipeline workflow failed pipeline due to lack of storage space, and adding a cleanup step to the workflow fixed it. So I propose adding this step to the template. 
https://github.com/nf-core/raredisease/actions/runs/8159070586/job/22302477254

Add cleanup step to download pipeline workflow

---

CHANGELOG.md
nf_core/schema.py

Fix schema docs console output truncating

---

CHANGELOG.md
nf_core/__main__.py

Quick attempt at a fix for https://github.com/nf-core/tools/issues/2759.
EDIT: New approach is summarized in the main commit message body. Original PR history preserved below:
---
I went for the naive approach and simply converted all occurrences of tool/subworkflow names to lowercase, whenever they were being used as an input to a function.
A cleaner solution might be to use a decorator for this, but I couldn't find an option for click ([token normalization](https://click.palletsprojects.com/en/8.1.x/advanced/#token-normalization) only appears to work on choices or options, not arguments). 
Alternatively, a check could be implemented inside the various functions of the ComponentCommand class, but I must admit I felt a bit lost trying to understand the overall structure of how these are …

Make module/subworkflow names case insensitive

---

CHANGELOG.md
nf_core/components/components_command.py
nf_core/lint/__init__.py
nf_core/modules/modules_json.py
nf_core/schema.py
tests/test_cli.py
tests/test_schema.py
tests/test_sync.py

Closes #2890  
fix: assertions for called_with/called_once_with were silently returning mocks before 3.12. Broken in 3.12.

Fix incorrect assertions for called_with on mocks

---

CHANGELOG.md
nf_core/schema.py
tests/test_schema.py

Hi 👋🏽  I've came to fix an issue but didn't realise about the dev branch until PR time, I've missed that detail in CONTRIBUTORS file, so the issue was already fixed with the `str` cast doing the trick.
I kept the PR as I think using `as_posix` is generally more correct for Paths, but maybe I'm missing something for this use case. First time around here.
Also adding a test since it wasn't tested the particular error.
Feel free to drop the PR in case is not necessary.
Thanks.

Get name for parent path to create schema_filename

---

CHANGELOG.md
nf_core/pipeline-template/nextflow.config

As this should be supported now though here: https://github.com/nf-core/configs/pull/674
Meaning devs don't need to touch the section of the config, and users can add configs when they need

Activate pipeline institutional configs in template

---

nf_core/pipeline-template/docs/usage.md
nf_core/pipeline-template/nextflow.config

Add a config profile in the template to use Wave.
> [!NOTE]
> Requires `24.03.0-edge`! I considered bumping `nextflowVersion` to `24.04.0` but it feels a bit overkill when the vast majority of end users will not be using `-profile wave`. I'm inclined to mention this in the docs but not encode it in the config. Please shout if you disagree.
Will need more docs about Wave, but that's a larger effort, probably for the website repo.

Added `-profile wave` to the template.

---

CHANGELOG.md
nf_core/pipeline-template/subworkflows/local/utils_nfcore_pipeline_pipeline/main.nf

Handle Multiple DOIs from manifest

---

CHANGELOG.md
nf_core/pipeline-template/nextflow.config

Template config: `conda.channels`, not `channels`

---

CHANGELOG.md
nf_core/modules/modules_utils.py

As per the document linked in the function description, valid git URLs may begin with ssh:// (and ftp://). This PR extends the nf-core tool to clone module repositories that are of these forms.
Before this fix, running a command like
```bash
nf-core modules list remote \
--git-remote ssh://git-codecommit.us-east-2.amazonaws.com/v1/repos/modules.git
```
would pass the string `ssh://git-codecommit.us-east-2.amazonaws.com/v1/repos/modules.git` to the `repo_full_name_from_remote` function which would return the repo full name `/v1/repos/modules`, which would be passed to the `git clone` subshell to invoke the command trying to `git clone` into the root of the filesystem, which is going to fail for almost all users:
```bash
git clone -v --progress -- \ …
```

Components: Handle extended set of git path prefixes

---

CHANGELOG.md
nf_core/modules/lint/__init__.py
nf_core/subworkflows/lint/__init__.py
nf_core/synced_repo.py

Fix linting tests failing when a subworkflow is not up to date but matches the remote.
Error reported: https://github.com/genomic-medicine-sweden/meta-val/actions/runs/8966887756/job/24623288271?pr=15

Components: set correct sha before running component lint tests

---

CHANGELOG.md
nf_core/pipeline-template/.editorconfig

I think we don't need to ignore README.md as it's covered by the md on the following line.

Template - Update .editorconfig

---

CHANGELOG.md
nf_core/lint/files_unchanged.py

Hopefully should resolve more of the linting issues

Less strict logo comparison

---

CHANGELOG.md
nf_core/pipeline-template/conf/test.config
nf_core/pipeline-template/conf/test_full.config
nf_core/pipeline-template/nextflow.config
nf_core/pipeline-template/nextflow_schema.json

https://nfcore.slack.com/archives/C043UU89KKQ/p1713940102697309

Adds test data base path to classic test configs for more easily switching between test data location

---

CHANGELOG.md
nf_core/pipeline-template/nextflow.config

- Adds the bash option no clobber
- Put each option on it's own line and explain what it does.

Add no clobber and put bash options on their own line

---

CHANGELOG.md
nf_core/utils.py

close https://github.com/nf-core/tools/issues/3002

return directory if base_dir is the root directory

---

CHANGELOG.md
nf_core/components/create.py
nf_core/module-template/tests/main.nf.test.j2
nf_core/modules/lint/module_tests.py
nf_core/subworkflow-template/tests/main.nf.test.j2
nf_core/subworkflows/lint/subworkflow_tests.py

Fixes #2979
In custom modules repositories, the `main.nf.test` file contains the `modules_nfcore` tag (which doesn't really make sense). This PR updates this by doing the following steps:
1. Update `nf-core modules create` and `nf-core subworkflows create` to add the `modules_<organization` tag instead of the `modules_nfcore` tag
2. Update `nf-core modules lint` to make sure it passes the linting check

Add organization to `main.nf.test` tag instead of using `nfcore`

---

CHANGELOG.md
nf_core/pipeline-template/.github/workflows/linting.yml
nf_core/pipeline-template/.github/workflows/template_version_comment.yml

Check the pipeline template version from `.nf-core.yml`. 
Run nf-core linting with that version.
If the template version is outdated, post a comment to the PR warning about a new version available.
Tested with the nf-core/testpipeline: https://github.com/nf-core/testpipeline/pull/84
Close https://github.com/nf-core/tools/issues/2966

Template: Lint pipelines with the nf-core template version and post comment if it is outdated

---

CHANGELOG.md
nf_core/pipelines/create/__init__.py
nf_core/pipelines/create/basicdetails.py
nf_core/pipelines/create/utils.py

Close #2963 
Use validation context from pydantic with Model initialization. See docs [here](https://docs.pydantic.dev/latest/concepts/validators/#using-validation-context-with-basemodel-initialization)
Adding a global variable was the only option to access the pipeline type from validation, where the app is not available, so we can't use class attributes.

Create: allow more special characters on the pipeline name for non-nf-core pipelines

---

CHANGELOG.md
nf_core/modules/lint/main_nf.py

Tried to do this with GitHub Copilot Workspaces but it failed 😅 
As I was looking at the code anyway I could see the fix so figured I would put it manually.
Closes https://github.com/nf-core/tools/issues/3009
Untested, done in web browser only.

Conda module linting: Include package name in log file

---

CHANGELOG.md
nf_core/__main__.py

Let top-level pipeline commands work to avoid breaking pipelines CI

Add warning deprecation message to top-level commands

---

CHANGELOG.md
nf_core/__main__.py
nf_core/commands_modules.py
nf_core/commands_pipelines.py
nf_core/commands_subworkflows.py

move pipeline commands to functions to avoid duplication
follow up #3036

move pipeline commands to functions to avoid duplication

---

CHANGELOG.md
nf_core/modules/lint/environment_yml.py
nf_core/modules/lint/meta_yml.py

fixes currently broken mypy linting due to update jsonschema dependency

handle new jsonschema error type

---

nf_core/pipeline-template/docs/usage.md

There was additional documentation which was legacy and not required now. 
Users should refer to the `azurebatch` specific profile and/or the Nextflow documentation for relevant features.

Remove Azure specific documentation which is no longer required

---

CHANGELOG.md
nf_core/__main__.py

Fixes https://github.com/nf-core/tools/issues/3068

Fix number of arguments for pipelines_create within the command_create function

---

CHANGELOG.md
nf_core/components/create.py
nf_core/modules/lint/main_nf.py

Fix module linting warning for process_high_memory

---

CHANGELOG.md
nf_core/pipelines/create/utils.py

Close https://github.com/nf-core/tools/issues/3067

Pipelines: allow numbers in custom pipeline name

---

.github/workflows/regenerate-snapshots.yml
.github/workflows/update-textual-snapshots.yml
CHANGELOG.md
CONTRIBUTING.md

Add action of @nf-core-bot to update Textual snapshots.
Add documentation of the uses of @nf-core-bot to the `CONTRIBUTING.md` docs.

Add bot action to update textual snapshots and write bot documentation

---

nf_core/modules/lint/main_nf.py

close https://github.com/nf-core/tools/issues/3010

Components: Modules : allow module lables between double quotes

---

CHANGELOG.md
nf_core/components/components_utils.py

Changing `match` to `search` will look for the component name even if the `include` keyword is not at the beginning of the line. This is to allow spaces for cases such as the following, where we have indentation.
```
if ( params.aligner == "clustalo/align" ) {
include { CLUSTALO_ALIGN as ALIGNER } from '../../../modules/mirpedrol/clustalo/align/main'
} else if ( params.aligner == "famsa/align" ) {
include { FAMSA_ALIGN    as ALIGNER } from '../../../modules/mirpedrol/famsa/align/main'
}
```

Components: allow spaces at the betinning of include statements

---

CHANGELOG.md
nf_core/pipelines/create/create.py

When `nf-core pipelines sync` was run from the pipeline root directory, a new directory was created and all pipeline files deleted. This overrides the output directory to use the same used by the sync command when the template pipeline is created.

fix syncing a pipeline from current directory

---

CHANGELOG.md
nf_core/components/nfcore_component.py

When the path provided to the linting command contains the name of the component, the lining will fail.
This was reported by `nf-core/isoseq`, which includes a module with the same name as the pipeline, `isoseq`.
See [Slack discussion](https://nfcore.slack.com/archives/CE5LG7WMB/p1724653773276939)

Linting: handle cases where the directory path contains the name of the component

---

nf_core/components/nfcore_component.py
tests/modules/test_lint.py

The linting on the current `dev` branch was failing with this error when it encountered a module where the tool and the subtool have the same name (`tabix/tabix`, `happy/happy`...):
```
LookupError: Could not find branch information for component 'happy/happy/happy'.Please remove the 'modules.json' and rerun the command to recreate it
```
@awgymer and I debugged and solved this like this. 
This PR checks if the tool and subtool have the same name and in that case it will move the org index one back so it will always pick the right name for the organization.

Fix issue where tool and subtool have the same name

---

CHANGELOG.md
nf_core/pipeline-template/.github/workflows/release-announcements.yml
tests/modules/test_lint.py

Strip hyphens from hashtags for mastodon compatibiluty

---

nf_core/__main__.py
nf_core/pipelines/create/create.py
nf_core/pipelines/download.py
nf_core/pipelines/schema.py
nf_core/pipelines/sync.py
nf_core/utils.py

The old `nf-core sync` command was crashing, now it is fixed.
The new `nf-core pipelines sync` command was not taking into account the template information from `.nf-core.yml` and was also crashing for pipelines without the template information. Now it uses this info to sync a pipeline.
Testing PRs syncing nf-core and custom pipelines can be found here: [nf-core](https://github.com/mirpedrol/plainnfcore/pull/3) and [custom](https://github.com/mirpedrol/customnonnfcoresync/pull/2/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5) and [custom with a new modification](https://github.com/mirpedrol/customnofastqc/pull/1/files#diff-2343acd64c297a361acf758556f3f7f7d9c5862a6841db803937b2eb5aaa1ec7)

Fix nf-core pipelines sync

---

CHANGELOG.md
nf_core/pipeline-template/.github/workflows/download_pipeline.yml

The Download Test fails, if there are obvious issues while downloading a pipeline, e.g. `nf-core pipeline download` errors out. 
But it did not assert that all required containers were downloaded.  Since it is impossible to take Github Action Runners offline for a certain step, it is quite difficult to test, if a pipeline would actually run offline.
But because Nextflow will pull container images at runtime that have not been downloaded correctly, the number of container images in the `$NXF_SINGULARITY_CACHEDIR` will change and this can be captured in the test.
[I have been testing that action in my fork of the testpipeline](https://github.com/MatthiasZepper/nfcore-testpipeline/actions/runs/11050968634) after manually removing the `{%raw%}` markup, but maybe there is a better way?
**PS: I …

Pipeline template: Modify download test action to capture the number of containers

---

.gitpod.yml
CHANGELOG.md
nf_core/pipeline-template/.github/workflows/linting.yml
setup.py

The action tries to read the `.nf-core.yaml` file but it should be `.nf-core.yml`. I also updated the pietrobolcato/action-read-yaml action version because there was a bug in there

Fix a typo in the linting action

---

CHANGELOG.md
nf_core/pipeline-template/.github/workflows/ci.yml

TEMPLATE: Parallelize pipeline GHA tests over docker/conda/singularity

---

CHANGELOG.md
nf_core/pipeline-template/workflows/pipeline.nf

Why going for `pipeline` when we have shortname?

TEMPLATE: Keep pipeline name in version.yml file

---

CHANGELOG.md
nf_core/pipeline-template/nextflow.config

I'd rather we use {{ name }} that way we see in the script what we have. If we have manifest.name we assume that people are using a name that org/pipeline, which should work for nf-core pipeline, but might not work for all.

Template: Do not assume pipeline name is url

---

.github/.coveragerc
.github/workflows/pytest.yml
CHANGELOG.md
nf_core/__main__.py
tests/test_cli.py

Fixes #3234 
not sure if we want it also in `pipelines create`

add `--dir/-d` option to schema commands

---

CHANGELOG.md
nf_core/pipeline-template/.github/workflows/download_pipeline.yml
nf_core/pipelines/download.py
tests/data/mock_module_containers/modules/mock_seqera_container.nf
tests/pipelines/test_download.py

This PR extends the tests so that Seqera Container support is tested for. It also tweaks the symlink function to support the unconventional registry that Seqera Containers uses. 
This is a basic patch. It does neither add `oras://` support nor does it fix the issue with the container priority resolution (#3179). For modules using Seqera containers, nf-core download will always download both containers, the native Singularity one and convert the Docker container to Singularity as well.

Download: Seqera container support - Patch 1

---

tests/data/mock_module_containers/modules/mock_seqera_container.nf

Add an example of Seqera Containers usage in a module (see https://nfcore.slack.com/archives/CE5LG7WMB/p1729699806378999?thread_ts=1729694853.053389&cid=CE5LG7WMB)

Seqera containers example

---

CHANGELOG.md
nf_core/synced_repo.py

Close https://github.com/nf-core/tools/issues/3263

General: Add hint to solve git errors with a synced repo

---

.github/workflows/create-test-lint-wf-template.yml
CHANGELOG.md
nf_core/pipeline-template/conf/modules.config
nf_core/pipeline-template/main.nf
nf_core/pipeline-template/nextflow.config
nf_core/pipeline-template/subworkflows/local/utils_nfcore_pipeline_pipeline/main.nf
nf_core/pipeline-template/workflows/pipeline.nf

close https://github.com/nf-core/tools/issues/3252

General: Run pre-commit when testing linting the template pipeline

---

CHANGELOG.md
nf_core/modules/lint/main_nf.py

Fix an issue where the regexs used to find where each section starts in the modules linter aren't robust enough and end up matching the wrong things.
add something like `container 'test_typescript:3.0.0'` to a module and you'll see these tests fail because the regex `r"script\s*:"` matches `script:` in `test_typescript:`

Fix module section linter regex

---

CHANGELOG.md
nf_core/components/nfcore_component.py
nf_core/modules/lint/main_nf.py

This PR is to fix an issue where running `nf-core modules lint -a -k meta_yml` always has failing tests due to `module.process_name` always being `""` in [nfcore_component.py](https://github.com/nf-core/tools/blob/main/nf_core/components/nfcore_component.py).
It gets initialized to `""` then eventually gets updated in `main_nf` but not in any others which results in the failed `meta_yml` tests unless `-k main_nf` is specified as well
I've added a simple function for the component to set it's `process_name` itself rather than it being set in other separate parts of the code. It uses the same regex expression that `main_nf.py` uses

Fix meta_yml linting error

---

CHANGELOG.md
nf_core/components/components_utils.py

This tooling works with non-nf-core pipelines, so the language should reflect that.

Make prompt less nf-core specific

---

CHANGELOG.md
nf_core/pipeline-template/.github/workflows/awsfulltest.yml

Thought this was already merged...

Be more verbose in approval check action

---

nf_core/pipelines/bump_version.py
nf_core/utils.py

Fix ro crate in bump version

---

CHANGELOG.md
nf_core/pipeline-template/nextflow.config

Fixing a jinja template error
Also reverting #3301 until we add the linting described in https://github.com/nf-core/tools/issues/2508

fix including modules.config

---

CHANGELOG.md
nf_core/pipelines/rocrate.py

Close https://github.com/nf-core/tools/issues/3361

Properly parse the names form `manifest.contributors`

---

CHANGELOG.md
nf_core/pipeline-template/LICENSE
nf_core/pipelines/lint/files_unchanged.py

lint LICENSE file is a warning instead of a failure

Template: set LICENSE copyright to nf-core community

---

CHANGELOG.md
nf_core/modules/modules_utils.py
tests/modules/test_modules_utils.py

Close https://github.com/nf-core/tools/issues/3382

Modules: fix bump-versions: only append module name if it is a dir and contains main.nf

---

CHANGELOG.md
nf_core/pipelines/schema.py
tests/pipelines/test_schema.py

I found a case where we were using the following schema structure:
```
"oneOf": [{ "required": ["param_1"] }, { "required": ["param_2", "param_3"] }],
```
This was failing because our listing wasn't removing the `required` instances inside the `oneOf` when validating default parameter values. 
This PR allows having these cases and also prints the complete error message on debug mode, as the `e.message` text was not helpful in identifying the problem.

Parameters schema validation: allow oneOf, anyOf and allOf with `required`

---

.gitpod.yml
CHANGELOG.md
nf_core/pipeline-template/conf/test.config
nf_core/pipelines/create/create.py
nf_core/pipelines/lint_utils.py
setup.py

Pre-commit was not running when creating a pipeline (because there isn't a git repo yet at the point of creating the pipeline), but it is running when we use `nf-core pipelines sync` and create a new pipeline in the `TEMPLATE` branch
Should fix https://github.com/nf-core/tools/issues/3372

run pre-comit when rendering template for pipelines sync

---

CHANGELOG.md
nf_core/pipelines/download.py
nf_core/utils.py
tests/pipelines/test_download.py
tests/test_utils.py

Supersedes #2906 
This is to allow downloading a specific commit of a pipeline, instead of only a branch / tag.
As @ewels suggested in the original pull-request, I only check the commit once we know it's neither a branch nor a tag. It's a single extra query, and it won't download the whole list of possible commits.
I could reuse the tests @fellen31 wrote. Credits to them

Allow `nf-core pipelines download -r` to download commits

---

CHANGELOG.md
nf_core/pipeline-template/.github/workflows/download_pipeline.yml

In #3351, I refactored the nf-core pipelines download test to use `$GITHUB_OUTPUT` instead of the environment for improved security. 
However, splitting the test into two independent jobs introduced the possibility of them running on different runners, which resulted in the second job lacking the correct setup. I have now resolved this issue by ensuring that all necessary setup setups are retained within the main job. Only the potentially vulnerable step remains isolated from the main job, but also does not require any setup.
[The new version of the CI pipeline was successfully tested](https://github.com/MatthiasZepper/nfcore-testpipeline/actions/runs/12674971883/job/35324917556) in [my Test pipeline repository](https://github.com/MatthiasZepper/nfcore-testpipeline). Any further …

Pipeline template: Fix the faulty Download test / GitHub action

---

CHANGELOG.md
nf_core/pipelines/lint/files_unchanged.py
nf_core/pipelines/rocrate.py
nf_core/pipelines/sync.py
nf_core/utils.py

close https://github.com/nf-core/tools/issues/3373

General: manifest.author is not required anymore

---

CHANGELOG.md
docs/api/_src/pipeline_lint_tests/local_component_structure.md
nf_core/components/components_command.py
nf_core/components/create.py
nf_core/components/lint/__init__.py
nf_core/components/nfcore_component.py
nf_core/modules/lint/__init__.py
nf_core/modules/lint/environment_yml.py
nf_core/modules/lint/meta_yml.py
nf_core/modules/lint/module_tests.py
nf_core/pipelines/lint/__init__.py
nf_core/pipelines/lint/local_component_structure.py
nf_core/subworkflows/lint/__init__.py
nf_core/subworkflows/lint/meta_yml.py
nf_core/subworkflows/lint/subworkflow_tests.py
nf_core/utils.py
tests/modules/test_create.py
tests/modules/test_lint.py
tests/pipelines/lint/test_local_component_structure.py
tests/subworkflows/test_create.py
tests/subworkflows/test_lint.py

1929: local modules use remote format from template

---

CHANGELOG.md
nf_core/module-template/meta.yml
nf_core/modules/lint/__init__.py

- add `ontologies` to meta.yml if not present
- fix BAM URL in modules template

Linting: EDAM ontology fixes

---

nf_core/pipeline-template/.github/workflows/ci.yml

The if condition handling push events is no longer needed since the workflow no longer triggers on push events.
Resolves issue #3455

Cleanup: Removed Redundant if Condition

---

CHANGELOG.md
nf_core/components/components_utils.py
tests/components/test_components_utils.py

Add the ability to configure the default modules repo, branch, and name as environment variables.
Context:
Within our org, we're looking to build an nf-core-style module repository in Gitlab - this is possible with the command line flags, but it's a hassle to set `--git-branch` every time we run a module command. 
This PR adds the ability to set `NF_CORE_MODULES_NAME`, `NF_CORE_MODULES_REMOTE`, and `NF_CORE_MODULES_DEFAULT_BRANCH` as environment variables, defaulting to the existing constants for those values if the variables are not set.
I took a quick look for other similar constants, but didn't see any, nor did I find an existing config file or object - if I missed something, let me know and I'll be happy to update this.

Configure the default module repository, branch, and path from environment variables.

---

CHANGELOG.md
nf_core/pipeline-template/.github/workflows/awsfulltest.yml
nf_core/pipelines/lint/actions_awsfulltest.py

Close https://github.com/nf-core/tools/issues/3462

Template: Run awsfulltest after release, and with dev revision on PRs to master

---

.github/workflows/create-lint-wf.yml
.github/workflows/create-test-lint-wf-template.yml
.github/workflows/create-test-wf.yml
.github/workflows/lint-code.yml
.github/workflows/pytest.yml
CHANGELOG.md

This should automerge and reduce the number of PRs that have to be manually approved. 
I'm not sure how it could interact with the changelog action though.

ci: Run checks on renovate branches to avoid creating and merging PRs

---

.github/workflows/test_offline_configs.yml
CHANGELOG.md

Add offline configs test action

---

.github/workflows/nextflow-source-test.yml
CHANGELOG.md

Build Nextflow from source, create a pipeline from dev and run it. If there's a failure, email Slack.
Untested, because this is GitHub actions.

GitHub action for nightly tests with Nextflow from source

---

CHANGELOG.md
nf_core/test_datasets/search.py

Changes the output table of the `test-datasets search` sub-command to wrap long one-word rows to essentially avoid ellipsis-cutting URLs.
This change was suggested in [this website PR comment](https://github.com/nf-core/website/pull/3317#issuecomment-2875936343). 
For copy-pasting urls the `-u` flag is still more suitable
Before Changes:
```
% nf-core test-datasets search -b mag minigut_reads
<nf-core logo cut out ...>
Searching files on branch:  mag
┌──────────────────┬────────────────────────────────────────┐
│ File Name:       │ test_data/minigut_reads.fastq.gz       │
│ Nextflow Import: │ params.pipelines_testdata_base_path +  │
│                  │ "test_data/minigut_reads.fastq.gz"     │
│ Download Link:   │ https://raw.githubusercontent.com/nf-… │ …
```

Add row wrapping for long lines in search result table

---

CHANGELOG.md
nf_core/test_datasets/list.py

Changes to `test-datasets list` subcommand to wrap long lines with urls / file paths in the output table.

Add wrapping long lines in list table

---

CHANGELOG.md
nf_core/pipeline-template/conf/base.config
nf_core/pipeline-template/nextflow.config

When a pipeline's whole Linux process tree is in the process of being snapshotted via Fusion Snapshots and encounters an unrecoverable error the Fusion Snapshots runtime emits a specific exit code (175) to signal that to Nextflow.
This PR makes sure that users creating pipelines out of the template are including the exit code in their retry strategy.

Make jobs automatically resubmit for exit code 175

---

CHANGELOG.md
nf_core/pipeline-template/nf-test.config
pyproject.toml
tests/pipelines/test_create_app.py

Based on work by @jfy133 and @maxulysse in https://nfcore.slack.com/archives/CE5LG7WMB/p1749121241197419?thread_ts=1749112128.280199&cid=CE5LG7WMB

TEMPLATE: fix nf-test scope to ignore nf-core module/swf tests

---

.github/workflows/changelog.yml

the old approach wrote a multi-line string into GITHUB_OUTPUT which is now failing. 
Instead, I just check if the output of git diff is empty now or not.

changelog bot: don't write the output from git diff into GITHUB_OUTPUT

---

CHANGELOG.md
nf_core/pipelines/lint/rocrate_readme_sync.py
tests/pipelines/lint/test_rocrate_readme_sync.py

The error message for `RO-Crate` lint was not updated: `nf-core lint --fix rocrate_readme_sync` instead `nf-core pipelines lint --fix rocrate_readme_sync`

Update error message for rocrate_readme_sync

---

CHANGELOG.md
nf_core/utils.py
tests/test_utils.py

Close https://github.com/nf-core/tools/issues/3672
https://regex101.com/r/xuh0TQ/1
The expressions that contain spaces are not read as if they were param variables.

don't read param expressions with spaces as params

---

.github/snapshots/adaptivecard.nf.test.snap
.github/snapshots/changelog.nf.test.snap
.github/snapshots/ci.nf.test.snap
.github/snapshots/citations.nf.test.snap
.github/snapshots/code_linters.nf.test.snap
.github/snapshots/codespaces.nf.test.snap
.github/snapshots/default.nf.test.snap
.github/snapshots/documentation.nf.test.snap
.github/snapshots/email.nf.test.snap
.github/snapshots/fastqc.nf.test.snap
.github/snapshots/github_badges.nf.test.snap
.github/snapshots/gitpod.nf.test.snap
.github/snapshots/gpu.nf.test.snap
.github/snapshots/igenomes.nf.test.snap
.github/snapshots/license.nf.test.snap
.github/snapshots/nf_core_configs.nf.test.snap
.github/snapshots/nf_schema.nf.test.snap
.github/snapshots/rocrate.nf.test.snap
.github/snapshots/seqera_platform.nf.test.snap
.github/snapshots/slackreport.nf.test.snap
.github/snapshots/vscode.nf.test.snap
nf_core/pipeline-template/modules.json
nf_core/pipeline-template/modules/nf-core/multiqc/environment.yml
nf_core/pipeline-template/modules/nf-core/multiqc/main.nf
nf_core/pipeline-template/modules/nf-core/multiqc/tests/main.nf.test.snap
nf_core/pipeline-template/modules/nf-core/multiqc/tests/tags.yml
nf_core/pipeline-template/tests/.nftignore

This file has no stable md5sum. File got introduced in multiQC version 1.30.

Ignore MultiQC llms.txt during pipeline nf-tests

---

.github/workflows/update-template-snapshots.yml
.github/workflows/update-textual-snapshots.yml
CHANGELOG.md

This GHA add an nf-core-bot option to update the template nf-test snapshots used in the tools CI.
The command is `@nf-core-bot update template snapshots`
Close https://github.com/nf-core/tools/issues/3572
Website docs: https://github.com/nf-core/website/pull/3478

Add GHA to update template nf-test snapshots

---

.gitignore
nf_core/pipelines/download.py
nf_core/pipelines/downloads/docker.py
nf_core/pipelines/downloads/singularity.py
nf_core/pipelines/downloads/utils.py
tests/pipelines/test_download.py

resolves: #2309
This PR adds docker support to the pipeline download functionality
- Many of the singularity functions were made container agnostic and reused for docker purposes
- Looks like this will run into merge conflicts as there are multiple refactors running concurrently (#3509, #3506)
This PR uses the guide to download the image: https://github.com/nextflow-io/nextflow/discussions/4708
It mimics Singularity's cache env variable by using the new env variable `NXF_DOCKER_CACHEDIR`, the downside is that this is not an official env in nextflow and the user needs to run 
```
ls -1 [$NXF_DOCKER_CACHEDIR]/*.tar | xargs --no-run-if-empty -L 1 docker load -i
```
on their own as nextflow currently has no way of loading offline tar files
This PR is a rework of …

Add docker downloads

---

CHANGELOG.md
nf_core/pipeline-template/.github/workflows/download_pipeline.yml

Fixes https://github.com/nf-core/tools/issues/3732
Changes the `download_pipeline.yml` workflow of the pipeline template to no longer use the `dev` branch when installing `tools`.

fix: Remove dependency on dev branch of tools

---

CHANGELOG.md
nf_core/commands_modules.py
nf_core/commands_subworkflows.py
nf_core/components/create.py
nf_core/modules/lint/module_tests.py
nf_core/subworkflows/lint/subworkflow_tests.py

We don't have Pytests in nf-core/modules anymore, so the pytest_modules.yml file can be deprecated.

Linting: do not check pytest_modules.yml file, deprecating

---

.devcontainer/devcontainer.json
CHANGELOG.md

Adds a `hostRequirements` section to the devcontainer configuration.
````
"cpus": 4,
"memory": "16gb",
"storage": "32gb"
````
This leads to using the larger (free-tier) machine type available in Codespaces by default.
Locally, these seem to behave like "soft" requirements. If your machine does not satisfy these, you see an alert window like this:

Add Host Requirements to Devcontainer Config

---

CHANGELOG.md
nf_core/pipelines/download/singularity.py
nf_core/pipelines/download/utils.py

Fixes https://github.com/nf-core/tools/issues/3742
For those images, where no http download can be used and the `singularity pull` command is used. The temporary files were not properly moved / cleared up after.
Also closes https://github.com/nf-core/tools/issues/3730 by setting the correct file permissions for those images downloaded via http in python.

Fix Downloads: Clean up temporary files from singularity pull and set correct file permissions for http downloads

---

CHANGELOG.md
nf_core/pipeline-template/.github/workflows/nf-test.yml

- Add NXF_VERSION: ${{ matrix.NXF_VER }} to env section in nf-test step
- This fixes the missing environment variable that .github/actions/nf-test expects
- The nf-test action uses ${{ env.NXF_VERSION }} for Nextflow setup but it wasn't being passed from the workflow
- [ x] This comment contains a description of changes (with reason)

Template: Fix: Add NXF_VERSION environment variable to nf-test workflow
