.gitignore
tests/lint_examples/minimal_working_example/Dockerfile
tests/lint_examples/minimal_working_example/LICENSE

Added a minimal working example to tests/lint_examples/minimal_working_example/. This is just an inital stub, which needs to grow as we add tests.

Added first dummy minimal working example to lint tests

---

nf_core/lint.py
tests/lint_examples/minimal_working_example/nextflow.config
tests/test_lint.py

So far this only checks that config variables are defined. Next we can think about adding more, and checking what they are set to.

Made a start on testing the nextflow config

---

.travis.yml

This reverts commit 91f2e1819b3ec437b9262b4cf42793d3cd13cd54.

Revert "Pip install from requirements file"

---

nf_core/lint.py
scripts/nf-core
tests/lint_examples/minimal_working_example/nextflow.config
tests/test_lint.py

Introduce additional checks for release ready workflows

---

nf_core/lint.py
requirements.txt

Just started working on a new pipeline port and came across these minor fixes.

Couple of minor fixes

---

.travis.yml
tests/test_lint.py

Switch from nose2 to pytest

---

.gitignore
nf_core/lint.py

Address test failure seen in nf-core/cookiecutter#19

Strip quotes from version numbers when comparing container tags.

---

.travis.yml
nf_core/lint.py
tests/lint_examples/minimal_working_example/environment.yml
tests/lint_examples/minimal_working_example/nextflow.config
tests/test_lint.py

Check pip dependencies on release

---

nf_core/lint.py
tests/lint_examples/minimal_working_example/.travis.yml

Updated tests to cover new change in PR #44

Fixing up #44 PR

---

nf_core/list.py
tests/test_list.py

Try to get code coverage back to the top

---

nf_core/lint.py

Just some tiny refactoring ;))

Make comparison of line items more readable

---

tests/test_lint.py

Remove TRAVIS_REPO_SLUG so that travis release tests don't fail for tools

---

CHANGELOG.md
docs/lint_errors.md
nf_core/lint.py
nf_core/release.py
tests/lint_examples/minimal_working_example/Dockerfile
tests/lint_examples/minimal_working_example/Singularity
tests/test_download.py
tests/test_lint.py

x-ref https://github.com/nf-core/methylseq/pull/29
Updates linting tests and automatic release tool to handle simpler root conda environment installations in Docker and Singularity.

Update linting and release tool to support simpler conda installation

---

CHANGELOG.md
docs/lint_errors.md
nf_core/lint.py
nf_core/release.py
tests/lint_examples/minimal_working_example/Dockerfile
tests/lint_examples/minimal_working_example/Singularity
tests/test_download.py
tests/test_lint.py

So that the pipelines use the latest linting tools, these updates need to be merged into `master`.
Happy to consider alternatives.

Dev > Master

---

Dockerfile

Pin miniconda image for reproducibility reasons as discussed on gitter.

Pin MiniConda Base Image 

---

nf_core/pipeline-template/{{cookiecutter.pipeline_slug}}/main.nf

Reapplied https://github.com/nf-core/cookiecutter/pull/57 now that we've moved cookiecutter into tools

Applied changes from @apeltzer in nf-core/cookiecutter#57

---

nf_core/pipeline-template/{{cookiecutter.pipeline_slug}}/environment.yml

cf https://github.com/nf-core/tools/pull/108

Get rid of last pipeline linting warning by using newest MQC

---

nf_core/pipeline-template/{{cookiecutter.pipeline_slug}}/docs/usage.md
nf_core/pipeline-template/{{cookiecutter.pipeline_slug}}/environment.yml

As mentioned by @sofiahaglund on gitter...

Fix vis error

---

.travis.yml
nf_core/pipeline-template/{{cookiecutter.pipeline_slug}}/.travis.yml
nf_core/pipeline-template/{{cookiecutter.pipeline_slug}}/docs/configuration/local.md
nf_core/pipeline-template/{{cookiecutter.pipeline_slug}}/docs/usage.md

The unquoted travis tests were breaking the YAML, meaning that Travis wasn't running.

Quote the new .travis.yaml tests

---

.travis.yml
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/CHANGELOG.md
setup.py

Most changes based on https://github.com/deathbeds/importnb, which appears to get this to work

Attempt at getting markdown parsed for PyPI release

---

.travis.yml
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.travis.yml
setup.py
tests/lint_examples/minimal_working_example/.travis.yml

Trying to fix the travis errors

Import sys to setup.py

---

nf_core/pipeline-template/{{cookiecutter.name_noslash}}/nextflow.config

As documented at https://www.nextflow.io/docs/latest/config.html?highlight=author#scope-manifest

Adding authorship template

---

.github/CONTRIBUTING.md
.github/PULL_REQUEST_TEMPLATE.md
README.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.github/CONTRIBUTING.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.github/ISSUE_TEMPLATE/bug_report.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.github/ISSUE_TEMPLATE/feature_request.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.github/PULL_REQUEST_TEMPLATE.md

* Added contributing docs and PR template for main tools repo
* Some tweaks to the template text for the same
* Updated the main readme docs, added ToC

Documentation update

---

README.md
nf_core/list.py
scripts/nf-core

I beefed up `nf-core list` a bit to make it more useful:
* Ability to filter on keywords
* Customisable sorting of results

Adding functionality to nf-core list

---

CHANGELOG.md
README.md
docs/lint_errors.md
nf_core/bump_version.py
nf_core/lint.py
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.travis.yml
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/README.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/main.nf
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/nextflow.config
tests/lint_examples/minimal_working_example/.travis.yml
tests/lint_examples/minimal_working_example/README.md
tests/lint_examples/minimal_working_example/nextflow.config
tests/test_bump_version.py
tests/test_lint.py

I have bumped up the version to 0.32.0, updated the nextflow.config and changed the relevant calls to "manifest" in main.nf.

Update manifest scope for predefined variables released in NF 0.32.0

---

CHANGELOG.md

Complete with a `[skip-ci]` demo for @sven1103 😉

Update changelog for v1.3 dev

---

nf_core/pipeline-template/{{cookiecutter.name_noslash}}/main.nf

${prefix} isnt defined anywhere in output_documentation process but is used as a tag.

Removed undefined ${prefix} from process

---

.github/CONTRIBUTING.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.github/CONTRIBUTING.md

~~See https://github.com/nf-core/deepvariant/pull/3~~
_Edit:_ See https://github.com/nf-core/nf-co.re/pull/46 I meant sorry

Updated URL for guidelines

---

.coveragerc
.travis.yml
CHANGELOG.md
nf_core/bump_version.py
nf_core/create.py
nf_core/licences.py
tests/test_bump_version.py
tests/test_create.py
tests/test_licenses.py

Mostly clean up PR and some added tests to increase code coverage by tests.

Pump up the coverage and refactor some code

---

docs/lint_errors.md
nf_core/lint.py
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/README.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/bin/scrape_software_versions.py
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/conf/base.config
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/conf/igenomes.config
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/conf/test.config
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/docs/output.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/docs/usage.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/environment.yml
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/main.nf
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/nextflow.config

Closes https://github.com/nf-core/tools/issues/93
* Added a load of `TODO nf-core:` statements in the template
* Added lint test to search for TODO statements
Bonus:: Handled Anaconda connection errors (was working offline and couldn't work without this).

Template todos

---

CHANGELOG.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.travis.yml
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/conf/binac.config
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/conf/cfc.config
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/docs/usage.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/nextflow.config

This updates both binac and cfc system configs for general usage across pipelines. Once we use the syncing process, this should (and could!) be synced across all pipelines :-)

QBIC Specific Config Template Updates

---

nf_core/lint.py
tests/test_create.py

Fix tests after https://github.com/nf-core/tools/pull/184

Update tests for new author flag in pipeline creation

---

CHANGELOG.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/conf/uzh.config
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/nextflow.config

This addresses a point raised by @ewels in https://github.com/nf-core/openmspeptidequant/pull/11 to harmonize more pipeline profiles across pipelines using the template and soon syncing. I added one more profile that I feel familiar with, but others such as the uppmax ones should probably be added the same way soonish (?).

Harmonize more profiles

---

README.md

This adds a bioconda badge to our readme to make sure people know how to install using conda :-) 

Added bioconda badge to readme

---

.travis.yml
CHANGELOG.md

This should fail, as I haven't updated `CHANGELOG.md` yet. Hopefully we'll also get some debugging variables printed. If it looks good then I'll updated the changelog and the new test should pass.. We shall see.

Attempt at making PRs fail if the CHANGELOG.md is not updated.

---

CHANGELOG.md
bin/sync
bin/syncutils/template.py
nf_core/create.py
nf_core/download.py
nf_core/lint.py
nf_core/utils.py

Removed unused import statements.
Mainly testing out LGTM: https://lgtm.com/projects/g/nf-core/tools/alerts/

Removed unused import statements

---

CHANGELOG.md
bin/syncutils/utils.py
nf_core/list.py
nf_core/utils.py

Fixes https://github.com/nf-core/tools/issues/208
Fail gracefully if nextflow isn't installed.

Handle missing nextflow installation. See nf-core/tools#208

---

CHANGELOG.md
README.md
docs/lint_errors.md
nf_core/bump_version.py
nf_core/lint.py
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.travis.yml
tests/lint_examples/minimal_working_example/.travis.yml

Pull the `:dev` tagged docker image for travis testing. Template and lint updates.

Travis - Pull :dev docker image for tests.

---

CHANGELOG.md
setup.py

Bumped version for 1.4 release.

Bumped version for 1.4 release

---

README.md

Fix link to linting error codes from tools readme

Fix link to linting error codes from tools readme

---

CHANGELOG.md
tests/test_list.py

Increase CC

---

CHANGELOG.md
bin/blacklist.json
bin/sync
bin/syncutils/utils.py

Introduces a blacklist of pipelines that should not be synced.
Just add or remove pipeline names in the `blacklist.json`.

Provide blacklist for syncing

---

CHANGELOG.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/conf/awsbatch.config
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/main.nf

This adds custom config logging to the summary used by nf-core pipelines. It checks for the existence of the required `params.config_...` parameters and then adds these to the `summary` object. 
x-ref https://github.com/nf-core/configs/pull/9 (which introduces this feature in `nf-core/configs`)

Add Custom Config Handling / Logging

---

.travis.yml

Conditions push event

---

bin/push.sh

Enforce git push

---

.travis.yml
CHANGELOG.md
setup.py

Adds travis job for api docs

---

CHANGELOG.md
setup.py

Removes Python 3.4 special treatment

---

nf_core/launch.py
nf_core/workflow/parameters.py
nf_core/workflow/validation.py

Made nf-core launch prompts beautiful

---

CHANGELOG.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/conf/base.config
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/docs/usage.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/main.nf
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/nextflow.config

See https://github.com/nf-core/tools/issues/265
NB: Instead of giving a `withLabel` config example, I instead linked to the nextflow documentation in a comment. I removed the toy `withName` examples - we don't actually want people to use those config lines in their pipelines.

Template: Update logo and trace filenames. Closes nf-core/tools#265

---

CHANGELOG.md
nf_core/launch.py
nf_core/workflow/parameters.py

* Handle JSON parsing and validation exceptions nicely
* Use OrderedDict structures to maintain group order in Python2
* Tweak a couple of bits of formatting

nf-core launch updates

---

CHANGELOG.md
Dockerfile

I upgraded Conda to latest version 4.6.7 to follow current best practices with slow conda builds. 
https://github.com/bioconda/bioconda-recipes/issues/13774

Update Base to 4.6.7 conda

---

CHANGELOG.md
docs/lint_errors.md

This should fix the linting errors on `dev`

 Fix markdown lint errors

---

CHANGELOG.md

Remove dup changelog line [skip ci]

---

CHANGELOG.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/main.nf

As requested in https://github.com/nf-core/tools/pull/279

Changelog version number. Tidy up template summary logs

---

setup.py

Bump version number in setup.py

---

CHANGELOG.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/main.nf

add check for tracefiles in s3 buckets

---

.travis.yml
CHANGELOG.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.gitignore
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/conf/test.config
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/docs/configuration/reference_genomes.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/docs/installation.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/docs/output.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/main.nf
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/nextflow.config

I came across some stuff which should have failed the markdown linting previously, so now running that lint step on the compiled pipeline using the compiled pipeline config file.

 Some more tweaks from the final rnaseq template merge

---

CHANGELOG.md
Dockerfile
README.md

Improved table of contents in the readme. This is mostly to coincide with an upcoming website update.

Improve Readme ToC

---

.github/CONTRIBUTING.md
CHANGELOG.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.github/CONTRIBUTING.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/CODE_OF_CONDUCT.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/README.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/assets/email_template.txt
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/assets/multiqc_config.yaml
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/bin/scrape_software_versions.py
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/docs/README.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/docs/usage.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/main.nf

* Removed Gitter references in `.github/` directories for `tools/` and pipeline template.
* Updated links for remote docs in both `README.md` files in pipeline template.
* Changed `scrape_software_versions.py` to output `.csv` file
* Added `export_plots` parameter to multiqc config

Removed Gitter everywhere, updated docs and multiqc updates

---

CHANGELOG.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/conf/igenomes.config

Adding BWA and Bowtie2 indices to igenome config template

---

README.md

FIxed https://nf-co.re/developers/sync and https://nf-co.re/developers/adding_pipelines links

Fixed some 404 end links

---

CHANGELOG.md
README.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/README.md

Add nf-core citation

---

CHANGELOG.md
bin/blacklist.json

Drop:
- bcellmagic
- nascent
- atacseq 
from blacklist as these have template branches and are ready to receive updates in the future 👍 
Add:
"sarek",
"neutronstar",
"proteomicslfq",
"clinvap",
"lncpipe",
"ddamsproteomics",
"scrnaseq",
"guideseq"
As these are not ready yet.

Update Sync Blacklist properly

---

CHANGELOG.md
bin/blacklist.json
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/main.nf

Removed `chipseq` from blacklist, and fixed annoying typo.

Remove chipseq from blacklist

---

CHANGELOG.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/main.nf

Fixed bug in template for https://github.com/nf-core/tools/issues/314

Fix email notification bug

---

CHANGELOG.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/README.md

Add Quick start section to main README of template

---

CHANGELOG.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/main.nf

Correct typo

---

CHANGELOG.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/nextflow.config

This just modifies some of the changes in https://github.com/nf-core/tools/pull/351 to get this merged into `dev`ASAP:

Options for DockerRun

---

CHANGELOG.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/main.nf

Fix workflow.onComplete() in template

---

CHANGELOG.md
nf_core/workflow/parameters.py
tests/workflow/example.json
tests/workflow/test_parameters.py

As requested by @ewels here: https://github.com/nf-core/tools/pull/373
This only addresses the parameter problem.

Fix Parameter issues

---

CHANGELOG.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.github/CONTRIBUTING.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/README.md

- add direct link to the pipeline slack channel in the contribution guidelines template
- add contributions and support heading with links to contribution guidelines and link to the pipeline slack channel in the main README template

Use direct link to slack channel

---

CHANGELOG.md
nf_core/create.py

description says it all
Merge after #376

Add a dev branch automatically too

---

CHANGELOG.md
README.md
nf_core/workflow/parameters.py
tests/workflow/test_parameters.py
tests/workflow/test_validator.py

I fixed a link in the tools README pointing to the parameter schema. I also introduced the usage of a stable schema release 0.1.0 in the tools launch logic.

Introduces stable parameter schema reference

---

CHANGELOG.md
setup.py
tests/lint_examples/minimal_working_example/Dockerfile

1.7 release

---

CHANGELOG.md
setup.py
tests/lint_examples/minimal_working_example/Dockerfile

Bumping version tags to v1.8dev

Version bump to v1.8dev

---

CHANGELOG.md
Dockerfile
bin/blacklist.json

Didn't feel like updating this in separate PRs... 
Fixes #413 and fixes #414

Blacklist Update + Base Image Update

---

CHANGELOG.md
nf_core/create.py
nf_core/pipeline-template/cookiecutter.json

Should fix error introduced in https://github.com/nf-core/tools/pull/421
Let's see what the tests do.. 🤞

Shortname hotfix

---

.github/CONTRIBUTING.md
CHANGELOG.md
README.md
docs/lint_errors.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.github/CONTRIBUTING.md

Everything should be travis-ci.com now

---

CHANGELOG.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/conf/base.config
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/nextflow.config

Move params section from base.config to nextflow.config

---

CHANGELOG.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.travis.yml
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/Dockerfile
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/README.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/nextflow.config
tests/lint_examples/minimal_working_example/.travis.yml
tests/lint_examples/minimal_working_example/README.md
tests/lint_examples/minimal_working_example/nextflow.config
tests/test_bump_version.py
tests/test_lint.py

Export PYTHONNOUSERSITE using env scope in nextflow.config

---

.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.github/CONTRIBUTING.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.github/PULL_REQUEST_TEMPLATE.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/CHANGELOG.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/CODE_OF_CONDUCT.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/docs/usage.md

Minor typo and bug fixes

---

nf_core/pipeline-template/{{cookiecutter.name_noslash}}/Dockerfile

Update wording in Dockerfile

---

nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.travis.yml

- Moved test to check if branch is `patch` (there's no need to check origin of a branch that is called patch).
cf https://github.com/nf-core/sarek/pull/53
Fix part of #432

Fix branch protection in TEMPLATE

---

CHANGELOG.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.github/CONTRIBUTING.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.gitignore
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/docs/usage.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/main.nf
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/nextflow.config

Minor template tweaks, picking up stuff mentioned in nf-core/methylseq#108

Template tweaks based on review of nf-core/methylseq#108

---

CHANGELOG.md
README.md
docs/lint_errors.md
nf_core/bump_version.py
nf_core/lint.py
tests/lint_examples/minimal_working_example/Dockerfile
tests/test_lint.py

At first, I added pattern matches for each of the occurences in the
Dockerfile, however this looked kinda ugly because there were multiple
'Updating version in Dockerfile ..' lines printed.
So I refactored the code a little to make sure there is only one INFO line printed per file that was changed, followed by all changes in that file.
While I was at it, I also added a bit of color to the output.

nf-core bump-version : also bump version of exported conda environment

---

CHANGELOG.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/bin/scrape_software_versions.py

Make it Python3 compatible following @drpatelh lead on this!
Fixes requirements for https://github.com/nf-core/tools/pull/462

Fix scrape_software_versions for python3

---

CHANGELOG.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.github/workflows/ci.yml

added NXF_ANSI_LOG variable export to template CI

---

CHANGELOG.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.github/workflows/ci.yml

Adding env variables to the env scope in the pipeline template

ci workflow env variables

---

CHANGELOG.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/main.nf

Should hopefully fix https://github.com/nf-core/tools/issues/442

Template: Fix ANSI codes in summary log messages

---

CHANGELOG.md
docs/lint_errors.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/conf/igenomes.config
setup.py

Fix a couple of things in CHANGELOG

---

CHANGELOG.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/README.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/main.nf
setup.py

Version bump to 1.9dev

---

CHANGELOG.md
nf_core/lint.py

- Removed linting on circle CI as the content is different than .travis.yml

Removed linting on circle CI

---

CHANGELOG.md
nf_core/lint.py
tests/test_lint.py

Remove CircleCI everywhere

---

CHANGELOG.md
docs/lint_errors.md

Update CI section for lint error documentation

---

CHANGELOG.md
README.md

- Improve docs about installing nf-core/tools

improve installation docs

---

docs/lint_errors.md

Fix link in lint errors page

---

CHANGELOG.md
docs/lint_errors.md
nf_core/lint.py
tests/lint_examples/minimalworkingexample/.github/workflows/branch.yml

Fix GitHub actions linting problems - minor fixes for problems spotted by @DiegoBrambilla
Full discussion of problems on Slack: https://nfcore.slack.com/archives/CE6PELWR4/p1581503176086600

Fix GitHub actions linting problems

---

CHANGELOG.md
README.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/README.md

Updated the reference in the template and tools readme for the new paper.
Too slow @drpatelh! 😉

Update nf core publication

---

.github/workflows/create-lint-wf.yml
.github/workflows/deploy-pypi.yml
.github/workflows/markdown-lint.yml
CHANGELOG.md

Further work on https://github.com/nf-core/tools/pull/523 to try to fix the errors encountered..

More actions ci

---

.github/workflows/tools-api-docs.yml
CHANGELOG.md

Testing the tests

---

CHANGELOG.md
README.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/README.md

Add ReadCube link to publication

---

CHANGELOG.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.github/workflows/linting.yml

add YAML linting

---

CHANGELOG.md
README.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/README.md

It's not a preprint

---

.github/workflows/deploy-pypi.yml
CHANGELOG.md

Should make the tests pass again.
See https://github.com/nf-core/tools/pull/535 for failed attempt to fix this without removing these.

Remove TestPyPI deployments

---

CHANGELOG.md
nf_core/lint.py

Linting: Don't print results if we have a critical error

---

CHANGELOG.md
docs/lint_errors.md
nf_core/lint.py

- Also refactored a bit of the lint code for files and config options
- Also made some of the output a little more colourful and pretty :sparkles:
Fixes https://github.com/nf-core/tools/issues/497

Lint: Allow params.reads or params.input or params.design

---

.github/RELEASE_CHECKLIST.md
CHANGELOG.md

Closes https://github.com/nf-core/tools/issues/505

Added release checklist for tools

---

.github/workflows/code-tests.yml
.github/workflows/markdown-lint.yml
CHANGELOG.md

Minor tweaks and tidying from code review in #545

Tidy up whitespace and changelog

---

.github/workflows/sync.yml
CHANGELOG.md

GitHub Actions: Install Nextflow for sync

---

CHANGELOG.md
README.md

* Made the GitHub Actions CI badge link to the Python tests for the `master` branch specifically
* Added a badge for the PyPI install as well as bioconda

Tart up the readme badges a little

---

README.md

See nf-core/tools#572 - rewrote the installation instructions for bioconda to make it clear about channel configuration.

Update conda installation instructions

---

nf_core/schema.py

Fixes to the new `nf-core schema` commands.
* `nf-core schema build` now removes the required flags from the schema if a parameter is removed.

Stand alone schema - fixes 

---

CHANGELOG.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/main.nf

Fix for https://github.com/nf-core/tools/issues/391

Fix images in output_docs

---

CHANGELOG.md
nf_core/lint.py
tests/lint_examples/minimalworkingexample/environment.yml
tests/test_lint.py

Allow specification of Conda build id as well as version

---

CHANGELOG.md
scripts/nf-core

Always print the current version of nf-core/tools below the ASCII header:

Header version info

---

CHANGELOG.md
nf_core/bump_version.py

Output docs

---

nf_core/pipeline-template/{{cookiecutter.name_noslash}}/README.md

Template readme tweaks, taken from nf-core/viralrecon#116

Template: Minor readme tweaks

---

CHANGELOG.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.github/workflows/awsfulltest.yml
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.github/workflows/awstest.yml
tests/lint_examples/failing_example/.github/workflows/awsfulltest.yml
tests/lint_examples/failing_example/.github/workflows/awstest.yml
tests/lint_examples/minimalworkingexample/.github/workflows/awsfulltest.yml
tests/lint_examples/minimalworkingexample/.github/workflows/awstest.yml

Update Awstests secrets names

---

nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.github/workflows/ci.yml
tests/lint_examples/minimalworkingexample/.github/workflows/ci.yml

Use the proper GitHub release version tag for the docker image, instead of the full ref string.

Dockerhub GHA release push fix

---

CHANGELOG.md
README.md
nf_core/launch.py
nf_core/lint.py
nf_core/list.py
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/nextflow_schema.json
nf_core/schema.py
nf_core/sync.py
nf_core/utils.py
scripts/nf-core
setup.py
tests/test_bump_version.py
tests/test_create.py
tests/test_download.py
tests/test_launch.py
tests/test_licenses.py
tests/test_lint.py
tests/test_list.py
tests/test_schema.py

Updates to `nf-core launch` to work with new pipeline JSON schema.
Maybe also want to wrap the send-to-website-GUI functionality into this PR too, even if the website side is not yet written.

Schema launch updates

---

CHANGELOG.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/README.md

Fix Slack badge

---

nf_core/pipeline-template/{{cookiecutter.name_noslash}}/README.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/bin/check_samplesheet.py
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/conf/test.config
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/conf/test_full.config
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/docs/usage.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/environment.yml
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/main.nf
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/modules/local/check_samplesheet.nf
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/modules/local/functions.nf
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/modules/local/get_software_versions.nf
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/modules/local/output_documentation.nf
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/modules/nf-core/fastqc.nf
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/modules/nf-core/multiqc.nf
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/nextflow.config
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/nextflow_schema.json
tests/test_launch.py

Get tests passing and add design file input

---

nf_core/launch.py
tests/test_launch.py

Fix PyInquirer due to upstream changes.

Fix PyInquirer

---

CHANGELOG.md
README.md
scripts/nf-core

Make proper use of the way that `click` handles command-line help. Use a full stop to finish the first sentence used in the overview help and write a lot more prose for each command that shows on the help text for that specific command.
New overview help text:
```console
$ nf-core --help
,--./,-.
`._,._,'
nf-core/tools version 1.10.dev0
Usage: nf-core [OPTIONS] COMMAND [ARGS]...
Options:
--version      Show the version and exit.
-v, --verbose  Verbose output (print debug statements).
--help         Show this message and exit.
Commands:
list          List available nf-core pipelines with local info.
launch        Launch a pipeline using a web GUI or command …
```

Write a lot more command-line help text

---

README.md

Add badge to readme for Black code formatter

---

nf_core/pipeline-template/{{cookiecutter.name_noslash}}/bin/check_samplesheet.py

Adding some details to the DSL2 template

add TODO check_samplesheet

---

nf_core/schema.py

Schema build - extra help if running offline

---

nf_core/pipeline-template/{{cookiecutter.name_noslash}}/lib/Schema.groovy

Add type to help and auto-detect parameter character size

---

CHANGELOG.md
README.md
nf_core/__main__.py
nf_core/list.py
tests/test_list.py

Added default filtering for archived workflows; https://github.com/nf-core/tools/issues/639

hide archived workflows by default in 'list'

---

.github/workflows/sync.yml
README.md
nf_core/__main__.py
nf_core/sync.py
tests/test_sync.py

Some tweaks to `nf-core sync --all` to address minor gripes in https://github.com/nf-core/tools/issues/548

Sync improvements

---

CHANGELOG.md
README.md
nf_core/__main__.py
nf_core/utils.py
tests/test_utils.py

Fix for https://github.com/nf-core/tools/issues/612
Note: currently checks against hard-coded url at https://nf-co.re/version ; consider updating this

Check tool release

---

nf_core/lint.py

Slight tweak to main lint results output

---

nf_core/pipeline-template/{{cookiecutter.name_noslash}}/docs/usage.md

fix for https://github.com/nf-core/nf-co.re/issues/453#issuecomment-662981952

update incorrect link to igenomes conf

---

nf_core/pipeline-template/{{cookiecutter.name_noslash}}/nextflow_schema.json
nf_core/schema.py

Fix issues with the `schema  build` code that was doing weird stuff when making a new schema - bug found by @mashehu 
Also revert the template JSON schema back to 4-space padding instead of 2, to limit the diffs when people edit their schema from the template.

Schema build bug

---

.github/RELEASE_CHECKLIST.md
CHANGELOG.md
setup.py

Bump to v1.10 - Copper Camel

---

CHANGELOG.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/conf/test_full.config
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/docs/usage.md

readPaths is now input_paths

---

.github/workflows/sync.yml
CHANGELOG.md
setup.py

Version bump - 1.11dev

---

CHANGELOG.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.github/workflows/awsfulltest.yml
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.github/workflows/awstest.yml

Fix mistake in command in `awstest.yml`

fix awstest command

---

.github/workflows/branch.yml

I dedicated my life to perish typos in 🔥 .

fixed typo

---

nf_core/pipeline-template/{{cookiecutter.name_noslash}}/nextflow_schema.json

move NOT mov

---

nf_core/__main__.py
nf_core/create.py
nf_core/download.py
nf_core/licences.py
nf_core/lint.py
nf_core/schema.py
nf_core/sync.py
nf_core/utils.py
tests/test_licenses.py
tests/test_lint.py
tests/test_list.py

I only added `highlight=False` in the nf-core ascii art (`__main__.py`) in order to fall into line and be the same colour.  After that, I run Black to formate the code. I tried to follow the steps in 'CONTRIBUTING.md'. Please let me if there is any mistake.
PR checklist

Wrong blue in a part of the nf-core ascii art #736

---

CHANGELOG.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/nextflow.config

Added a new podman profile

---

.gitignore
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.github/ISSUE_TEMPLATE/bug_report.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/README.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/docs/usage.md

Not updating the changelog, since I consider this part of 
`* Added a Podman profile, which enables Podman as container`

Added Podman documentation

---

CHANGELOG.md
docs/lint_errors.md
nf_core/lint.py
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.github/workflows/awstest.yml
nf_core/schema.py
tests/lint_examples/failing_example/.github/workflows/awstest.yml
tests/lint_examples/minimalworkingexample/.github/workflows/awsfulltest.yml
tests/lint_examples/minimalworkingexample/.github/workflows/awstest.yml
tests/lint_examples/minimalworkingexample/nextflow_schema.json
tests/test_lint.py

- Updated linting for the GitHub actions AWS workflows.
- Also updated linting for the Json schema after the change of `https` to `http` by #748

AWS actions linting update

---

CHANGELOG.md
setup.py

https://github.com/nf-core/tools/pull/746#discussion_r512517934

Added release name and date to v1.11 changelog

---

tests/lint_examples/minimalworkingexample/Dockerfile
tests/test_lint.py

More 1.11 not 1.11.0

---

CHANGELOG.md
setup.py

Bump version number to v1.12dev in changelog and setup.

Version 1.12dev bump

---

CHANGELOG.md
nf_core/launch.py

Hotfix for https://github.com/nf-core/tools/pull/760/

Hotfix rich

---

CHANGELOG.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/nextflow.config

include test_full pipeline template

---

CHANGELOG.md
docs/api/_src/conf.py
docs/api/_src/index.rst
docs/api/_src/launch.rst
docs/api/_src/modules.rst
docs/api/_src/schema.rst
docs/api/_src/sync.rst
docs/api/_src/workflow.rst
tests/test_licenses.py

Hopefully fixes https://github.com/nf-core/tools/issues/775

Update sphinx autodocs

---

CHANGELOG.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.github/workflows/ci.yml
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/README.md
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/assets/sendmail_template.txt
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/main.nf
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/nextflow.config
tests/lint_examples/minimalworkingexample/nextflow.config

`baseDir` is deprecated in favour of `projectDir` since Nextflow version 20.04.0
https://www.nextflow.io/docs/latest/script.html#script-implicit-variables

Switch baseDir to projectDir

---

docs/api/_src/bump_version.rst
docs/api/_src/conf.py
docs/api/_src/create.rst
docs/api/_src/download.rst
docs/api/_src/index.rst
docs/api/_src/launch.rst
docs/api/_src/licences.rst
docs/api/_src/lint.rst
docs/api/_src/list.rst
docs/api/_src/modules.rst
docs/api/_src/schema.rst
docs/api/_src/sync.rst
docs/api/_src/utils.rst
tests/test_launch.py

* Index page - auto ToC for all pages
* Show all methods, including those that are undocumented
* Show intheritance between methods
* Remove disabling of syntax highlighting

Better sphinx autodocs

---

CHANGELOG.md
setup.py

Bump the version number to 1.12 for a new release.

Version bump to 1.12

---

CHANGELOG.md
setup.py

Please do not merge before https://github.com/nf-core/tools/pull/784 is merged to `master`

Version bump to v1.13dev

---

nf_core/pipeline-template/{{cookiecutter.name_noslash}}/conf/igenomes.config
nf_core/pipeline-template/{{cookiecutter.name_noslash}}/main.nf

Otherwise, all pipelines fail in the onComplete step. Maybe the overall exit status was still 0? Otherwise, I don't know how this passed CI. Let me know if it needs a test.
Follow-up to: #778

Remove remaining baseDir occurrance

---

CHANGELOG.md
setup.py

Version bump for https://github.com/nf-core/tools/pull/806/

Bump version for v.1.12.1 release

---

.github/workflows/tools-api-docs.yml
docs/api/requirements.txt

Will hopefully fix the Sphinx docs generation. See https://github.com/nf-core/tools/pull/809#issuecomment-744398508

Fix sphinx docs

---

nf_core/pipeline-template/{{cookiecutter.name_noslash}}/README.md

* No blockquotes for config instructions
* Include pipeline description in intro.

DSL2 readme tweaks

---

nf_core/utils.py
setup.py

Replace a bunch of homebrew code _(that took me most of a morning and that I was quite pleased with to be honest)_ with like, 2 lines from `rich`.
See nf-core/tools#816

Use nice spinner function from Rich instead of homebrew code.

---

nf_core/lint/actions_awsfulltest.py
nf_core/lint/actions_awstest.py
nf_core/lint/actions_branch_protection.py
nf_core/lint/actions_ci.py
nf_core/lint/actions_lint.py

Just a tiny PR that adds better error reporting for loading YAML files in the lint function, to help
better understand errors as found here #790

linting: better error message to yaml loading

---

CHANGELOG.md
nf_core/lint/__init__.py
nf_core/lint/conda_env_yaml.py
nf_core/lint/pipeline_todos.py
nf_core/schema.py
setup.py

Updated the linting progress bar so that lint tests can have their own sub-progress bar. Added one for the conda dependency check.
Closes nf-core/tools#299
Also bumped minimum Rich version as latest release is a bug hotfix.

Added granular progress bar for conda deps check.

---

nf_core/pipeline-template/{{cookiecutter.name_noslash}}/assets/email_template.html

remove extra <head> tag

---

nf_core/pipeline-template/{{cookiecutter.name_noslash}}/README.md

Remove Readcube link

---

nf_core/module-template/{{cookiecutter.tool_name}}/software/functions.nf
nf_core/module-template/{{cookiecutter.tool_name}}/software/main.nf

Updates to nf-core modules create command

---

nf_core/__main__.py
nf_core/modules/create.py

Update docs for nf-core create

---

nf_core/module-template/software/main.nf

Fixes for @drpatelh after updates to the Jinja templating for modules.

Fix modules template main.nf

---

nf_core/modules/create.py

New feature suggested by @JoseEspinosa in Slack: https://nfcore.slack.com/archives/CE5LG7WMB/p1615976112010300

Modules create - fuzzy finder for process label

---

nf_core/modules/lint.py

Appending correct tuples in `check_module_changes` function

fixed value error with new module

---

nf_core/modules/create.py

Remove [violet] rich format string from questionary prompt

---

nf_core/lint/pipeline_todos.py
nf_core/modules/lint.py

fixed module todo bug

---

nf_core/lint/__init__.py
nf_core/modules/lint.py

Modules lint - don't wrap messages

---

docs/api/_src/_static/css/custom.css
docs/api/_src/conf.py
requirements-dev.txt

Adds sphinx to dev requirements file.
Switches based on OS/browser between light theme:
and dark theme:

Add nf-core colors to rtd sphinx theme

---

setup.py

closes https://github.com/nf-core/tools/issues/933

add pytest-workflow dep

---

.github/RELEASE_CHECKLIST.md
.github/workflows/create-lint-wf.yml
.github/workflows/pytest.yml
.github/workflows/sync.yml
nf_core/pipeline-template/.github/workflows/ci.yml

Added comment to release checklist to avoid running sync with an outdated Nextflow version.
closes #912

added comment in release checklist

---

CHANGELOG.md
nf_core/bump_version.py
nf_core/create.py
nf_core/lint/__init__.py

* Copy file if any exception with jinja in pipeline create
* Make lint summary table coloured according to overall status

Bugfix tweaks

---

nf_core/pipeline-template/.github/workflows/linting.yml

Find yml and yaml files for yaml linting

---

CHANGELOG.md
nf_core/pipeline-template/.github/workflows/linting.yml
nf_core/sync.py
tests/test_sync.py

Hopefully fixes https://github.com/nf-core/tools/issues/911 !

Sync headers abuse

---

nf_core/modules/create.py

This fixes it locally for me, would be nice to get some tests though.

fixed nf-core modules create bug

---

CHANGELOG.md
setup.py

Just bumping to 1.13.3 instead of 1.14 as is minor change

bump version to 1.13.3

---

nf_core/__main__.py

Fix docs URL and add mention of config file to nf-core lint cli help

---

CHANGELOG.md
nf_core/pipeline-template/lib/NfcoreSchema.groovy

* Don't set defaults to empty strings if no default in the schema
* Fix logic for printing a param to the summary if there is no default
* Rewrite the colour for the summary log
* Other minor tidying
Fixes nf-core/tools#971
Demo on the nf-core/methylseq pipeline before changes:
And after changes:

Rewrote schema summary output function.

---

nf_core/__main__.py
nf_core/download.py

Added questionary autocomplete to download command if pipeline name is not provided.

Autocomplete prompt for download command

---

.github/workflows/create-lint-wf.yml
.github/workflows/sync.yml
CHANGELOG.md
nf_core/__main__.py
nf_core/launch.py
nf_core/lint/__init__.py
nf_core/lint/actions_awsfulltest.py
nf_core/lint/files_unchanged.py
nf_core/lint/version_consistency.py
nf_core/module-template/tests/main.nf
nf_core/modules/create.py
nf_core/modules/test_yml_builder.py
nf_core/pipeline-template/.github/PULL_REQUEST_TEMPLATE.md
nf_core/pipeline-template/.github/workflows/awsfulltest.yml
nf_core/pipeline-template/.github/workflows/linting.yml
nf_core/pipeline-template/lib/NfcoreSchema.groovy
nf_core/pipeline-template/nextflow.config
nf_core/pipeline-template/nextflow_schema.json
nf_core/schema.py
nf_core/sync.py
setup.py
tests/lint/actions_awsfulltest.py
tests/test_modules.py

Fix merge conflics on dsl2_template branch due to recent updates on dev

---

tests/lint/files_unchanged.py
tests/lint/nextflow_config.py
tests/test_lint.py
tests/test_utils.py

Added a few more test for utils and linting.

Increased test coverage

---

CHANGELOG.md
nf_core/module-template/software/functions.nf
nf_core/module-template/software/main.nf
nf_core/modules/lint.py

This adds the following functionality to `nf-core modules lint`:
* check for entry in `pytest_software.yml`
* check that tags in `test.yml` adhere to guidelines
* update the `functions.nf` template according to @drpatelh new code

Adjust linting

---

CHANGELOG.md
nf_core/module-template/software/main.nf
nf_core/modules/lint.py
tests/test_modules.py

FIx linting for the addition of publish_by_meta to the module template

---

.github/workflows/tools-api-docs-dev.yml
.github/workflows/tools-api-docs-release.yml

Suggested gh action workflows for syncing docs with FTP.

Suggestion of gh actions for docs versioning

---

.github/workflows/tools-api-docs-dev.yml
.github/workflows/tools-api-docs-release.yml
CHANGELOG.md
docs/api/_src/conf.py

Follow up to https://github.com/nf-core/tools/pull/1004 - only upload the HTML build subfolder, not the entire docs directory.

Ftp sync folder fix

---

.github/workflows/tools-api-docs-dev.yml
.github/workflows/tools-api-docs-release.yml

Follow up to https://github.com/nf-core/tools/pull/1004 - I'm thinking that we probably don't need these ones after all..

No dangerous clean slate for docs ftp

---

nf_core/pipeline-template/nextflow_schema.json

Update regex used for --max_* params in Schema

---

README.md

Docker help - added mention of `$NXF_SINGULARITY_CACHE`

Docker docs - mention NXF_SINGULARITY_CACHE

---

README.md

Accidentally missed this one in the last PR to tweak these docs, sorry.

Docker - add `-u $(id -u):$(id -g)` to the docs

---

tools.Dockerfile

Ignore any locally installed packages (in `$HOME`) with `PYTHONNOUSERSITE`.

Do not pick up locally installed python packages

---

.gitignore
nf_core/modules/create.py

Tiny change in error message from check of GitHub user name, plus added Vim's tmp files to `.gitignore`.

Corrected spelling mistake

---

CHANGELOG.md
nf_core/modules/lint.py
tests/test_modules.py

Adds a lint check for `nf-core modules lint` that compares the `functions.nf` file with the template as discussed in slack.

Functions nf comparison

---

nf_core/__main__.py
nf_core/create.py
nf_core/launch.py
nf_core/lint/__init__.py
nf_core/list.py
nf_core/modules/lint.py
nf_core/modules/pipeline_modules.py
nf_core/modules/test_yml_builder.py
nf_core/schema.py
nf_core/sync.py
nf_core/utils.py
tests/test_bump_version.py
tests/test_cli.py
tests/test_launch.py
tests/test_licenses.py
tests/test_list.py
tests/test_modules.py
tests/test_schema.py
tests/test_sync.py
tests/test_utils.py

A recent update of `black` changed the formatting for docstrings spacing. This means that (a) CI validation is failing all over the place and (b) open PRs have tonnes of diffs where this is being applied file by file.
This PR is for the entire repo, just running Black.

Black - docstring quotes format change

---

.github/workflows/create-lint-wf.yml
.github/workflows/pytest.yml

Should be testing Python 3.9 now as well, since it hit a stable release.

Run pytests with Python 3.9 too

---

nf_core/pipeline-template/main.nf

Add implicit workflow declaration to main.nf of the DSL2 template.
Closes #1056

Add implicit workflow declaration to main.nf of the DSL2 template

---

CHANGELOG.md

Update changelog PR #1056

---

CHANGELOG.md
docs/api/_src/pipeline_lint_tests/schema_description.rst
nf_core/lint/__init__.py
nf_core/lint/schema_description.py

Adding a lint check to look missing parameter descriptions in the schema and warn about parameters outside of groups.

added check for parameter description

---

CHANGELOG.md
README.md
nf_core/pipeline-template/README.md

Fix review comments from @maxulysse in nf-core/tools#1066

---

nf_core/pipeline-template/nextflow.config

Remove docker.runOptions in favor of docker.userEmulation

---

nf_core/launch.py
nf_core/schema.py
tests/test_launch.py
tests/test_schema.py

Putting back the typo to maintain compatibility with the website.
See also https://github.com/nf-core/nf-co.re/pull/799

Revert recieved typo fix.

---

nf_core/pipeline-template/nextflow_schema.json

Add regex for MultiQC max email size

---

CHANGELOG.md
nf_core/modules/module_utils.py

Added progress bar to creation of `modules.json` file, since this can take quite a bit of time.

Added progress bar to creation of `modules.json`

---

.github/workflows/create-lint-wf.yml
CHANGELOG.md
nf_core/modules/remove.py

For `nf-core modules remove`: Remove entry in 'modules.json' if module directory is missing .

Remove entry in 'modules.json' if module directory is missing

---

nf_core/modules/lint/__init__.py
nf_core/modules/lint/functions_nf.py
nf_core/modules/nfcore_module.py
tests/test_modules.py

Small fix for the modules tests

fix the modules test setup

---

CHANGELOG.md
nf_core/modules/install.py
nf_core/modules/lint/module_version.py
nf_core/modules/module_utils.py

Fix bug in `modules.json` creation causing `get_module_git_log` to call GitHub API indefinitely.

Fix bug in `modules.json` creation

---

CHANGELOG.md
README.md

Added description of the `nf-core modules bump-versions` command to the readme.

Added `bump-versions` to the readme

---

CHANGELOG.md
README.md
setup.py

I think that should be all the versions ... 🤔

bumping the version to 2.0

---

CHANGELOG.md
nf_core/__main__.py
nf_core/modules/modules_repo.py
tests/test_modules.py

Modules install were raising errors when installing from an external repository. I've added checks for 
- That the remote repository and branch exists
- That the remote repository has a `modules` directory
- That the remote repository contain any modules

Add verification of remote repo

---

CHANGELOG.md
README.md
nf_core/__main__.py
nf_core/modules/install.py
nf_core/modules/module_utils.py

Misc. changes to install:
- Added check that the remote of a module exists.
- Made `--latest` default for `modules install --all`. It is still possble to override with `--sha`
- Remove unnecessary critical error from `nf-core modules install`.
- Added try-except blocks in a few more places.

Misc. changes to `nf-core modules install`

---

.github/workflows/sync.yml
CHANGELOG.md
setup.py

Bump version and fix sync action

Bump version

---

nf_core/pipeline-template/.editorconfig
nf_core/pipeline-template/.github/workflows/linting.yml
nf_core/pipeline-template/bin/scrape_software_versions.py

A few things I spotted whilst merging in the template updates

Small fixes in pipeline template

---

CHANGELOG.md
setup.py

Bump version to v2.1

---

CHANGELOG.md
nf_core/modules/update.py

Added code for checking that a module is installed before trying to update in `nf-core modules update`.

Check if module is installed before trying to update

---

.github/workflows/python-lint.yml

Use official black GitHub Action

Update black GitHub Action

---

.github/workflows/create-lint-wf.yml
.github/workflows/create-test-wf.yml
CHANGELOG.md
nf_core/pipeline-template/lib/NfcoreSchema.groovy
nf_core/pipeline-template/lib/NfcoreTemplate.groovy
nf_core/pipeline-template/lib/WorkflowMain.groovy
nf_core/pipeline-template/nextflow.config
nf_core/pipeline-template/nextflow_schema.json

Follow up to https://github.com/nf-core/tools/issues/1304

Remove params.hostnames from pipeline template

---

nf_core/pipeline-template/lib/NfcoreTemplate.groovy

Follow up to https://github.com/nf-core/tools/pull/1309

Remove remnant of params.hostnames

---

CHANGELOG.md
nf_core/pipeline-template/.gitattributes

See also https://nfcore.slack.com/archives/CE5LG7WMB/p1636276933143100

Auto-collapse installed modules and subworkflows in PRs

---

CHANGELOG.md
nf_core/modules/create.py
nf_core/modules/module_utils.py

`main.nf` has been added to the modules repo, so the original check no longer works. Based on Phil's suggestion, the PR checks to see if the README is from the modules repo.

Update 'modules' vs 'pipelines' check in 'modules create' command

---

CHANGELOG.md
nf_core/pipeline-template/.github/workflows/awsfulltest.yml
nf_core/pipeline-template/.github/workflows/awstest.yml

Update the AWS megatest CI actions for the pipelines to use the new and improve v2 GitHub Action.

Update tower action

---

.github/workflows/create-test-wf.yml
nf_core/modules/create.py
nf_core/modules/lint/__init__.py
nf_core/modules/lint/main_nf.py
nf_core/pipeline-template/.github/workflows/ci.yml
nf_core/pipeline-template/conf/modules.config
pyproject.toml

Draft PR to work together on fixing test after DSL2 v2.0 release of modules

Fix tests after DSL2 v2.0 release of modules

---

nf_core/modules/module_utils.py

Fix the nasty nasty bug

---

CHANGELOG.md
nf_core/pipeline-template/.github/workflows/linting_comment.yml

Add a linting PR comment even when the workflow `linting.yml` is failing.

Fix linting comment

---

nf_core/bump_version.py
nf_core/lint/actions_ci.py
nf_core/pipeline-template/.github/workflows/ci.yml
tests/lint/actions_ci.py
tests/test_bump_version.py

Continuing from https://github.com/nf-core/tools/pull/1343, refactoring to try to make this logic a little easier to read / understand

Nicer syntax for ci.yml matrix env variables

---

requirements.txt

Pin `jsonschema` to at least 3.0, same as bioconda fix: https://github.com/bioconda/bioconda-recipes/pull/32017

Pin jsonschema minimum 3.0

---

CHANGELOG.md
nf_core/pipeline-template/.github/workflows/awsfulltest.yml
nf_core/pipeline-template/.github/workflows/awstest.yml

x-ref https://github.com/nf-core/tower-action/pull/9 https://github.com/nf-core/tower-action/pull/10

Add retry strategy for AWS megatests

---

CHANGELOG.md

I put the gitpod changelog in the wrong place last time.

Changelog message fix

---

.gitpod.yml
nf_core/gitpod/gitpod.Dockerfile

Reduce the size by half, by dropping other languages supported in the image. 
I already pushed it manually to Dockerhub for testing purposes.

switch to gitpod/workspace-python to reduce image size

---

nf_core/gitpod/gitpod.Dockerfile

should help writing consistent code even on gitpod.

add black and yamllint to gitpod

---

nf_core/__main__.py
requirements.txt

I pulled this new command-line help stuff out into its own package: `rich-click`.
So now we can strip all of this out again and instead just have and import and a cheeky monkey patch 🙊

Rich click

---

CHANGELOG.md
nf_core/pipeline-template/conf/modules.config
nf_core/pipeline-template/nextflow.config
nf_core/pipeline-template/nextflow_schema.json

See [nf-core/rnaseq#752](https://github.com/nf-core/rnaseq/issues/752#issuecomment-1039451607)

Add --publish_dir_mode back into pipeline template

---

CHANGELOG.md
nf_core/pipeline-template/.github/workflows/awsfulltest.yml
nf_core/pipeline-template/.github/workflows/awstest.yml

Also removed `pipeline` and `revision` from the AWS workflows, which were not needed.
See https://github.com/nf-core/tower-action/pull/11 for context

Bumped `nf-core/tower-action` to `v3`

---

CHANGELOG.md
nf_core/bump_version.py

Don't trim trailing newline when bumping versions

---

nf_core/modules/module_utils.py

The new method of checking for an nf-core config file is much cleaner than what we had previously (looking for a readme file with various marks). However, the new warning is tripping people up quite a bit:
```
ERROR    Can't find a '.nf-core.yml' file with 'repository_type' set to 'pipeline' or 'modules': '.'                                                                                         __main__.py:489
Please use the '--repo-type' flag or create '.nf-core.yml'
```
This will become less of an issue after the pipeline sync goes out and pipelines update, but it's not very user friendly until then.
This PR replaces the exception error with an interactive prompt that asks what type of repo it is. If desired, it then creates / appends to a `.nf-core.yml` file with this information so …

Add prompt + file append if `.nf-core.yml` `repository_type` is not found.

---

README.md
nf_core/modules/create.py
nf_core/modules/module_utils.py

Make @mashehu happy.
Closes nf-core/tools#1444

Make prompts more consistent.

---

nf_core/modules/modules_command.py

Fix typo in log message.

---

.gitpod.yml
nf_core/pipeline-template/.gitpod.yml

[lint] spaces before comment

---

nf_core/pipeline-template/CHANGELOG.md
nf_core/pipeline-template/README.md

Added Singularity install tutorial + clarified conda usage

---

nf_core/pipeline-template/conf/test.config
nf_core/pipeline-template/conf/test_full.config

Remove params.outdir from test configs again

---

CHANGELOG.md
nf_core/module-template/tests/test.yml

Add versions.yml to the test.yml file of the module's template.

---

.github/workflows/push_dockerhub_dev.yml
.github/workflows/push_dockerhub_release.yml

- Split two docker build commands into their own action steps
- Bugfix: use --file instead of specfying the context incorrectly

Fix GitPod docker builds

---

nf_core/pipeline-template/docs/usage.md

Doc hackathon: [#1417](https://github.com/nf-core/tools/issues/1417)
Added some details about the -resume parameter.

Doc update : -resume parameter

---

nf_core/gitpod/gitpod.Dockerfile

Fix gitpod file permissions

---

CHANGELOG.md
setup.py

Changelog, bump to 2.3.1

---

CHANGELOG.md
nf_core/pipeline-template/.github/workflows/awsfulltest.yml
nf_core/pipeline-template/.github/workflows/awstest.yml

Don't specify pipeline or git sha

Fix tower-action

---

CHANGELOG.md
setup.py

Bump to version v2.3.2

---

CHANGELOG.md
nf_core/lint/files_exist.py

Linting: Check that editorconfig file exists

---

CHANGELOG.md
setup.py

Bump 2.4dev

---

CHANGELOG.md
requirements.txt

Bump minimum version of rich to 10.7.0

---

README.md

Add documentation for two new modules added to dev version 2.4 `nf-core modules mulled` and `nf-core modules test`

Add documentation for modules mulled and modules test commands

---

nf_core/modules/lint/main_nf.py

https://github.com/nf-core/tools/pull/1571#pullrequestreview-970968902

Nicer syntax from @Midnighter

---

CHANGELOG.md
nf_core/modules/lint/main_nf.py

Basically, skip this step if using shell instead.
Fixes nf-core/tools#1558

Module linting: Only lint script if there was a script.

---

CHANGELOG.md
nf_core/pipeline-template/README.md
tests/test_bump_version.py

- Remove black backgrounds. Now that GitHub has dark mode, they dissapear into the background.
- Add a badge to launch on Tower
---
[![GitHub Actions CI Status](https://github.com/nf-core/rnaseq/workflows/nf-core%20CI/badge.svg)](https://github.com/nf-core/rnaseq/actions?query=workflow%3A%22nf-core+CI%22) [![GitHub Actions Linting Status](https://github.com/nf-core/rnaseq/workflows/nf-core%20linting/badge.svg)](https://github.com/nf-core/rnaseq/actions?query=workflow%3A%22nf-core+linting%22) [![AWS CI](https://img.shields.io/badge/CI%20tests-full%20size-FF9900?logo=Amazon%20AWS)](https://nf-co.re/rnaseq/results) [![Cite with Zenodo](http://img.shields.io/badge/DOI-10.5281/zenodo.XXXXXXX-1073c8)](https://doi.org/10.5281/zenodo.XXXXXXX) …

Readme badges update

---

CHANGELOG.md
setup.py

Prepare v2.4 release

---

CHANGELOG.md
nf_core/pipeline-template/bin/check_samplesheet.py

Fix header sniffing

---

CHANGELOG.md
setup.py

Ready to be merged as soon as v2.4 is released 🚀

Bump to v2.5dev

---

nf_core/sync.py

This PR removes the self-import in sync.py

do not self-import

---

CHANGELOG.md

update PR number for 1598

---

.github/CONTRIBUTING.md
.pre-commit-config.yaml
requirements-dev.txt

Nobody asked for it, yet here comes a pre-commit hook for isort, black and Prettier. It can be optionally installed by any dev, but doesn't need to be. Pure convenience.

Black, isort and Prettier pre-commit hooks

---

nf_core/utils.py

The variable version at some point held a module and in different parts of the same script a tool version number. This PR removes that ambiguity.

[MAINT] Prevent redefinition of version

---

README.md

This PR adds a Prettier badge to the README.md and removes the capitalization from all code formatting badges.

[MAINT] Prettier badge

---

nf_core/schema.py
nf_core/utils.py

Using lists as default for function arguments can lead to unexpected behaviour and should be avoided.

do not use lists as defaults for function arguments

---

CHANGELOG.md

Harmonize CHANGELOG.md PR-links.

wrap PR links in parentheses

---

nf_core/schema.py

add missing dot

---

CHANGELOG.md
README.md

Update readme to drop --key option from modules list

---

CHANGELOG.md
nf_core/pipeline-template/.github/workflows/linting.yml

Add black linting checks to workflow linting

---

CHANGELOG.md

Update change log for [#1090](https://github.com/nf-core/tools/pull/1090)

update changelog for #1090

---

CHANGELOG.md
nf_core/pipeline-template/.editorconfig
nf_core/pipeline-template/CITATION.cff

Add `CITATION.cff` to pipeline template

---

tests/test_schema.py

fix repeated test name

---

CHANGELOG.md
nf_core/__main__.py
nf_core/launch.py
nf_core/modules/info.py
nf_core/utils.py

Fix pylint-C0301 and simplify control flow.

Fix pylint-C0301

---

CHANGELOG.md
nf_core/lint/__init__.py
nf_core/modules/bump_versions.py
nf_core/modules/lint/__init__.py
nf_core/modules/lint/main_nf.py
nf_core/modules/lint/meta_yml.py
nf_core/modules/lint/module_changes.py
nf_core/modules/lint/module_patch.py
nf_core/modules/lint/module_version.py
nf_core/modules/list.py
nf_core/modules/module_utils.py
nf_core/modules/modules_command.py
nf_core/modules/nfcore_module.py
tests/modules/lint.py
tests/test_modules.py

This PR adds support for custom remotes in `nf-core modules lint`. Closes #1715.

Custom remote modules lint

---

nf_core/modules/lint/module_changes.py
nf_core/modules/lint/module_patch.py
nf_core/modules/lint/module_version.py
nf_core/modules/modules_command.py
nf_core/modules/modules_differ.py
nf_core/modules/nfcore_module.py
nf_core/modules/update.py

remove unused imports

---

nf_core/utils.py

[MAINT] remove useless-else-on-loop

---

nf_core/modules/remove.py

The init method removed has the same footprint as the on e of the inherited objet and is hence superfluous.

remove unnecessary init method

---

nf_core/create.py

explicitly set check

---

requirements-dev.txt
requirements.txt

refgene is now a production requirement.

refgene is a production requirement

---

.github/workflows/create-lint-wf.yml
.github/workflows/create-test-wf.yml
.github/workflows/deploy-pypi.yml
.github/workflows/lint-code.yml
.github/workflows/push_dockerhub_dev.yml
.github/workflows/push_dockerhub_release.yml
.github/workflows/pytest.yml
.github/workflows/sync.yml
.github/workflows/tools-api-docs-dev.yml
.github/workflows/tools-api-docs-release.yml
CHANGELOG.md

add cancel CI run if new run starts

---

CHANGELOG.md

add requirements update pr links to changelog

---

README.md
docs/images/nf-core-create.svg
nf_core/create.py

add documentation for excluding GitHub during pipeline creation

---

CHANGELOG.md
setup.py

Bump to v2.5 for release

---

nf_core/pipeline-template/pyproject.toml

Fix black linting in pipelines.

Add pyproject.toml with black custom parameters

---

.github/workflows/deploy-pypi.yml
CHANGELOG.md

use GitHub PyPI publish action release v1

---

CHANGELOG.md
setup.py

Bump to 2.5.1 to fix black linting in pipelines

bump to 2.5.1

---

CHANGELOG.md

remove v2.6dev from changelog

---

CHANGELOG.md
setup.py

bump to 2.6dev

---

nf_core/pipeline-template/docs/usage.md

add azurebatch info

---

CHANGELOG.md
nf_core/pipeline-template/.github/workflows/awsfulltest.yml
nf_core/pipeline-template/.github/workflows/awstest.yml

Exposes the new debug log file from the action to be downloaded

Add actions/upload-artifact to the awstest workflows

---

.github/workflows/fix-linting.yml

It does prettier, black and isort. Made the commit message a bit more generic.

Tweak confusing commit message

---

tests/test_list.py

fix typo in test class name

---

CHANGELOG.md
nf_core/pipeline-template/modules.json
nf_core/pipeline-template/modules/nf-core/modules/multiqc/main.nf
nf_core/pipeline-template/modules/nf-core/modules/multiqc/meta.yml
nf_core/pipeline-template/nextflow.config
nf_core/pipeline-template/nextflow_schema.json
nf_core/pipeline-template/workflows/pipeline.nf

Updates MultiQC to latest module version, correctly passes config file, and leaves note to add logo for display

Update MultiQC in pipeline template

---

CHANGELOG.md
nf_core/pipeline-template/modules.json
nf_core/pipeline-template/modules/nf-core/modules/multiqc/main.nf
nf_core/pipeline-template/modules/nf-core/modules/multiqc/meta.yml
nf_core/pipeline-template/workflows/pipeline.nf

Update multiQC to allow extra configs

---

CHANGELOG.md
nf_core/pipeline-template/main.nf

Fixes the template spacing, which was lost after adding JINJA logic evaluation. 
Closes #1826

fix template spacing

---

CHANGELOG.md
setup.py

Bump to version 2.6 for release

bump to v2.6

---

nf_core/module-template/tests/test.yml

Jinja whitespace

---

nf_core/modules/modules_json.py

try to find module sha with the old repo path structure

---

CHANGELOG.md
nf_core/modules/modules_command.py

do not remove local copy of modules repo

---

nf_core/pipeline-template/docs/usage.md

easier descriptions for daily users #1293

---

nf_core/module-template/modules/main.nf
nf_core/modules/create.py

The links to the nf-core github in the template were broken.  This pull request updates those example URLs.

Fix URLs in module template

---

README.md

Fixes issue #1339
Removed tick that lead to wrong words were highlighted

Remove tick in the wrong place

---

nf_core/modules/install.py
nf_core/subworkflows/install.py

remove include statements and install recursive modules from same remote

---

nf_core/modules/modules_repo.py
nf_core/modules/test_yml_builder.py
nf_core/pipeline-template/docs/usage.md
nf_core/subworkflows/test_yml_builder.py

Fixes #1922 which was confusing people generating test yml using `contains`

Fix test yml contains

---

nf_core/pipeline-template/.github/workflows/ci.yml

Fix critical bug in template formatting

---

tests/test_launch.py
tests/test_schema.py
tests/test_sync.py
tests/test_utils.py

- Use pytest.raises instead of custom try except blocks.
- Use touch instead of open and close to create empty files.
- Removed some useless else.

Pytest raises

---

CHANGELOG.md
README.md

3.7 is the next version to be deprecated (2023-06-27) - I think it makes sense to promote a version that will not be deprecated within months.

promote the use of Python 3.8 instead of 3.7

---

requirements-dev.txt

Sort the requirements alphabetically and standardize the requirement names to use das instead of underscores.

Sort requirements dev

---

nf_core/modules/modules_json.py
nf_core/modules/modules_repo.py
nf_core/subworkflows/install.py

Smaller fixes to make it run in my local test case

Fix subworkflows install command

---

.github/workflows/lint-code.yml
CHANGELOG.md

bump isort action version

---

nf_core/components/components_utils.py

A small fix to an erroneous variable name I discovered. 
We should also consider ensuring this method is tested in future.

Fix variable name

---

CHANGELOG.md
nf_core/__main__.py

Don't print the filename + line number in log calls

---

nf_core/pipeline-template/.gitattributes

I think that this should give the nf-test files syntax highlighting on Github.com

Nextflow syntax highlighting for nf-test

---

nf_core/modules/modules_json.py

This PR adapts a method call to the changes in the method name and signature.

Fix name of ModuleJson method call

---

nf_core/__main__.py

I thought I checked all instances 🙃

fix subworkflow info command

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/workflows/create-lint-wf.yml
.github/workflows/create-test-wf.yml
nf_core/lint/readme.py
nf_core/pipeline-template/.github/ISSUE_TEMPLATE/bug_report.yml
nf_core/pipeline-template/.github/workflows/ci.yml
nf_core/pipeline-template/README.md
nf_core/pipeline-template/nextflow.config

update minimum nextflow version to 22.10.1

---

nf_core/components/info.py
nf_core/components/install.py
nf_core/components/update.py

sort choices in prompts alphabetically

---

nf_core/__main__.py

Add subworkflows test command to __main__.py

---

nf_core/__main__.py
nf_core/components/remove.py
nf_core/modules/modules_json.py
nf_core/modules/remove.py
nf_core/subworkflows/remove.py
tests/modules/remove.py
tests/test_modules.py

Return remote params to remove commands

---

.github/workflows/create-lint-wf.yml
tests/modules/patch.py
tests/utils.py

after clean-up of the branch names on gitlab

update gitlab branches

---

nf_core/components/install.py
nf_core/components/remove.py
nf_core/modules/modules_json.py
requirements-dev.txt
tests/subworkflows/remove.py
tests/test_subworkflows.py

Make remove command recursive

---

nf_core/components/install.py
nf_core/modules/modules_json.py

Avoid duplicates from install tracking in `modules.json`

Avoid duplicates from install tracking

---

CHANGELOG.md
nf_core/modules/modules_json.py

allow other urls not starting with http

---

CHANGELOG.md
nf_core/pipeline-template/nextflow.config

description between double quotes

---

CHANGELOG.md
nf_core/components/remove.py
nf_core/modules/modules_json.py

Avoid trying to remove components by duplicate

---

nf_core/components/install.py
nf_core/utils.py

Absolute path was messing with logging.

Return the relative path of the determined base dir

---

CHANGELOG.md
nf_core/pipeline-template/.prettierignore

don't run prettier on files in bin/

---

.devcontainer/devcontainer.json
.gitpod.yml
.pre-commit-config.yaml
CHANGELOG.md

Added 'pre-commit install` to codespaces config and gitpod setup (hopefully it will work like that 🤞🏻)

Init pre commit in online IDEs

---

nf_core/modules/lint/main_nf.py
tests/utils.py

Apply suggestion from @mashehu in [#2088comment](https://github.com/nf-core/tools/pull/2088#issuecomment-1335288771)

change requests get by head

---

CHANGELOG.md

Updating Changelog for previous PR

Add line to changelog

---

nf_core/components/update.py

Fix subworkflows update command to work for non-nf-core repos

---

CHANGELOG.md
setup.py

Getting ready for the release 🥳

reformat changelog

---

CHANGELOG.md
nf_core/pipeline-template/workflows/pipeline.nf

Revert `unique()` syntax change. 

---

README.md

Clean version of https://github.com/nf-core/tools/pull/2151 without the confused git history

Add singularity note for offline use

---

nf_core/__main__.py
nf_core/schema.py

Fixes #2148 
Also fixes some issues with newline characters in markdown tables of the output from `nf-core schema docs`

Schema docs fix output

---

nf_core/gitpod/gitpod.Dockerfile

based on https://github.com/nextflow-io/training/blob/master/.github/gitpod.Dockerfile

update gitpod dockerfile

---

nf_core/pipeline-template/lib/WorkflowMain.groovy

Two methods WorkflowMain::help and WorkflowMain::paramsSummaryLog use a
"log" argument that is not used in the method body. This commit removes
those arguments and their references.

Remove unused "log" args

---

nf_core/module-template/modules/meta.yml

fix indentation in modules template meta.yml

---

nf_core/pipeline-template/README.md

Add mastodon badge to readme template

---

CHANGELOG.md
setup.py

bump to version 2.8 for release

---

.gitpod.yml

Change gitpod container for 2.8 release

---

CHANGELOG.md

Move some changelog points which were added to the last version by mistake.

move misplaced changelog points

---

nf_core/pipeline-template/lib/WorkflowPipeline.groovy
nf_core/pipeline-template/main.nf

fix template new lines

---

.gitpod.yml
CHANGELOG.md
setup.py

bump version to 2.9dev

---

nf_core/pipeline-template/README.md

Doesn't need changelog, too small

Typo tweaks and minor clarifications

---

nf_core/pipeline-template/nextflow.config

Fix indent

---

nf_core/pipeline-template/.github/workflows/awsfulltest.yml
nf_core/pipeline-template/.github/workflows/awstest.yml

Remove aws_tower profile

---

.github/CONTRIBUTING.md
nf_core/pipeline-template/.github/CONTRIBUTING.md
nf_core/pipeline-template/CITATIONS.md

The Dockerfile in `CONTRIBUTING.md` pipeline template is outdated and there were some citations missing and needed formatting.

Remove Dockerfile from contributing + Add citations

---

CHANGELOG.md
nf_core/refgenie.py

create .nextflow/nf-core if it doesn't exist

---

nf_core/pipeline-template/.github/workflows/awsfulltest.yml

FEAT: Add slack notification for megatests

---

.gitpod.yml
CHANGELOG.md
setup.py

Bump to v2.9

---

README.md

Fix readme images from rich-codex

---

README.md

Revert "rich-codex remove modules repo folder before clone"

---

README.md

remove cd modules

---

.gitpod.yml
CHANGELOG.md
setup.py

I forgot to bump the version after the release! 😱 🤫

bump to 2.10dev

---

.github/RELEASE_CHECKLIST.md
nf_core/pipeline-template/modules.json
nf_core/pipeline-template/modules/nf-core/custom/dumpsoftwareversions/main.nf
nf_core/pipeline-template/modules/nf-core/fastqc/main.nf
nf_core/pipeline-template/modules/nf-core/multiqc/main.nf

Update modules in TEMPLATE

---

nf_core/sync.py

Address https://nfcore.slack.com/archives/C04QR0T3G3H/p1689238511278679

Fix link template PR message

---

nf_core/pipeline-template/CITATIONS.md

Remove bare URL in MD file.
Plus we already have this exact link in the tool name.

Remove bare URL in CITATIONS.md

---

CHANGELOG.md
nf_core/pipeline-template/conf/modules.config

Close https://github.com/nf-core/tools/issues/2271

Add multiqc to modules.config

---

CHANGELOG.md
nf_core/launch.py

Fix getting the revision from prompts when running nf-core launch

---

docs/api/_src/index.md
docs/api/_src/subworkflow_lint_tests/module_changes.md
docs/api/_src/subworkflow_lint_tests/module_tests.md
docs/api/_src/subworkflow_lint_tests/module_todos.md
docs/api/_src/subworkflow_lint_tests/module_version.md
docs/api/_src/subworkflow_lint_tests/subworkflow_changes.md
docs/api/_src/subworkflow_lint_tests/subworkflow_tests.md
docs/api/_src/subworkflow_lint_tests/subworkflow_todos.md
docs/api/_src/subworkflow_lint_tests/subworkflow_version.md
docs/api/make_lint_md.py

This will hopefully generate lint API docs 🤞 

---

nf_core/pipeline-template/lib/WorkflowPipeline.groovy

Add `nf-core:` suffix to a `TODO` comment, so that it's picked up by `nf-core lint`

Change `TODO` to `TODO nf-core`

---

nf_core/components/remove.py

changing the grammar so that the noun+verb becomes a pronoun

---

CHANGELOG.md
nf_core/create.py

warning when custom workflow name contains special characters

---

nf_core/pipeline-template/.github/workflows/release-announcments.yml

remove inexisten variable VERSION from send-tweet github workflow

---

CHANGELOG.md
nf_core/bump_version.py

Close https://github.com/nf-core/tools/issues/2344

bump version of nf-test snap files

---

CHANGELOG.md
nf_core/pipeline-template/nextflow.config

The Gitpod environment resources were reduced at some point. This updates the profile to use the standard environment settings.

Update Gitpod profile to reflect environment allowance

---

.gitpod.yml
CHANGELOG.md
setup.py

bump to 2.10 for release

---

Dockerfile

install default-jre instead of openjdk-11-jre

---

.github/workflows/pytest.yml
nf_core/utils.py

This should increase the success rate of CI runs (or make them even longer before they fail)

add retry functionality to github requests

---

nf_core/module-template/modules/main.nf
nf_core/modules/create.py

Fixes #2466 
Implemented by setting `self.tool` for the `ModuleCreate` class

Fix module tool value empty in template

---

CHANGELOG.md
nf_core/pipeline-template/docs/usage.md

Will look something like this:

add csv syntax highlighting in template

---

nf_core/modules/lint/meta_yml.py

related to the changes in https://github.com/nf-core/modules/pull/4318#pullrequestreview-1724477394

handle custom error messages from schemas

---

.github/workflows/lint-code.yml

Let's try this!
We just need to be sure that this test is run every 90 days on the target branch, see https://github.com/marketplace/actions/mypy-imprecision-check#limitations

Add mypy check

---

.github/workflows/lint-code.yml

Revert "Add mypy check"

---

nf_core/components/components_test.py
nf_core/utils.py
tests/components/generate_snapshot.py
tests/components/snapshot_test.py
tests/modules/lint.py
tests/test_test_utils.py
tests/test_utils.py
tests/utils.py

move set_wd from tests/utils.py to utils.py

---

nf_core/__main__.py
nf_core/components/lint/__init__.py
nf_core/components/nfcore_component.py
nf_core/subworkflows/lint/subworkflow_tests.py

fixes #https://github.com/nf-core/modules/pull/4414 and #2547

Fix swf test error

---

nf_core/module-template/modules/main.nf

Shortens the module template version string to remove the unnecessary echo and use a shorter sed manipulation.

Simplify module template version string

---

.github/workflows/pytest.yml
.gitpod.yml
CHANGELOG.md
nf_core/pipeline-template/.gitpod.yml

Unset env variable JAVA_TOOL_OPTIONS in gitpod

---

README.md
nf_core/pipeline-template/README.md

So that they can be rendered both on github and on the website

fix admonitions

---

.pre-commit-config.yaml

Reverts nf-core/tools#2598
switch to ruff instead

Revert "Update pre-commit hook psf/black to v23.12.0"

---

nf_core/components/nfcore_component.py

handle stageAs in input parsing correctly

---

.github/workflows/changelog.py
.github/workflows/changelog.yml

code taken from MultiQC and customized for our use case
Not sure if it will work, but let's see... 🤞🏻

Automatically create changelog entries from PRs

---

.github/workflows/fix-linting.yml
README.md

add more verbose fix-linting bot

---

.github/renovate.json5
.github/workflows/changelog.yml
CHANGELOG.md

fix ignorepath

---

CHANGELOG.md
nf_core/modules/lint/module_changes.py

Close https://github.com/nf-core/tools/issues/2659

Modules: Fix linting of a pipeline with patched custom module

---

.github/workflows/fix-linting.yml

Unfortunately, I need to merge this to test it in a second PR...

debug fix-linting comment [no changelog]

---

.github/workflows/fix-linting.yml
nf_core/create.py
nf_core/create_logo.py
nf_core/pipeline-template/.github/workflows/fix-linting.yml

template: add 👀👍🏻🎉😕 reactions to fix-linting bot action

---

.github/workflows/fix-linting.yml
CHANGELOG.md
nf_core/create.py
nf_core/create_logo.py
nf_core/pipeline-template/.github/workflows/fix-linting.yml

Revert "template: add 👀👍🏻🎉😕 reactions to fix-linting bot action"

---

.gitpod.yml
CHANGELOG.md
setup.py

Bump version to 2.12.1

---

.github/workflows/tools-api-docs.yml

fix api docs build request (next attempt) [skip changelog]

---

nf_core/pipeline-template/README.md
nf_core/pipeline-template/subworkflows/local/utils_nfcore_pipeline_pipeline/main.nf

Templates: update Nextflow Tower -> Seqera Platform badge and keep some newlines in local subworkflow

---

CHANGELOG.md
nf_core/pipeline-template/.github/CONTRIBUTING.md
nf_core/pipeline-template/.github/PULL_REQUEST_TEMPLATE.md

adding instructions to run all tests to contributing with debug and also update PR template with nf-test instructions

add nf-test test instructions to contributing and PR template

---

CHANGELOG.md
nf_core/pipeline-template/.github/workflows/ci.yml
nf_core/pipeline-template/.github/workflows/download_pipeline.yml
nf_core/pipeline-template/.github/workflows/linting.yml

setup-nextflow v2 has released! Here are some updates to make the templates use the new, non-rate-limited version.

Update templates to use nf-core/setup-nextflow v2

---

CHANGELOG.md
nf_core/pipeline-template/nextflow.config

Fix https://nfcore.slack.com/archives/CE5LG7WMB/p1709630446594579

Template: Remove fasta default from nextflow.config

---

nf_core/components/nfcore_component.py

Prevents breaking the progress bar when running linting

Log debug instead of info for module input/outputs

---

CHANGELOG.md
nf_core/schema.py

fix: ensure path object converted to string before stripping quotes

---

CHANGELOG.md
nf_core/pipeline-template/workflows/pipeline.nf

fix(collectfile): sort true for methods_description_mqc.yaml

---

CHANGELOG.md
nf_core/pipeline-template/nextflow.config

Fix a line break introduced by jinja on nextflow.config
Remove duplicates from CHANGELOG.md
Add missing PRs to CHANGELOG.md
Move changes to the correct section of CHANGELOG.md

Restructure CHANGELOG.md

---

.gitpod.yml
CHANGELOG.md
setup.py

~we didn't reset gitpod.yml to `dev`, so it's still on `latest`~

version bump to 2.14.1

---

CHANGELOG.md
README.md

README - absolute image paths

---

nf_core/modules/lint/main_nf.py

Close: https://github.com/nf-core/tools/issues/3000

Components: Modules: allow multiline module input tuple

---

CHANGELOG.md
MANIFEST.in

add templatefeatures.yml to python package

---

nf_core/__main__.py

Trying to solve https://github.com/nf-core/tools/issues/2554

Add a verbose option for nf-core modules test

---

nf_core/pipeline-template/nextflow.config

bump nf-schema to v2.1.1 in the template

---

nf_core/pipeline-template/nextflow.config

Follow up https://github.com/nf-core/tools/pull/3037

Remove check_max() [skip changelog]

---

nf_core/pipelines/lint/nextflow_config.py
nf_core/pipelines/schema.py

assign schema_default when a param is found in the schema but not in the config

Linting: Fix bug when linting schema params

---

CHANGELOG.md
nf_core/pipeline-template/nextflow.config

- Add line break
- Fix indentation

Template: Fix Manifest DOI text

---

nf_core/__main__.py

Fix logo typo in help message for create logos

---

CHANGELOG.md
nf_core/pipeline-template/nextflow.config

Adds resource limits to Gitpod

Template: Add resource limits to Gitpod profile

---

CHANGELOG.md
nf_core/gitpod/gitpod.Dockerfile

The defaults channel still appears to be in use with the Miniconda installer. Replacing with Miniforge which doesn't have it.

Gitpod miniforge

---

CHANGELOG.md
nf_core/pipeline-template/nextflow.config

Close https://github.com/nf-core/tools/issues/3289

Template: Add `manifest.contributors` to `nextflow.config`

---

CHANGELOG.md
nf_core/subworkflows/lint/subworkflow_tests.py

Improve subworkflow nf-test migration warning

---

.gitpod.yml
nf_core/pipeline-template/.gitpod.yml

Simplify extension maintenance for gitpod extensions.

Update gitpod vscode extensions to use nf-core extension pack

---

CHANGELOG.md
requirements-dev.txt

Reverting the version update since it breaks the logging console

Revert textual dev 1.7.0 [no changelog]

---

nf_core/pipelines/sync.py

Revert "don't set up loggin level to error [no changelog]"

---

CHANGELOG.md
nf_core/pipeline-template/docs/usage.md

Add missing p

---

CHANGELOG.md
nf_core/utils.py

Close https://github.com/nf-core/tools/issues/3359

Use `manifest.contributors` names if available, otherwise default to `manifest.author`

---

.github/workflows/sync.yml
CHANGELOG.md

Close https://github.com/nf-core/tools/issues/3390
Tested with nf-core/eager which was failing before, a new sync PR was open correctly. https://github.com/nf-core/tools/actions/runs/12763988002/job/35575245107

General: Fix sync GHA by removing quotes from parsed branch name

---

CHANGELOG.md
nf_core/pipeline-template/nextflow.config

Update nf-schema in the template to 2.3.0

update nf-schema version

---

CHANGELOG.md
nf_core/pipeline-template/README.md

TEMPLATE - Remove Twitter from README

---

CHANGELOG.md
nf_core/components/nfcore_component.py

fix: linting with comments after the input directive

---

CHANGELOG.md
README.md

docs: fix contributing link in the main README

---

CHANGELOG.md
nf_core/module-template/main.nf
nf_core/module-template/meta.yml

https://github.com/nf-core/website/pull/3096#discussion_r1965183066
Thanks @mahesh-panchal for pointing this

Modules: increase meta index for multiple input channels

---

CHANGELOG.md
nf_core/pipeline-template/README.md

Template: Add Bluesky badge to readme

---

CHANGELOG.md
nf_core/modules/modules_utils.py

Rationale at: https://github.com/nf-core/tools/issues/3511

Changing retrieval of file extension from EDAM

---

CHANGELOG.md
nf_core/modules/lint/__init__.py

Refactor ontologies addition code (common in input and output)
Addressing assignation of files (versions.yml) and also addressing issues such as https://github.com/nf-core/tools/issues/3496

Refactor adding EDAM ontologies and allowing detect more patterns (e.g., versions.yml)

---

CHANGELOG.md
docs/api/_src/pipeline_lint_tests/included_configs.md

fixes reported error in https://nfcore.slack.com/archives/CE7DN1U7M/p1743091006940629 (once I regenerate the api docs on the website

Fix indentation in included_configs API docs

---

nf_core/components/nfcore_component.py

This should address issue here: https://github.com/nf-core/tools/issues/3513

adding boundary in regex

---

nf_core/components/nfcore_component.py

Handling issue [#3530](https://github.com/nf-core/tools/issues/3530)

Handling issue with arity #3530

---

.github/workflows/nextflow-source-test.yml

Follow on from https://github.com/nf-core/tools/pull/3553 after I actually did the grunt work of testing the action and making sure it works as intended.
Should be good to go now.

Nextflow build from source

---

CHANGELOG.md
nf_core/components/nfcore_component.py
tests/modules/test_lint.py

Coming from https://github.com/nf-core/tools/issues/3530

Linting: Addressing more cases than can happen when processing input and output values

---

nf_core/modules/lint/environment_yml.py
requirements.txt
tests/modules/test_lint.py
tests/test_modules.py

fixes https://github.com/nf-core/tools/issues/3461 and https://github.com/nf-core/modules/issues/5814

Handle nested dependencies in `environment.yml`

---

.gitpod.yml
CHANGELOG.md
setup.py
tests/modules/test_lint.py

Since we merged a change in the modules repo modifying the JSON schema of environment.yml in modules, one of our tests failed. The main linting error that we are checking in this test is `test_main_tags` so I removed the one that is not failing anymore.

Bump version to 3.3.0

---

CHANGELOG.md
nf_core/pipeline-template/.github/workflows/nf-test.yml

TEMPALTE: Remove more occurences of NFT_DIFF

---

CHANGELOG.md
nf_core/pipeline-template/.github/workflows/nf-test.yml

TEMPLATE - CI - Only trigger nf-test action on pull_request

---

CHANGELOG.md
nf_core/pipelines/lint/pipeline_if_empty_null.py
nf_core/utils.py

Fixing an issue found with nf-core/mag where the lint test was stuck trying to open too many files https://nfcore.slack.com/archives/CE5LG7WMB/p1755845835047829

ignore files in gitignore also for pipeline_if_empty_null lint test

---

CHANGELOG.md
nf_core/pipeline-template/.prettierignore

Noticed that prettier was checking all content in the (residual) .nf-test dirs.

Add .nf-test/ to prettier ignore list

---

CHANGELOG.md
tests/test_modules.py

Update pytest tests after https://github.com/nf-core/modules/pull/9174

Override example keywords in modules test
